//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4.1.9004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4.1.9004 C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g 2012-07-09 07:25:16

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;

namespace  StatsDirect.Expressions 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4.1.9004")]
[System.CLSCompliant(false)]
public partial class StatsDirectExpressionParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "A", "AND", "B", "BACKSLASH", "C", "CARET", "COMMA", "D", "E", "EE", "EQ", "EXCLAIM", "EXPONENT", "F", "FALSE", "FLOAT", "G", "GE", "GETS", "GT", "H", "I", "IDENTIFIER", "INTEGER", "J", "K", "L", "LE", "LPAREN", "LR", "LT", "M", "MINUS", "MOD", "N", "NE", "NOT", "O", "OR", "P", "PI", "PLUS", "Q", "R", "RPAREN", "S", "SLASH", "STAR", "STARSTAR", "STRING", "T", "TRUE", "U", "V", "W", "WS", "X", "Y", "Z"
	};
	public const int EOF=-1;
	public const int A=4;
	public const int AND=5;
	public const int B=6;
	public const int BACKSLASH=7;
	public const int C=8;
	public const int CARET=9;
	public const int COMMA=10;
	public const int D=11;
	public const int E=12;
	public const int EE=13;
	public const int EQ=14;
	public const int EXCLAIM=15;
	public const int EXPONENT=16;
	public const int F=17;
	public const int FALSE=18;
	public const int FLOAT=19;
	public const int G=20;
	public const int GE=21;
	public const int GETS=22;
	public const int GT=23;
	public const int H=24;
	public const int I=25;
	public const int IDENTIFIER=26;
	public const int INTEGER=27;
	public const int J=28;
	public const int K=29;
	public const int L=30;
	public const int LE=31;
	public const int LPAREN=32;
	public const int LR=33;
	public const int LT=34;
	public const int M=35;
	public const int MINUS=36;
	public const int MOD=37;
	public const int N=38;
	public const int NE=39;
	public const int NOT=40;
	public const int O=41;
	public const int OR=42;
	public const int P=43;
	public const int PI=44;
	public const int PLUS=45;
	public const int Q=46;
	public const int R=47;
	public const int RPAREN=48;
	public const int S=49;
	public const int SLASH=50;
	public const int STAR=51;
	public const int STARSTAR=52;
	public const int STRING=53;
	public const int T=54;
	public const int TRUE=55;
	public const int U=56;
	public const int V=57;
	public const int W=58;
	public const int WS=59;
	public const int X=60;
	public const int Y=61;
	public const int Z=62;

	#if ANTLR_DEBUG
		private static readonly bool[] decisionCanBacktrack =
			new bool[]
			{
				false, // invalid decision
				false, false, false, false, false, false, false, false, false, false, 
				false, false, false, false, false, false
			};
	#else
		private static readonly bool[] decisionCanBacktrack = new bool[0];
	#endif
	public StatsDirectExpressionParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public StatsDirectExpressionParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}

	public override string[] TokenNames { get { return StatsDirectExpressionParser.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g"; } }


	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

	#region Rules

	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_start() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_start() {}
	// $ANTLR start "start"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:6:8: public start returns [string builtExpression] : ( EQ )? expr EOF ;
	[GrammarRule("start")]
	public string start()
	{
		EnterRule_start();
		EnterRule("start", 1);
		TraceIn("start", 1);
	    string builtExpression = default(string);


	    string expr1 = default(string);

		try { DebugEnterRule(GrammarFileName, "start");
		DebugLocation(6, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:7:2: ( ( EQ )? expr EOF )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:7:4: ( EQ )? expr EOF
			{
			DebugLocation(7, 4);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:7:4: ( EQ )?
			int alt1=2;
			try { DebugEnterSubRule(1);
			try { DebugEnterDecision(1, decisionCanBacktrack[1]);
			int LA1_1 = input.LA(1);

			if ((LA1_1==EQ))
			{
				alt1 = 1;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:7:4: EQ
				{
				DebugLocation(7, 4);
				Match(input,EQ,Follow._EQ_in_start32); 

				}
				break;

			}
			} finally { DebugExitSubRule(1); }

			DebugLocation(7, 8);
			PushFollow(Follow._expr_in_start35);
			expr1=expr();
			PopFollow();

			DebugLocation(7, 13);
			Match(input,EOF,Follow._EOF_in_start37); 
			DebugLocation(7, 17);
			 builtExpression = expr1; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("start", 1);
			LeaveRule("start", 1);
			LeaveRule_start();
	    }
	 	DebugLocation(8, 1);
		} finally { DebugExitRule(GrammarFileName, "start"); }
		return builtExpression;

	}
	// $ANTLR end "start"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_expr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_expr() {}
	// $ANTLR start "expr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:10:1: expr returns [string builtExpression] : lhs= andexpr (op= OR rhs= andexpr )* ;
	[GrammarRule("expr")]
	private string expr()
	{
		EnterRule_expr();
		EnterRule("expr", 2);
		TraceIn("expr", 2);
	    string builtExpression = default(string);


	    IToken op = default(IToken);
	    string lhs = default(string);
	    string rhs = default(string);

		try { DebugEnterRule(GrammarFileName, "expr");
		DebugLocation(10, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:11:2: (lhs= andexpr (op= OR rhs= andexpr )* )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:11:4: lhs= andexpr (op= OR rhs= andexpr )*
			{
			DebugLocation(11, 7);
			PushFollow(Follow._andexpr_in_expr56);
			lhs=andexpr();
			PopFollow();

			DebugLocation(11, 16);
			 builtExpression = lhs; 
			DebugLocation(12, 3);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:12:3: (op= OR rhs= andexpr )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, decisionCanBacktrack[2]);
				int LA2_1 = input.LA(1);

				if ((LA2_1==OR))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:12:4: op= OR rhs= andexpr
					{
					DebugLocation(12, 6);
					op=(IToken)Match(input,OR,Follow._OR_in_expr65); 
					DebugLocation(12, 13);
					PushFollow(Follow._andexpr_in_expr69);
					rhs=andexpr();
					PopFollow();

					DebugLocation(12, 22);
					 builtExpression = "(" + builtExpression + " || " + rhs + ")"; 

					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("expr", 2);
			LeaveRule("expr", 2);
			LeaveRule_expr();
	    }
	 	DebugLocation(13, 1);
		} finally { DebugExitRule(GrammarFileName, "expr"); }
		return builtExpression;

	}
	// $ANTLR end "expr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_andexpr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_andexpr() {}
	// $ANTLR start "andexpr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:15:1: andexpr returns [string builtExpression] : lhs= notexpr (op= AND rhs= notexpr )* ;
	[GrammarRule("andexpr")]
	private string andexpr()
	{
		EnterRule_andexpr();
		EnterRule("andexpr", 3);
		TraceIn("andexpr", 3);
	    string builtExpression = default(string);


	    IToken op = default(IToken);
	    string lhs = default(string);
	    string rhs = default(string);

		try { DebugEnterRule(GrammarFileName, "andexpr");
		DebugLocation(15, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:16:2: (lhs= notexpr (op= AND rhs= notexpr )* )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:16:4: lhs= notexpr (op= AND rhs= notexpr )*
			{
			DebugLocation(16, 7);
			PushFollow(Follow._notexpr_in_andexpr91);
			lhs=notexpr();
			PopFollow();

			DebugLocation(16, 16);
			 builtExpression = lhs; 
			DebugLocation(17, 3);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:17:3: (op= AND rhs= notexpr )*
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, decisionCanBacktrack[3]);
				int LA3_1 = input.LA(1);

				if ((LA3_1==AND))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch ( alt3 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:17:4: op= AND rhs= notexpr
					{
					DebugLocation(17, 6);
					op=(IToken)Match(input,AND,Follow._AND_in_andexpr100); 
					DebugLocation(17, 14);
					PushFollow(Follow._notexpr_in_andexpr104);
					rhs=notexpr();
					PopFollow();

					DebugLocation(17, 23);
					 builtExpression = "(" + builtExpression + " && " + rhs + ")"; 

					}
					break;

				default:
					goto loop3;
				}
			}

			loop3:
				;

			} finally { DebugExitSubRule(3); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("andexpr", 3);
			LeaveRule("andexpr", 3);
			LeaveRule_andexpr();
	    }
	 	DebugLocation(18, 1);
		} finally { DebugExitRule(GrammarFileName, "andexpr"); }
		return builtExpression;

	}
	// $ANTLR end "andexpr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_notexpr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_notexpr() {}
	// $ANTLR start "notexpr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:20:1: notexpr returns [string builtExpression] : ( ( NOT rhs= relexpr ) | relexpr );
	[GrammarRule("notexpr")]
	private string notexpr()
	{
		EnterRule_notexpr();
		EnterRule("notexpr", 4);
		TraceIn("notexpr", 4);
	    string builtExpression = default(string);


	    string rhs = default(string);
	    string relexpr2 = default(string);

		try { DebugEnterRule(GrammarFileName, "notexpr");
		DebugLocation(20, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:21:2: ( ( NOT rhs= relexpr ) | relexpr )
			int alt4=2;
			try { DebugEnterDecision(4, decisionCanBacktrack[4]);
			int LA4_1 = input.LA(1);

			if ((LA4_1==NOT))
			{
				alt4 = 1;
			}
			else if ((LA4_1==EE||(LA4_1>=FALSE && LA4_1<=FLOAT)||(LA4_1>=IDENTIFIER && LA4_1<=INTEGER)||(LA4_1>=LPAREN && LA4_1<=LR)||LA4_1==MINUS||LA4_1==PI||LA4_1==TRUE))
			{
				alt4 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 4, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:21:4: ( NOT rhs= relexpr )
				{
				DebugLocation(21, 4);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:21:4: ( NOT rhs= relexpr )
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:21:6: NOT rhs= relexpr
				{
				DebugLocation(21, 6);
				Match(input,NOT,Follow._NOT_in_notexpr126); 
				DebugLocation(21, 13);
				PushFollow(Follow._relexpr_in_notexpr130);
				rhs=relexpr();
				PopFollow();

				DebugLocation(21, 22);
				 builtExpression = "(!(" + rhs + "))"; 

				}


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:22:4: relexpr
				{
				DebugLocation(22, 4);
				PushFollow(Follow._relexpr_in_notexpr139);
				relexpr2=relexpr();
				PopFollow();

				DebugLocation(22, 12);
				 builtExpression = relexpr2; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("notexpr", 4);
			LeaveRule("notexpr", 4);
			LeaveRule_notexpr();
	    }
	 	DebugLocation(23, 1);
		} finally { DebugExitRule(GrammarFileName, "notexpr"); }
		return builtExpression;

	}
	// $ANTLR end "notexpr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_relexpr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_relexpr() {}
	// $ANTLR start "relexpr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:25:1: relexpr returns [string builtExpression] : lhs= numexpr (op= relop rhs= numexpr )? ;
	[GrammarRule("relexpr")]
	private string relexpr()
	{
		EnterRule_relexpr();
		EnterRule("relexpr", 5);
		TraceIn("relexpr", 5);
	    string builtExpression = default(string);


	    string lhs = default(string);
	    string op = default(string);
	    string rhs = default(string);

		try { DebugEnterRule(GrammarFileName, "relexpr");
		DebugLocation(25, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:26:2: (lhs= numexpr (op= relop rhs= numexpr )? )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:26:4: lhs= numexpr (op= relop rhs= numexpr )?
			{
			DebugLocation(26, 7);
			PushFollow(Follow._numexpr_in_relexpr158);
			lhs=numexpr();
			PopFollow();

			DebugLocation(26, 16);
			 builtExpression = lhs; 
			DebugLocation(27, 3);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:27:3: (op= relop rhs= numexpr )?
			int alt5=2;
			try { DebugEnterSubRule(5);
			try { DebugEnterDecision(5, decisionCanBacktrack[5]);
			int LA5_1 = input.LA(1);

			if ((LA5_1==EQ||LA5_1==GE||LA5_1==GT||LA5_1==LE||LA5_1==LT||LA5_1==NE))
			{
				alt5 = 1;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:27:4: op= relop rhs= numexpr
				{
				DebugLocation(27, 6);
				PushFollow(Follow._relop_in_relexpr167);
				op=relop();
				PopFollow();

				DebugLocation(27, 16);
				PushFollow(Follow._numexpr_in_relexpr171);
				rhs=numexpr();
				PopFollow();

				DebugLocation(27, 25);
				 builtExpression = "(" + builtExpression + " " + op + " " + rhs + ")"; 

				}
				break;

			}
			} finally { DebugExitSubRule(5); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("relexpr", 5);
			LeaveRule("relexpr", 5);
			LeaveRule_relexpr();
	    }
	 	DebugLocation(28, 1);
		} finally { DebugExitRule(GrammarFileName, "relexpr"); }
		return builtExpression;

	}
	// $ANTLR end "relexpr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_numexpr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_numexpr() {}
	// $ANTLR start "numexpr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:30:1: numexpr returns [string builtExpression] : lhs= mulexpr (op= addop rhs= mulexpr )* ;
	[GrammarRule("numexpr")]
	private string numexpr()
	{
		EnterRule_numexpr();
		EnterRule("numexpr", 6);
		TraceIn("numexpr", 6);
	    string builtExpression = default(string);


	    string lhs = default(string);
	    string op = default(string);
	    string rhs = default(string);

		try { DebugEnterRule(GrammarFileName, "numexpr");
		DebugLocation(30, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:31:2: (lhs= mulexpr (op= addop rhs= mulexpr )* )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:31:4: lhs= mulexpr (op= addop rhs= mulexpr )*
			{
			DebugLocation(31, 7);
			PushFollow(Follow._mulexpr_in_numexpr193);
			lhs=mulexpr();
			PopFollow();

			DebugLocation(31, 16);
			 builtExpression = lhs; 
			DebugLocation(32, 3);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:32:3: (op= addop rhs= mulexpr )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, decisionCanBacktrack[6]);
				int LA6_1 = input.LA(1);

				if ((LA6_1==MINUS||LA6_1==PLUS))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:32:4: op= addop rhs= mulexpr
					{
					DebugLocation(32, 6);
					PushFollow(Follow._addop_in_numexpr202);
					op=addop();
					PopFollow();

					DebugLocation(32, 16);
					PushFollow(Follow._mulexpr_in_numexpr206);
					rhs=mulexpr();
					PopFollow();

					DebugLocation(32, 25);
					 builtExpression = "(" + builtExpression + " " + op + " " + rhs + ")"; 

					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("numexpr", 6);
			LeaveRule("numexpr", 6);
			LeaveRule_numexpr();
	    }
	 	DebugLocation(33, 1);
		} finally { DebugExitRule(GrammarFileName, "numexpr"); }
		return builtExpression;

	}
	// $ANTLR end "numexpr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_mulexpr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_mulexpr() {}
	// $ANTLR start "mulexpr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:35:1: mulexpr returns [string builtExpression] : lhs= powexpr (op= mulop rhs= powexpr )* ;
	[GrammarRule("mulexpr")]
	private string mulexpr()
	{
		EnterRule_mulexpr();
		EnterRule("mulexpr", 7);
		TraceIn("mulexpr", 7);
	    string builtExpression = default(string);


	    string lhs = default(string);
	    string op = default(string);
	    string rhs = default(string);

		try { DebugEnterRule(GrammarFileName, "mulexpr");
		DebugLocation(35, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:36:2: (lhs= powexpr (op= mulop rhs= powexpr )* )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:36:4: lhs= powexpr (op= mulop rhs= powexpr )*
			{
			DebugLocation(36, 7);
			PushFollow(Follow._powexpr_in_mulexpr229);
			lhs=powexpr();
			PopFollow();

			DebugLocation(36, 16);
			 builtExpression = lhs; 
			DebugLocation(37, 3);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:37:3: (op= mulop rhs= powexpr )*
			try { DebugEnterSubRule(7);
			while (true)
			{
				int alt7=2;
				try { DebugEnterDecision(7, decisionCanBacktrack[7]);
				int LA7_1 = input.LA(1);

				if ((LA7_1==BACKSLASH||LA7_1==MOD||(LA7_1>=SLASH && LA7_1<=STAR)))
				{
					alt7 = 1;
				}


				} finally { DebugExitDecision(7); }
				switch ( alt7 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:37:4: op= mulop rhs= powexpr
					{
					DebugLocation(37, 6);
					PushFollow(Follow._mulop_in_mulexpr238);
					op=mulop();
					PopFollow();

					DebugLocation(37, 16);
					PushFollow(Follow._powexpr_in_mulexpr242);
					rhs=powexpr();
					PopFollow();

					DebugLocation(37, 25);
					 if ("idiv".Equals(op)) builtExpression = "SDMath.Idiv(" + builtExpression + ", " + rhs + ")"; else builtExpression = "(" + builtExpression + " " + op + " " + rhs + ")"; 

					}
					break;

				default:
					goto loop7;
				}
			}

			loop7:
				;

			} finally { DebugExitSubRule(7); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("mulexpr", 7);
			LeaveRule("mulexpr", 7);
			LeaveRule_mulexpr();
	    }
	 	DebugLocation(38, 1);
		} finally { DebugExitRule(GrammarFileName, "mulexpr"); }
		return builtExpression;

	}
	// $ANTLR end "mulexpr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_powexpr() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_powexpr() {}
	// $ANTLR start "powexpr"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:40:1: powexpr returns [string builtExpression] : lhs= factorial ( ( CARET | STARSTAR ) rhs= factorial )* ;
	[GrammarRule("powexpr")]
	private string powexpr()
	{
		EnterRule_powexpr();
		EnterRule("powexpr", 8);
		TraceIn("powexpr", 8);
	    string builtExpression = default(string);


	    string lhs = default(string);
	    string rhs = default(string);

		try { DebugEnterRule(GrammarFileName, "powexpr");
		DebugLocation(40, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:41:2: (lhs= factorial ( ( CARET | STARSTAR ) rhs= factorial )* )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:41:4: lhs= factorial ( ( CARET | STARSTAR ) rhs= factorial )*
			{
			DebugLocation(41, 7);
			PushFollow(Follow._factorial_in_powexpr264);
			lhs=factorial();
			PopFollow();

			DebugLocation(41, 18);
			 builtExpression = lhs; 
			DebugLocation(42, 3);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:42:3: ( ( CARET | STARSTAR ) rhs= factorial )*
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, decisionCanBacktrack[8]);
				int LA8_1 = input.LA(1);

				if ((LA8_1==CARET||LA8_1==STARSTAR))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch ( alt8 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:42:4: ( CARET | STARSTAR ) rhs= factorial
					{
					DebugLocation(42, 4);
					if (input.LA(1)==CARET||input.LA(1)==STARSTAR)
					{
						input.Consume();
						state.errorRecovery=false;
					}
					else
					{
						MismatchedSetException mse = new MismatchedSetException(null,input);
						DebugRecognitionException(mse);
						throw mse;
					}

					DebugLocation(42, 26);
					PushFollow(Follow._factorial_in_powexpr281);
					rhs=factorial();
					PopFollow();

					DebugLocation(42, 37);
					 builtExpression = "Math.Pow(" + builtExpression + ", " + rhs + ")"; 

					}
					break;

				default:
					goto loop8;
				}
			}

			loop8:
				;

			} finally { DebugExitSubRule(8); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("powexpr", 8);
			LeaveRule("powexpr", 8);
			LeaveRule_powexpr();
	    }
	 	DebugLocation(43, 1);
		} finally { DebugExitRule(GrammarFileName, "powexpr"); }
		return builtExpression;

	}
	// $ANTLR end "powexpr"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_factorial() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_factorial() {}
	// $ANTLR start "factorial"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:45:1: factorial returns [string builtExpression] : term ( EXCLAIM )? ;
	[GrammarRule("factorial")]
	private string factorial()
	{
		EnterRule_factorial();
		EnterRule("factorial", 9);
		TraceIn("factorial", 9);
	    string builtExpression = default(string);


	    string term3 = default(string);

		try { DebugEnterRule(GrammarFileName, "factorial");
		DebugLocation(45, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:46:2: ( term ( EXCLAIM )? )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:46:4: term ( EXCLAIM )?
			{
			DebugLocation(46, 4);
			PushFollow(Follow._term_in_factorial302);
			term3=term();
			PopFollow();

			DebugLocation(46, 9);
			 builtExpression = term3; 
			DebugLocation(47, 2);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:47:2: ( EXCLAIM )?
			int alt9=2;
			try { DebugEnterSubRule(9);
			try { DebugEnterDecision(9, decisionCanBacktrack[9]);
			int LA9_1 = input.LA(1);

			if ((LA9_1==EXCLAIM))
			{
				alt9 = 1;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:47:3: EXCLAIM
				{
				DebugLocation(47, 3);
				Match(input,EXCLAIM,Follow._EXCLAIM_in_factorial308); 
				DebugLocation(47, 11);
				 builtExpression = "SDMath.Factorial(" + term3 + ")"; 

				}
				break;

			}
			} finally { DebugExitSubRule(9); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("factorial", 9);
			LeaveRule("factorial", 9);
			LeaveRule_factorial();
	    }
	 	DebugLocation(48, 1);
		} finally { DebugExitRule(GrammarFileName, "factorial"); }
		return builtExpression;

	}
	// $ANTLR end "factorial"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_term() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_term() {}
	// $ANTLR start "term"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:50:1: term returns [string builtExpression] : ( INTEGER | MINUS INTEGER | FLOAT | MINUS FLOAT | LPAREN expr RPAREN | constant | function | IDENTIFIER );
	[GrammarRule("term")]
	private string term()
	{
		EnterRule_term();
		EnterRule("term", 10);
		TraceIn("term", 10);
	    string builtExpression = default(string);


	    IToken INTEGER4 = default(IToken);
	    IToken INTEGER5 = default(IToken);
	    IToken FLOAT6 = default(IToken);
	    IToken FLOAT7 = default(IToken);
	    IToken IDENTIFIER11 = default(IToken);
	    string expr8 = default(string);
	    string constant9 = default(string);
	    string function10 = default(string);

		try { DebugEnterRule(GrammarFileName, "term");
		DebugLocation(50, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:51:2: ( INTEGER | MINUS INTEGER | FLOAT | MINUS FLOAT | LPAREN expr RPAREN | constant | function | IDENTIFIER )
			int alt10=8;
			try { DebugEnterDecision(10, decisionCanBacktrack[10]);
			switch (input.LA(1))
			{
			case INTEGER:
				{
				alt10 = 1;
				}
				break;
			case MINUS:
				{
				int LA10_2 = input.LA(2);

				if ((LA10_2==INTEGER))
				{
					alt10 = 2;
				}
				else if ((LA10_2==FLOAT))
				{
					alt10 = 4;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 10, 2, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case FLOAT:
				{
				alt10 = 3;
				}
				break;
			case LPAREN:
				{
				alt10 = 5;
				}
				break;
			case EE:
			case FALSE:
			case LR:
			case PI:
			case TRUE:
				{
				alt10 = 6;
				}
				break;
			case IDENTIFIER:
				{
				int LA10_2 = input.LA(2);

				if ((LA10_2==LPAREN))
				{
					alt10 = 7;
				}
				else if ((LA10_2==EOF||LA10_2==AND||LA10_2==BACKSLASH||(LA10_2>=CARET && LA10_2<=COMMA)||(LA10_2>=EQ && LA10_2<=EXCLAIM)||LA10_2==GE||LA10_2==GT||LA10_2==LE||LA10_2==LT||(LA10_2>=MINUS && LA10_2<=MOD)||LA10_2==NE||LA10_2==OR||LA10_2==PLUS||LA10_2==RPAREN||(LA10_2>=SLASH && LA10_2<=STARSTAR)))
				{
					alt10 = 8;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 10, 6, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 10, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:51:4: INTEGER
				{
				DebugLocation(51, 4);
				INTEGER4=(IToken)Match(input,INTEGER,Follow._INTEGER_in_term328); 
				DebugLocation(51, 12);
				 builtExpression = "((double)" + (INTEGER4!=null?INTEGER4.Text:null) + ")"; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:52:4: MINUS INTEGER
				{
				DebugLocation(52, 4);
				Match(input,MINUS,Follow._MINUS_in_term335); 
				DebugLocation(52, 10);
				INTEGER5=(IToken)Match(input,INTEGER,Follow._INTEGER_in_term337); 
				DebugLocation(52, 18);
				 builtExpression = "((double)-" + (INTEGER5!=null?INTEGER5.Text:null) + ")"; 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:53:4: FLOAT
				{
				DebugLocation(53, 4);
				FLOAT6=(IToken)Match(input,FLOAT,Follow._FLOAT_in_term344); 
				DebugLocation(53, 10);
				 builtExpression = double.Parse((FLOAT6!=null?FLOAT6.Text:null).Replace("d","e").Replace("D","E")).ToString(); 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:54:4: MINUS FLOAT
				{
				DebugLocation(54, 4);
				Match(input,MINUS,Follow._MINUS_in_term351); 
				DebugLocation(54, 10);
				FLOAT7=(IToken)Match(input,FLOAT,Follow._FLOAT_in_term353); 
				DebugLocation(54, 16);
				 builtExpression = "-" + double.Parse((FLOAT7!=null?FLOAT7.Text:null).Replace("d","e").Replace("D","E")).ToString(); 

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:55:4: LPAREN expr RPAREN
				{
				DebugLocation(55, 4);
				Match(input,LPAREN,Follow._LPAREN_in_term360); 
				DebugLocation(55, 11);
				PushFollow(Follow._expr_in_term362);
				expr8=expr();
				PopFollow();

				DebugLocation(55, 16);
				Match(input,RPAREN,Follow._RPAREN_in_term364); 
				DebugLocation(55, 23);
				 builtExpression = "(" + expr8 + ")"; 

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:56:4: constant
				{
				DebugLocation(56, 4);
				PushFollow(Follow._constant_in_term371);
				constant9=constant();
				PopFollow();

				DebugLocation(56, 13);
				 builtExpression = constant9; 

				}
				break;
			case 7:
				DebugEnterAlt(7);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:57:4: function
				{
				DebugLocation(57, 4);
				PushFollow(Follow._function_in_term378);
				function10=function();
				PopFollow();

				DebugLocation(57, 13);
				 builtExpression = function10; 

				}
				break;
			case 8:
				DebugEnterAlt(8);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:58:4: IDENTIFIER
				{
				DebugLocation(58, 4);
				IDENTIFIER11=(IToken)Match(input,IDENTIFIER,Follow._IDENTIFIER_in_term385); 
				DebugLocation(58, 15);
				 builtExpression = RenderVariable((IDENTIFIER11!=null?IDENTIFIER11.Text:null)); 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("term", 10);
			LeaveRule("term", 10);
			LeaveRule_term();
	    }
	 	DebugLocation(59, 1);
		} finally { DebugExitRule(GrammarFileName, "term"); }
		return builtExpression;

	}
	// $ANTLR end "term"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_function() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_function() {}
	// $ANTLR start "function"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:61:1: function returns [string builtExpression] : IDENTIFIER LPAREN argumentlist RPAREN ;
	[GrammarRule("function")]
	private string function()
	{
		EnterRule_function();
		EnterRule("function", 11);
		TraceIn("function", 11);
	    string builtExpression = default(string);


	    IToken IDENTIFIER12 = default(IToken);
	    Arguments argumentlist13 = default(Arguments);

		try { DebugEnterRule(GrammarFileName, "function");
		DebugLocation(61, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:62:2: ( IDENTIFIER LPAREN argumentlist RPAREN )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:62:4: IDENTIFIER LPAREN argumentlist RPAREN
			{
			DebugLocation(62, 4);
			IDENTIFIER12=(IToken)Match(input,IDENTIFIER,Follow._IDENTIFIER_in_function403); 
			DebugLocation(62, 15);
			Match(input,LPAREN,Follow._LPAREN_in_function405); 
			DebugLocation(62, 22);
			PushFollow(Follow._argumentlist_in_function407);
			argumentlist13=argumentlist();
			PopFollow();

			DebugLocation(62, 35);
			Match(input,RPAREN,Follow._RPAREN_in_function409); 
			DebugLocation(62, 42);
			 builtExpression = RenderFunction((IDENTIFIER12!=null?IDENTIFIER12.Text:null).ToUpper(), argumentlist13); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("function", 11);
			LeaveRule("function", 11);
			LeaveRule_function();
	    }
	 	DebugLocation(63, 1);
		} finally { DebugExitRule(GrammarFileName, "function"); }
		return builtExpression;

	}
	// $ANTLR end "function"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_argumentlist() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_argumentlist() {}
	// $ANTLR start "argumentlist"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:65:1: argumentlist returns [Arguments arguments] : lhs= argument ( COMMA rhs= argument )* ;
	[GrammarRule("argumentlist")]
	private Arguments argumentlist()
	{
		EnterRule_argumentlist();
		EnterRule("argumentlist", 12);
		TraceIn("argumentlist", 12);
	    Arguments arguments = default(Arguments);


	    Argument lhs = default(Argument);
	    Argument rhs = default(Argument);

		try { DebugEnterRule(GrammarFileName, "argumentlist");
		DebugLocation(65, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:66:2: (lhs= argument ( COMMA rhs= argument )* )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:66:4: lhs= argument ( COMMA rhs= argument )*
			{
			DebugLocation(66, 7);
			PushFollow(Follow._argument_in_argumentlist429);
			lhs=argument();
			PopFollow();

			DebugLocation(66, 17);
			 arguments = new Arguments(); if (null != lhs) arguments.Add(lhs); 
			DebugLocation(67, 2);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:67:2: ( COMMA rhs= argument )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=2;
				try { DebugEnterDecision(11, decisionCanBacktrack[11]);
				int LA11_1 = input.LA(1);

				if ((LA11_1==COMMA))
				{
					alt11 = 1;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:67:4: COMMA rhs= argument
					{
					DebugLocation(67, 4);
					Match(input,COMMA,Follow._COMMA_in_argumentlist436); 
					DebugLocation(67, 13);
					PushFollow(Follow._argument_in_argumentlist440);
					rhs=argument();
					PopFollow();

					DebugLocation(67, 23);
					 arguments.Add(rhs); 

					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("argumentlist", 12);
			LeaveRule("argumentlist", 12);
			LeaveRule_argumentlist();
	    }
	 	DebugLocation(68, 1);
		} finally { DebugExitRule(GrammarFileName, "argumentlist"); }
		return arguments;

	}
	// $ANTLR end "argumentlist"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_argument() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_argument() {}
	// $ANTLR start "argument"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:70:1: argument returns [Argument argument] : ( expr | explicitParameterName GETS expr |);
	[GrammarRule("argument")]
	private Argument argument()
	{
		EnterRule_argument();
		EnterRule("argument", 13);
		TraceIn("argument", 13);
	    Argument argument = default(Argument);


	    string expr14 = default(string);
	    ParserRuleReturnScope<IToken> explicitParameterName15 = default(ParserRuleReturnScope<IToken>);
	    string expr16 = default(string);

		try { DebugEnterRule(GrammarFileName, "argument");
		DebugLocation(70, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:71:2: ( expr | explicitParameterName GETS expr |)
			int alt12=3;
			try { DebugEnterDecision(12, decisionCanBacktrack[12]);
			switch (input.LA(1))
			{
			case EE:
			case FALSE:
			case FLOAT:
			case INTEGER:
			case LPAREN:
			case LR:
			case MINUS:
			case NOT:
			case PI:
			case TRUE:
				{
				alt12 = 1;
				}
				break;
			case IDENTIFIER:
				{
				int LA12_2 = input.LA(2);

				if ((LA12_2==AND||LA12_2==BACKSLASH||(LA12_2>=CARET && LA12_2<=COMMA)||(LA12_2>=EQ && LA12_2<=EXCLAIM)||LA12_2==GE||LA12_2==GT||(LA12_2>=LE && LA12_2<=LPAREN)||LA12_2==LT||(LA12_2>=MINUS && LA12_2<=MOD)||LA12_2==NE||LA12_2==OR||LA12_2==PLUS||LA12_2==RPAREN||(LA12_2>=SLASH && LA12_2<=STARSTAR)))
				{
					alt12 = 1;
				}
				else if ((LA12_2==GETS))
				{
					alt12 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 12, 2, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case COMMA:
			case RPAREN:
				{
				alt12 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 12, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(12); }
			switch (alt12)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:71:4: expr
				{
				DebugLocation(71, 4);
				PushFollow(Follow._expr_in_argument461);
				expr14=expr();
				PopFollow();

				DebugLocation(71, 9);
				 argument = new Argument(expr14); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:72:4: explicitParameterName GETS expr
				{
				DebugLocation(72, 4);
				PushFollow(Follow._explicitParameterName_in_argument468);
				explicitParameterName15=explicitParameterName();
				PopFollow();

				DebugLocation(72, 26);
				Match(input,GETS,Follow._GETS_in_argument470); 
				DebugLocation(72, 31);
				PushFollow(Follow._expr_in_argument472);
				expr16=expr();
				PopFollow();

				DebugLocation(72, 36);
				 argument = new Argument((explicitParameterName15!=null?input.ToString(explicitParameterName15.Start,explicitParameterName15.Stop):null), expr16); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:73:4: 
				{
				DebugLocation(73, 4);
				 argument = null; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("argument", 13);
			LeaveRule("argument", 13);
			LeaveRule_argument();
	    }
	 	DebugLocation(74, 1);
		} finally { DebugExitRule(GrammarFileName, "argument"); }
		return argument;

	}
	// $ANTLR end "argument"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_constant() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_constant() {}
	// $ANTLR start "constant"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:76:1: constant returns [string builtExpression] : ( PI | EE | FALSE | LR | TRUE );
	[GrammarRule("constant")]
	private string constant()
	{
		EnterRule_constant();
		EnterRule("constant", 14);
		TraceIn("constant", 14);
	    string builtExpression = default(string);


		try { DebugEnterRule(GrammarFileName, "constant");
		DebugLocation(76, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:77:2: ( PI | EE | FALSE | LR | TRUE )
			int alt13=5;
			try { DebugEnterDecision(13, decisionCanBacktrack[13]);
			switch (input.LA(1))
			{
			case PI:
				{
				alt13 = 1;
				}
				break;
			case EE:
				{
				alt13 = 2;
				}
				break;
			case FALSE:
				{
				alt13 = 3;
				}
				break;
			case LR:
				{
				alt13 = 4;
				}
				break;
			case TRUE:
				{
				alt13 = 5;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:77:4: PI
				{
				DebugLocation(77, 4);
				Match(input,PI,Follow._PI_in_constant495); 
				DebugLocation(77, 7);
				 builtExpression = "Math.PI"; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:78:4: EE
				{
				DebugLocation(78, 4);
				Match(input,EE,Follow._EE_in_constant502); 
				DebugLocation(78, 7);
				 builtExpression = "Math.E"; 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:79:4: FALSE
				{
				DebugLocation(79, 4);
				Match(input,FALSE,Follow._FALSE_in_constant509); 
				DebugLocation(79, 10);
				 builtExpression = "false"; 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:80:4: LR
				{
				DebugLocation(80, 4);
				Match(input,LR,Follow._LR_in_constant516); 
				DebugLocation(80, 7);
				 throw new System.NotImplementedException(); 

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:81:4: TRUE
				{
				DebugLocation(81, 4);
				Match(input,TRUE,Follow._TRUE_in_constant523); 
				DebugLocation(81, 9);
				 builtExpression = "true"; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("constant", 14);
			LeaveRule("constant", 14);
			LeaveRule_constant();
	    }
	 	DebugLocation(82, 1);
		} finally { DebugExitRule(GrammarFileName, "constant"); }
		return builtExpression;

	}
	// $ANTLR end "constant"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_relop() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_relop() {}
	// $ANTLR start "relop"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:84:1: relop returns [string builtExpression] : ( NE | LE | LT | GE | GT | EQ );
	[GrammarRule("relop")]
	private string relop()
	{
		EnterRule_relop();
		EnterRule("relop", 15);
		TraceIn("relop", 15);
	    string builtExpression = default(string);


		try { DebugEnterRule(GrammarFileName, "relop");
		DebugLocation(84, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:85:2: ( NE | LE | LT | GE | GT | EQ )
			int alt14=6;
			try { DebugEnterDecision(14, decisionCanBacktrack[14]);
			switch (input.LA(1))
			{
			case NE:
				{
				alt14 = 1;
				}
				break;
			case LE:
				{
				alt14 = 2;
				}
				break;
			case LT:
				{
				alt14 = 3;
				}
				break;
			case GE:
				{
				alt14 = 4;
				}
				break;
			case GT:
				{
				alt14 = 5;
				}
				break;
			case EQ:
				{
				alt14 = 6;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 14, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:85:4: NE
				{
				DebugLocation(85, 4);
				Match(input,NE,Follow._NE_in_relop541); 
				DebugLocation(85, 7);
				 builtExpression = "!="; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:86:4: LE
				{
				DebugLocation(86, 4);
				Match(input,LE,Follow._LE_in_relop548); 
				DebugLocation(86, 7);
				 builtExpression = "<="; 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:87:4: LT
				{
				DebugLocation(87, 4);
				Match(input,LT,Follow._LT_in_relop555); 
				DebugLocation(87, 7);
				 builtExpression = "<"; 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:88:4: GE
				{
				DebugLocation(88, 4);
				Match(input,GE,Follow._GE_in_relop562); 
				DebugLocation(88, 7);
				 builtExpression = ">="; 

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:89:4: GT
				{
				DebugLocation(89, 4);
				Match(input,GT,Follow._GT_in_relop569); 
				DebugLocation(89, 7);
				 builtExpression = ">"; 

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:90:4: EQ
				{
				DebugLocation(90, 4);
				Match(input,EQ,Follow._EQ_in_relop576); 
				DebugLocation(90, 7);
				 builtExpression = "=="; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("relop", 15);
			LeaveRule("relop", 15);
			LeaveRule_relop();
	    }
	 	DebugLocation(91, 1);
		} finally { DebugExitRule(GrammarFileName, "relop"); }
		return builtExpression;

	}
	// $ANTLR end "relop"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_addop() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_addop() {}
	// $ANTLR start "addop"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:93:1: addop returns [string builtExpression] : ( PLUS | MINUS );
	[GrammarRule("addop")]
	private string addop()
	{
		EnterRule_addop();
		EnterRule("addop", 16);
		TraceIn("addop", 16);
	    string builtExpression = default(string);


		try { DebugEnterRule(GrammarFileName, "addop");
		DebugLocation(93, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:94:2: ( PLUS | MINUS )
			int alt15=2;
			try { DebugEnterDecision(15, decisionCanBacktrack[15]);
			int LA15_1 = input.LA(1);

			if ((LA15_1==PLUS))
			{
				alt15 = 1;
			}
			else if ((LA15_1==MINUS))
			{
				alt15 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 15, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:94:4: PLUS
				{
				DebugLocation(94, 4);
				Match(input,PLUS,Follow._PLUS_in_addop593); 
				DebugLocation(94, 9);
				 builtExpression = "+"; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:95:4: MINUS
				{
				DebugLocation(95, 4);
				Match(input,MINUS,Follow._MINUS_in_addop600); 
				DebugLocation(95, 10);
				 builtExpression = "-"; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("addop", 16);
			LeaveRule("addop", 16);
			LeaveRule_addop();
	    }
	 	DebugLocation(96, 1);
		} finally { DebugExitRule(GrammarFileName, "addop"); }
		return builtExpression;

	}
	// $ANTLR end "addop"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_mulop() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_mulop() {}
	// $ANTLR start "mulop"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:98:1: mulop returns [string builtExpression] : ( STAR | SLASH | BACKSLASH | MOD );
	[GrammarRule("mulop")]
	private string mulop()
	{
		EnterRule_mulop();
		EnterRule("mulop", 17);
		TraceIn("mulop", 17);
	    string builtExpression = default(string);


		try { DebugEnterRule(GrammarFileName, "mulop");
		DebugLocation(98, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:99:2: ( STAR | SLASH | BACKSLASH | MOD )
			int alt16=4;
			try { DebugEnterDecision(16, decisionCanBacktrack[16]);
			switch (input.LA(1))
			{
			case STAR:
				{
				alt16 = 1;
				}
				break;
			case SLASH:
				{
				alt16 = 2;
				}
				break;
			case BACKSLASH:
				{
				alt16 = 3;
				}
				break;
			case MOD:
				{
				alt16 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 16, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:99:4: STAR
				{
				DebugLocation(99, 4);
				Match(input,STAR,Follow._STAR_in_mulop618); 
				DebugLocation(99, 9);
				 builtExpression = "*"; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:100:4: SLASH
				{
				DebugLocation(100, 4);
				Match(input,SLASH,Follow._SLASH_in_mulop625); 
				DebugLocation(100, 10);
				 builtExpression = "/"; 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:101:4: BACKSLASH
				{
				DebugLocation(101, 4);
				Match(input,BACKSLASH,Follow._BACKSLASH_in_mulop632); 
				DebugLocation(101, 14);
				 builtExpression = "idiv"; 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:102:4: MOD
				{
				DebugLocation(102, 4);
				Match(input,MOD,Follow._MOD_in_mulop639); 
				DebugLocation(102, 8);
				 builtExpression = "%"; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("mulop", 17);
			LeaveRule("mulop", 17);
			LeaveRule_mulop();
	    }
	 	DebugLocation(103, 1);
		} finally { DebugExitRule(GrammarFileName, "mulop"); }
		return builtExpression;

	}
	// $ANTLR end "mulop"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_explicitParameterName() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_explicitParameterName() {}
	// $ANTLR start "explicitParameterName"
	// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:105:1: explicitParameterName : IDENTIFIER ;
	[GrammarRule("explicitParameterName")]
	private ParserRuleReturnScope<IToken> explicitParameterName()
	{
		EnterRule_explicitParameterName();
		EnterRule("explicitParameterName", 18);
		TraceIn("explicitParameterName", 18);
	    ParserRuleReturnScope<IToken> retval = new ParserRuleReturnScope<IToken>();
	    retval.Start = (IToken)input.LT(1);

		try { DebugEnterRule(GrammarFileName, "explicitParameterName");
		DebugLocation(105, 1);
		try
		{
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:106:2: ( IDENTIFIER )
			DebugEnterAlt(1);
			// C:\\Sandbox\\StatsDirect\\shell\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:106:4: IDENTIFIER
			{
			DebugLocation(106, 4);
			Match(input,IDENTIFIER,Follow._IDENTIFIER_in_explicitParameterName652); 

			}

			retval.Stop = (IToken)input.LT(-1);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("explicitParameterName", 18);
			LeaveRule("explicitParameterName", 18);
			LeaveRule_explicitParameterName();
	    }
	 	DebugLocation(107, 1);
		} finally { DebugExitRule(GrammarFileName, "explicitParameterName"); }
		return retval;

	}
	// $ANTLR end "explicitParameterName"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _EQ_in_start32 = new BitSet(new ulong[]{0x8011130C0C2000UL});
		public static readonly BitSet _expr_in_start35 = new BitSet(new ulong[]{0x0UL});
		public static readonly BitSet _EOF_in_start37 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _andexpr_in_expr56 = new BitSet(new ulong[]{0x40000000002UL});
		public static readonly BitSet _OR_in_expr65 = new BitSet(new ulong[]{0x8011130C0C2000UL});
		public static readonly BitSet _andexpr_in_expr69 = new BitSet(new ulong[]{0x40000000002UL});
		public static readonly BitSet _notexpr_in_andexpr91 = new BitSet(new ulong[]{0x22UL});
		public static readonly BitSet _AND_in_andexpr100 = new BitSet(new ulong[]{0x8011130C0C2000UL});
		public static readonly BitSet _notexpr_in_andexpr104 = new BitSet(new ulong[]{0x22UL});
		public static readonly BitSet _NOT_in_notexpr126 = new BitSet(new ulong[]{0x8010130C0C2000UL});
		public static readonly BitSet _relexpr_in_notexpr130 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _relexpr_in_notexpr139 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _numexpr_in_relexpr158 = new BitSet(new ulong[]{0x8480A04002UL});
		public static readonly BitSet _relop_in_relexpr167 = new BitSet(new ulong[]{0x8010130C0C2000UL});
		public static readonly BitSet _numexpr_in_relexpr171 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _mulexpr_in_numexpr193 = new BitSet(new ulong[]{0x201000000002UL});
		public static readonly BitSet _addop_in_numexpr202 = new BitSet(new ulong[]{0x8010130C0C2000UL});
		public static readonly BitSet _mulexpr_in_numexpr206 = new BitSet(new ulong[]{0x201000000002UL});
		public static readonly BitSet _powexpr_in_mulexpr229 = new BitSet(new ulong[]{0xC002000000082UL});
		public static readonly BitSet _mulop_in_mulexpr238 = new BitSet(new ulong[]{0x8010130C0C2000UL});
		public static readonly BitSet _powexpr_in_mulexpr242 = new BitSet(new ulong[]{0xC002000000082UL});
		public static readonly BitSet _factorial_in_powexpr264 = new BitSet(new ulong[]{0x10000000000202UL});
		public static readonly BitSet _set_in_powexpr271 = new BitSet(new ulong[]{0x8010130C0C2000UL});
		public static readonly BitSet _factorial_in_powexpr281 = new BitSet(new ulong[]{0x10000000000202UL});
		public static readonly BitSet _term_in_factorial302 = new BitSet(new ulong[]{0x8002UL});
		public static readonly BitSet _EXCLAIM_in_factorial308 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _INTEGER_in_term328 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _MINUS_in_term335 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _INTEGER_in_term337 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _FLOAT_in_term344 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _MINUS_in_term351 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _FLOAT_in_term353 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _LPAREN_in_term360 = new BitSet(new ulong[]{0x8011130C0C2000UL});
		public static readonly BitSet _expr_in_term362 = new BitSet(new ulong[]{0x1000000000000UL});
		public static readonly BitSet _RPAREN_in_term364 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _constant_in_term371 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _function_in_term378 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IDENTIFIER_in_term385 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IDENTIFIER_in_function403 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _LPAREN_in_function405 = new BitSet(new ulong[]{0x8011130C0C2400UL});
		public static readonly BitSet _argumentlist_in_function407 = new BitSet(new ulong[]{0x1000000000000UL});
		public static readonly BitSet _RPAREN_in_function409 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _argument_in_argumentlist429 = new BitSet(new ulong[]{0x402UL});
		public static readonly BitSet _COMMA_in_argumentlist436 = new BitSet(new ulong[]{0x8011130C0C2400UL});
		public static readonly BitSet _argument_in_argumentlist440 = new BitSet(new ulong[]{0x402UL});
		public static readonly BitSet _expr_in_argument461 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _explicitParameterName_in_argument468 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _GETS_in_argument470 = new BitSet(new ulong[]{0x8011130C0C2000UL});
		public static readonly BitSet _expr_in_argument472 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PI_in_constant495 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _EE_in_constant502 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _FALSE_in_constant509 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _LR_in_constant516 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _TRUE_in_constant523 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _NE_in_relop541 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _LE_in_relop548 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _LT_in_relop555 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _GE_in_relop562 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _GT_in_relop569 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _EQ_in_relop576 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PLUS_in_addop593 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _MINUS_in_addop600 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _STAR_in_mulop618 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _SLASH_in_mulop625 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _BACKSLASH_in_mulop632 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _MOD_in_mulop639 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IDENTIFIER_in_explicitParameterName652 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  StatsDirect.Expressions 
