//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4.1.9004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4.1.9004 C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g 2012-04-12 08:28:25

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4.1.9004")]
[System.CLSCompliant(false)]
public partial class StatsDirectExpressionLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int A=4;
	public const int AND=5;
	public const int B=6;
	public const int BACKSLASH=7;
	public const int C=8;
	public const int CARET=9;
	public const int COMMA=10;
	public const int D=11;
	public const int E=12;
	public const int EE=13;
	public const int EQ=14;
	public const int EXCLAIM=15;
	public const int EXPONENT=16;
	public const int F=17;
	public const int FALSE=18;
	public const int FLOAT=19;
	public const int G=20;
	public const int GE=21;
	public const int GETS=22;
	public const int GT=23;
	public const int H=24;
	public const int I=25;
	public const int IDENTIFIER=26;
	public const int INTEGER=27;
	public const int J=28;
	public const int K=29;
	public const int L=30;
	public const int LE=31;
	public const int LPAREN=32;
	public const int LR=33;
	public const int LT=34;
	public const int M=35;
	public const int MINUS=36;
	public const int MOD=37;
	public const int N=38;
	public const int NE=39;
	public const int NOT=40;
	public const int O=41;
	public const int OR=42;
	public const int P=43;
	public const int PI=44;
	public const int PLUS=45;
	public const int Q=46;
	public const int R=47;
	public const int RPAREN=48;
	public const int S=49;
	public const int SLASH=50;
	public const int STAR=51;
	public const int STARSTAR=52;
	public const int STRING=53;
	public const int T=54;
	public const int TRUE=55;
	public const int U=56;
	public const int V=57;
	public const int W=58;
	public const int WS=59;
	public const int X=60;
	public const int Y=61;
	public const int Z=62;

    // delegates
    // delegators

	public StatsDirectExpressionLexer()
	{
		OnCreated();
	}

	public StatsDirectExpressionLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public StatsDirectExpressionLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g"; } }

	private static readonly bool[] decisionCanBacktrack = new bool[0];

	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_INTEGER() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_INTEGER() {}

    // $ANTLR start "INTEGER"
    [GrammarRule("INTEGER")]
    private void mINTEGER()
    {
    	EnterRule_INTEGER();
    	EnterRule("INTEGER", 1);
    	TraceIn("INTEGER", 1);
    		try
    		{
    		int _type = INTEGER;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:111:9: ( ( '0' .. '9' )+ )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:111:11: ( '0' .. '9' )+
    		{
    		DebugLocation(111, 11);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:111:11: ( '0' .. '9' )+
    		int cnt1=0;
    		try { DebugEnterSubRule(1);
    		while (true)
    		{
    			int alt1=2;
    			try { DebugEnterDecision(1, decisionCanBacktrack[1]);
    			int LA1_1 = input.LA(1);

    			if (((LA1_1>='0' && LA1_1<='9')))
    			{
    				alt1 = 1;
    			}


    			} finally { DebugExitDecision(1); }
    			switch (alt1)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    				{
    				DebugLocation(111, 11);
    				input.Consume();


    				}
    				break;

    			default:
    				if (cnt1 >= 1)
    					goto loop1;

    				EarlyExitException eee1 = new EarlyExitException( 1, input );
    				DebugRecognitionException(eee1);
    				throw eee1;
    			}
    			cnt1++;
    		}
    		loop1:
    			;

    		} finally { DebugExitSubRule(1); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("INTEGER", 1);
    		LeaveRule("INTEGER", 1);
    		LeaveRule_INTEGER();
        }
    }
    // $ANTLR end "INTEGER"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_FLOAT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_FLOAT() {}

    // $ANTLR start "FLOAT"
    [GrammarRule("FLOAT")]
    private void mFLOAT()
    {
    	EnterRule_FLOAT();
    	EnterRule("FLOAT", 2);
    	TraceIn("FLOAT", 2);
    		try
    		{
    		int _type = FLOAT;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:115:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
    		int alt8=3;
    		try { DebugEnterDecision(8, decisionCanBacktrack[8]);
    		try
    		{
    			alt8 = dfa8.Predict(input);
    		}
    		catch (NoViableAltException nvae)
    		{
    			DebugRecognitionException(nvae);
    			throw;
    		}
    		} finally { DebugExitDecision(8); }
    		switch (alt8)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:115:9: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
    			{
    			DebugLocation(115, 9);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:115:9: ( '0' .. '9' )+
    			int cnt2=0;
    			try { DebugEnterSubRule(2);
    			while (true)
    			{
    				int alt2=2;
    				try { DebugEnterDecision(2, decisionCanBacktrack[2]);
    				int LA2_1 = input.LA(1);

    				if (((LA2_1>='0' && LA2_1<='9')))
    				{
    					alt2 = 1;
    				}


    				} finally { DebugExitDecision(2); }
    				switch (alt2)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    					{
    					DebugLocation(115, 9);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt2 >= 1)
    						goto loop2;

    					EarlyExitException eee2 = new EarlyExitException( 2, input );
    					DebugRecognitionException(eee2);
    					throw eee2;
    				}
    				cnt2++;
    			}
    			loop2:
    				;

    			} finally { DebugExitSubRule(2); }

    			DebugLocation(115, 21);
    			Match('.'); 
    			DebugLocation(115, 25);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:115:25: ( '0' .. '9' )*
    			try { DebugEnterSubRule(3);
    			while (true)
    			{
    				int alt3=2;
    				try { DebugEnterDecision(3, decisionCanBacktrack[3]);
    				int LA3_1 = input.LA(1);

    				if (((LA3_1>='0' && LA3_1<='9')))
    				{
    					alt3 = 1;
    				}


    				} finally { DebugExitDecision(3); }
    				switch ( alt3 )
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    					{
    					DebugLocation(115, 25);
    					input.Consume();


    					}
    					break;

    				default:
    					goto loop3;
    				}
    			}

    			loop3:
    				;

    			} finally { DebugExitSubRule(3); }

    			DebugLocation(115, 37);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:115:37: ( EXPONENT )?
    			int alt4=2;
    			try { DebugEnterSubRule(4);
    			try { DebugEnterDecision(4, decisionCanBacktrack[4]);
    			int LA4_1 = input.LA(1);

    			if (((LA4_1>='D' && LA4_1<='E')||(LA4_1>='d' && LA4_1<='e')))
    			{
    				alt4 = 1;
    			}
    			} finally { DebugExitDecision(4); }
    			switch (alt4)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:115:37: EXPONENT
    				{
    				DebugLocation(115, 37);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(4); }


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:116:9: '.' ( '0' .. '9' )+ ( EXPONENT )?
    			{
    			DebugLocation(116, 9);
    			Match('.'); 
    			DebugLocation(116, 13);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:116:13: ( '0' .. '9' )+
    			int cnt5=0;
    			try { DebugEnterSubRule(5);
    			while (true)
    			{
    				int alt5=2;
    				try { DebugEnterDecision(5, decisionCanBacktrack[5]);
    				int LA5_1 = input.LA(1);

    				if (((LA5_1>='0' && LA5_1<='9')))
    				{
    					alt5 = 1;
    				}


    				} finally { DebugExitDecision(5); }
    				switch (alt5)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    					{
    					DebugLocation(116, 13);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt5 >= 1)
    						goto loop5;

    					EarlyExitException eee5 = new EarlyExitException( 5, input );
    					DebugRecognitionException(eee5);
    					throw eee5;
    				}
    				cnt5++;
    			}
    			loop5:
    				;

    			} finally { DebugExitSubRule(5); }

    			DebugLocation(116, 25);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:116:25: ( EXPONENT )?
    			int alt6=2;
    			try { DebugEnterSubRule(6);
    			try { DebugEnterDecision(6, decisionCanBacktrack[6]);
    			int LA6_1 = input.LA(1);

    			if (((LA6_1>='D' && LA6_1<='E')||(LA6_1>='d' && LA6_1<='e')))
    			{
    				alt6 = 1;
    			}
    			} finally { DebugExitDecision(6); }
    			switch (alt6)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:116:25: EXPONENT
    				{
    				DebugLocation(116, 25);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(6); }


    			}
    			break;
    		case 3:
    			DebugEnterAlt(3);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:117:9: ( '0' .. '9' )+ EXPONENT
    			{
    			DebugLocation(117, 9);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:117:9: ( '0' .. '9' )+
    			int cnt7=0;
    			try { DebugEnterSubRule(7);
    			while (true)
    			{
    				int alt7=2;
    				try { DebugEnterDecision(7, decisionCanBacktrack[7]);
    				int LA7_1 = input.LA(1);

    				if (((LA7_1>='0' && LA7_1<='9')))
    				{
    					alt7 = 1;
    				}


    				} finally { DebugExitDecision(7); }
    				switch (alt7)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    					{
    					DebugLocation(117, 9);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt7 >= 1)
    						goto loop7;

    					EarlyExitException eee7 = new EarlyExitException( 7, input );
    					DebugRecognitionException(eee7);
    					throw eee7;
    				}
    				cnt7++;
    			}
    			loop7:
    				;

    			} finally { DebugExitSubRule(7); }

    			DebugLocation(117, 21);
    			mEXPONENT(); 

    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("FLOAT", 2);
    		LeaveRule("FLOAT", 2);
    		LeaveRule_FLOAT();
        }
    }
    // $ANTLR end "FLOAT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_AND() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_AND() {}

    // $ANTLR start "AND"
    [GrammarRule("AND")]
    private void mAND()
    {
    	EnterRule_AND();
    	EnterRule("AND", 3);
    	TraceIn("AND", 3);
    		try
    		{
    		int _type = AND;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:121:5: ( A N D )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:121:7: A N D
    		{
    		DebugLocation(121, 7);
    		mA(); 
    		DebugLocation(121, 9);
    		mN(); 
    		DebugLocation(121, 11);
    		mD(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("AND", 3);
    		LeaveRule("AND", 3);
    		LeaveRule_AND();
        }
    }
    // $ANTLR end "AND"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_EE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_EE() {}

    // $ANTLR start "EE"
    [GrammarRule("EE")]
    private void mEE()
    {
    	EnterRule_EE();
    	EnterRule("EE", 4);
    	TraceIn("EE", 4);
    		try
    		{
    		int _type = EE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:122:4: ( E E )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:122:6: E E
    		{
    		DebugLocation(122, 6);
    		mE(); 
    		DebugLocation(122, 8);
    		mE(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("EE", 4);
    		LeaveRule("EE", 4);
    		LeaveRule_EE();
        }
    }
    // $ANTLR end "EE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_EQ() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_EQ() {}

    // $ANTLR start "EQ"
    [GrammarRule("EQ")]
    private void mEQ()
    {
    	EnterRule_EQ();
    	EnterRule("EQ", 5);
    	TraceIn("EQ", 5);
    		try
    		{
    		int _type = EQ;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:123:4: ( '=' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:123:6: '='
    		{
    		DebugLocation(123, 6);
    		Match('='); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("EQ", 5);
    		LeaveRule("EQ", 5);
    		LeaveRule_EQ();
        }
    }
    // $ANTLR end "EQ"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_FALSE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_FALSE() {}

    // $ANTLR start "FALSE"
    [GrammarRule("FALSE")]
    private void mFALSE()
    {
    	EnterRule_FALSE();
    	EnterRule("FALSE", 6);
    	TraceIn("FALSE", 6);
    		try
    		{
    		int _type = FALSE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:124:6: ( F A L S E )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:124:8: F A L S E
    		{
    		DebugLocation(124, 8);
    		mF(); 
    		DebugLocation(124, 10);
    		mA(); 
    		DebugLocation(124, 12);
    		mL(); 
    		DebugLocation(124, 14);
    		mS(); 
    		DebugLocation(124, 16);
    		mE(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("FALSE", 6);
    		LeaveRule("FALSE", 6);
    		LeaveRule_FALSE();
        }
    }
    // $ANTLR end "FALSE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_GE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_GE() {}

    // $ANTLR start "GE"
    [GrammarRule("GE")]
    private void mGE()
    {
    	EnterRule_GE();
    	EnterRule("GE", 7);
    	TraceIn("GE", 7);
    		try
    		{
    		int _type = GE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:4: ( ( '=' '>' ) | ( '>' '=' ) )
    		int alt9=2;
    		try { DebugEnterDecision(9, decisionCanBacktrack[9]);
    		int LA9_1 = input.LA(1);

    		if ((LA9_1=='='))
    		{
    			alt9 = 1;
    		}
    		else if ((LA9_1=='>'))
    		{
    			alt9 = 2;
    		}
    		else
    		{
    			NoViableAltException nvae = new NoViableAltException("", 9, 0, input, 1);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		} finally { DebugExitDecision(9); }
    		switch (alt9)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:6: ( '=' '>' )
    			{
    			DebugLocation(125, 6);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:6: ( '=' '>' )
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:7: '=' '>'
    			{
    			DebugLocation(125, 7);
    			Match('='); 
    			DebugLocation(125, 11);
    			Match('>'); 

    			}


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:18: ( '>' '=' )
    			{
    			DebugLocation(125, 18);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:18: ( '>' '=' )
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:125:19: '>' '='
    			{
    			DebugLocation(125, 19);
    			Match('>'); 
    			DebugLocation(125, 23);
    			Match('='); 

    			}


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("GE", 7);
    		LeaveRule("GE", 7);
    		LeaveRule_GE();
        }
    }
    // $ANTLR end "GE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_GETS() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_GETS() {}

    // $ANTLR start "GETS"
    [GrammarRule("GETS")]
    private void mGETS()
    {
    	EnterRule_GETS();
    	EnterRule("GETS", 8);
    	TraceIn("GETS", 8);
    		try
    		{
    		int _type = GETS;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:126:5: ( ':' '=' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:126:7: ':' '='
    		{
    		DebugLocation(126, 7);
    		Match(':'); 
    		DebugLocation(126, 11);
    		Match('='); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("GETS", 8);
    		LeaveRule("GETS", 8);
    		LeaveRule_GETS();
        }
    }
    // $ANTLR end "GETS"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_GT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_GT() {}

    // $ANTLR start "GT"
    [GrammarRule("GT")]
    private void mGT()
    {
    	EnterRule_GT();
    	EnterRule("GT", 9);
    	TraceIn("GT", 9);
    		try
    		{
    		int _type = GT;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:127:4: ( '>' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:127:6: '>'
    		{
    		DebugLocation(127, 6);
    		Match('>'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("GT", 9);
    		LeaveRule("GT", 9);
    		LeaveRule_GT();
        }
    }
    // $ANTLR end "GT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_LE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_LE() {}

    // $ANTLR start "LE"
    [GrammarRule("LE")]
    private void mLE()
    {
    	EnterRule_LE();
    	EnterRule("LE", 10);
    	TraceIn("LE", 10);
    		try
    		{
    		int _type = LE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:4: ( ( '<' '=' ) | ( '=' '<' ) )
    		int alt10=2;
    		try { DebugEnterDecision(10, decisionCanBacktrack[10]);
    		int LA10_1 = input.LA(1);

    		if ((LA10_1=='<'))
    		{
    			alt10 = 1;
    		}
    		else if ((LA10_1=='='))
    		{
    			alt10 = 2;
    		}
    		else
    		{
    			NoViableAltException nvae = new NoViableAltException("", 10, 0, input, 1);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		} finally { DebugExitDecision(10); }
    		switch (alt10)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:6: ( '<' '=' )
    			{
    			DebugLocation(128, 6);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:6: ( '<' '=' )
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:7: '<' '='
    			{
    			DebugLocation(128, 7);
    			Match('<'); 
    			DebugLocation(128, 11);
    			Match('='); 

    			}


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:18: ( '=' '<' )
    			{
    			DebugLocation(128, 18);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:18: ( '=' '<' )
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:128:19: '=' '<'
    			{
    			DebugLocation(128, 19);
    			Match('='); 
    			DebugLocation(128, 23);
    			Match('<'); 

    			}


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("LE", 10);
    		LeaveRule("LE", 10);
    		LeaveRule_LE();
        }
    }
    // $ANTLR end "LE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_LR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_LR() {}

    // $ANTLR start "LR"
    [GrammarRule("LR")]
    private void mLR()
    {
    	EnterRule_LR();
    	EnterRule("LR", 11);
    	TraceIn("LR", 11);
    		try
    		{
    		int _type = LR;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:129:4: ( L R )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:129:6: L R
    		{
    		DebugLocation(129, 6);
    		mL(); 
    		DebugLocation(129, 8);
    		mR(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("LR", 11);
    		LeaveRule("LR", 11);
    		LeaveRule_LR();
        }
    }
    // $ANTLR end "LR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_LT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_LT() {}

    // $ANTLR start "LT"
    [GrammarRule("LT")]
    private void mLT()
    {
    	EnterRule_LT();
    	EnterRule("LT", 12);
    	TraceIn("LT", 12);
    		try
    		{
    		int _type = LT;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:130:4: ( '<' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:130:6: '<'
    		{
    		DebugLocation(130, 6);
    		Match('<'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("LT", 12);
    		LeaveRule("LT", 12);
    		LeaveRule_LT();
        }
    }
    // $ANTLR end "LT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_MOD() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_MOD() {}

    // $ANTLR start "MOD"
    [GrammarRule("MOD")]
    private void mMOD()
    {
    	EnterRule_MOD();
    	EnterRule("MOD", 13);
    	TraceIn("MOD", 13);
    		try
    		{
    		int _type = MOD;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:131:5: ( M O D )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:131:7: M O D
    		{
    		DebugLocation(131, 7);
    		mM(); 
    		DebugLocation(131, 9);
    		mO(); 
    		DebugLocation(131, 11);
    		mD(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("MOD", 13);
    		LeaveRule("MOD", 13);
    		LeaveRule_MOD();
        }
    }
    // $ANTLR end "MOD"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_NE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_NE() {}

    // $ANTLR start "NE"
    [GrammarRule("NE")]
    private void mNE()
    {
    	EnterRule_NE();
    	EnterRule("NE", 14);
    	TraceIn("NE", 14);
    		try
    		{
    		int _type = NE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:4: ( ( '<' '>' ) | ( '>' '<' ) )
    		int alt11=2;
    		try { DebugEnterDecision(11, decisionCanBacktrack[11]);
    		int LA11_1 = input.LA(1);

    		if ((LA11_1=='<'))
    		{
    			alt11 = 1;
    		}
    		else if ((LA11_1=='>'))
    		{
    			alt11 = 2;
    		}
    		else
    		{
    			NoViableAltException nvae = new NoViableAltException("", 11, 0, input, 1);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		} finally { DebugExitDecision(11); }
    		switch (alt11)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:6: ( '<' '>' )
    			{
    			DebugLocation(132, 6);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:6: ( '<' '>' )
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:7: '<' '>'
    			{
    			DebugLocation(132, 7);
    			Match('<'); 
    			DebugLocation(132, 11);
    			Match('>'); 

    			}


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:18: ( '>' '<' )
    			{
    			DebugLocation(132, 18);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:18: ( '>' '<' )
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:132:19: '>' '<'
    			{
    			DebugLocation(132, 19);
    			Match('>'); 
    			DebugLocation(132, 23);
    			Match('<'); 

    			}


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("NE", 14);
    		LeaveRule("NE", 14);
    		LeaveRule_NE();
        }
    }
    // $ANTLR end "NE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_NOT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_NOT() {}

    // $ANTLR start "NOT"
    [GrammarRule("NOT")]
    private void mNOT()
    {
    	EnterRule_NOT();
    	EnterRule("NOT", 15);
    	TraceIn("NOT", 15);
    		try
    		{
    		int _type = NOT;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:133:5: ( N O T )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:133:7: N O T
    		{
    		DebugLocation(133, 7);
    		mN(); 
    		DebugLocation(133, 9);
    		mO(); 
    		DebugLocation(133, 11);
    		mT(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("NOT", 15);
    		LeaveRule("NOT", 15);
    		LeaveRule_NOT();
        }
    }
    // $ANTLR end "NOT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_OR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_OR() {}

    // $ANTLR start "OR"
    [GrammarRule("OR")]
    private void mOR()
    {
    	EnterRule_OR();
    	EnterRule("OR", 16);
    	TraceIn("OR", 16);
    		try
    		{
    		int _type = OR;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:134:4: ( O R )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:134:6: O R
    		{
    		DebugLocation(134, 6);
    		mO(); 
    		DebugLocation(134, 8);
    		mR(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("OR", 16);
    		LeaveRule("OR", 16);
    		LeaveRule_OR();
        }
    }
    // $ANTLR end "OR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_PI() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_PI() {}

    // $ANTLR start "PI"
    [GrammarRule("PI")]
    private void mPI()
    {
    	EnterRule_PI();
    	EnterRule("PI", 17);
    	TraceIn("PI", 17);
    		try
    		{
    		int _type = PI;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:135:4: ( P I )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:135:6: P I
    		{
    		DebugLocation(135, 6);
    		mP(); 
    		DebugLocation(135, 8);
    		mI(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("PI", 17);
    		LeaveRule("PI", 17);
    		LeaveRule_PI();
        }
    }
    // $ANTLR end "PI"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_TRUE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_TRUE() {}

    // $ANTLR start "TRUE"
    [GrammarRule("TRUE")]
    private void mTRUE()
    {
    	EnterRule_TRUE();
    	EnterRule("TRUE", 18);
    	TraceIn("TRUE", 18);
    		try
    		{
    		int _type = TRUE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:136:5: ( T R U E )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:136:7: T R U E
    		{
    		DebugLocation(136, 7);
    		mT(); 
    		DebugLocation(136, 9);
    		mR(); 
    		DebugLocation(136, 11);
    		mU(); 
    		DebugLocation(136, 13);
    		mE(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("TRUE", 18);
    		LeaveRule("TRUE", 18);
    		LeaveRule_TRUE();
        }
    }
    // $ANTLR end "TRUE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_IDENTIFIER() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_IDENTIFIER() {}

    // $ANTLR start "IDENTIFIER"
    [GrammarRule("IDENTIFIER")]
    private void mIDENTIFIER()
    {
    	EnterRule_IDENTIFIER();
    	EnterRule("IDENTIFIER", 19);
    	TraceIn("IDENTIFIER", 19);
    		try
    		{
    		int _type = IDENTIFIER;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:138:11: ( ( 'A' .. 'Z' | 'a' .. 'z' ) ( 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' | '.' | '!' )* )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:138:13: ( 'A' .. 'Z' | 'a' .. 'z' ) ( 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' | '.' | '!' )*
    		{
    		DebugLocation(138, 13);
    		if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z'))
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}

    		DebugLocation(138, 32);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:138:32: ( 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' | '.' | '!' )*
    		try { DebugEnterSubRule(12);
    		while (true)
    		{
    			int alt12=2;
    			try { DebugEnterDecision(12, decisionCanBacktrack[12]);
    			int LA12_1 = input.LA(1);

    			if ((LA12_1=='!'||LA12_1=='.'||(LA12_1>='0' && LA12_1<='9')||(LA12_1>='A' && LA12_1<='Z')||(LA12_1>='a' && LA12_1<='z')))
    			{
    				alt12 = 1;
    			}


    			} finally { DebugExitDecision(12); }
    			switch ( alt12 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    				{
    				DebugLocation(138, 32);
    				input.Consume();


    				}
    				break;

    			default:
    				goto loop12;
    			}
    		}

    		loop12:
    			;

    		} finally { DebugExitSubRule(12); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("IDENTIFIER", 19);
    		LeaveRule("IDENTIFIER", 19);
    		LeaveRule_IDENTIFIER();
        }
    }
    // $ANTLR end "IDENTIFIER"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_BACKSLASH() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_BACKSLASH() {}

    // $ANTLR start "BACKSLASH"
    [GrammarRule("BACKSLASH")]
    private void mBACKSLASH()
    {
    	EnterRule_BACKSLASH();
    	EnterRule("BACKSLASH", 20);
    	TraceIn("BACKSLASH", 20);
    		try
    		{
    		int _type = BACKSLASH;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:141:11: ( '\\\\' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:141:13: '\\\\'
    		{
    		DebugLocation(141, 13);
    		Match('\\'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("BACKSLASH", 20);
    		LeaveRule("BACKSLASH", 20);
    		LeaveRule_BACKSLASH();
        }
    }
    // $ANTLR end "BACKSLASH"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_CARET() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_CARET() {}

    // $ANTLR start "CARET"
    [GrammarRule("CARET")]
    private void mCARET()
    {
    	EnterRule_CARET();
    	EnterRule("CARET", 21);
    	TraceIn("CARET", 21);
    		try
    		{
    		int _type = CARET;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:142:8: ( '^' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:142:10: '^'
    		{
    		DebugLocation(142, 10);
    		Match('^'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("CARET", 21);
    		LeaveRule("CARET", 21);
    		LeaveRule_CARET();
        }
    }
    // $ANTLR end "CARET"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_COMMA() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_COMMA() {}

    // $ANTLR start "COMMA"
    [GrammarRule("COMMA")]
    private void mCOMMA()
    {
    	EnterRule_COMMA();
    	EnterRule("COMMA", 22);
    	TraceIn("COMMA", 22);
    		try
    		{
    		int _type = COMMA;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:143:8: ( ',' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:143:10: ','
    		{
    		DebugLocation(143, 10);
    		Match(','); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("COMMA", 22);
    		LeaveRule("COMMA", 22);
    		LeaveRule_COMMA();
        }
    }
    // $ANTLR end "COMMA"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_EXCLAIM() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_EXCLAIM() {}

    // $ANTLR start "EXCLAIM"
    [GrammarRule("EXCLAIM")]
    private void mEXCLAIM()
    {
    	EnterRule_EXCLAIM();
    	EnterRule("EXCLAIM", 23);
    	TraceIn("EXCLAIM", 23);
    		try
    		{
    		int _type = EXCLAIM;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:144:10: ( '!' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:144:12: '!'
    		{
    		DebugLocation(144, 12);
    		Match('!'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("EXCLAIM", 23);
    		LeaveRule("EXCLAIM", 23);
    		LeaveRule_EXCLAIM();
        }
    }
    // $ANTLR end "EXCLAIM"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_LPAREN() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_LPAREN() {}

    // $ANTLR start "LPAREN"
    [GrammarRule("LPAREN")]
    private void mLPAREN()
    {
    	EnterRule_LPAREN();
    	EnterRule("LPAREN", 24);
    	TraceIn("LPAREN", 24);
    		try
    		{
    		int _type = LPAREN;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:145:9: ( '(' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:145:11: '('
    		{
    		DebugLocation(145, 11);
    		Match('('); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("LPAREN", 24);
    		LeaveRule("LPAREN", 24);
    		LeaveRule_LPAREN();
        }
    }
    // $ANTLR end "LPAREN"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_MINUS() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_MINUS() {}

    // $ANTLR start "MINUS"
    [GrammarRule("MINUS")]
    private void mMINUS()
    {
    	EnterRule_MINUS();
    	EnterRule("MINUS", 25);
    	TraceIn("MINUS", 25);
    		try
    		{
    		int _type = MINUS;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:146:8: ( '-' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:146:10: '-'
    		{
    		DebugLocation(146, 10);
    		Match('-'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("MINUS", 25);
    		LeaveRule("MINUS", 25);
    		LeaveRule_MINUS();
        }
    }
    // $ANTLR end "MINUS"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_PLUS() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_PLUS() {}

    // $ANTLR start "PLUS"
    [GrammarRule("PLUS")]
    private void mPLUS()
    {
    	EnterRule_PLUS();
    	EnterRule("PLUS", 26);
    	TraceIn("PLUS", 26);
    		try
    		{
    		int _type = PLUS;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:147:7: ( '+' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:147:9: '+'
    		{
    		DebugLocation(147, 9);
    		Match('+'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("PLUS", 26);
    		LeaveRule("PLUS", 26);
    		LeaveRule_PLUS();
        }
    }
    // $ANTLR end "PLUS"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_RPAREN() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_RPAREN() {}

    // $ANTLR start "RPAREN"
    [GrammarRule("RPAREN")]
    private void mRPAREN()
    {
    	EnterRule_RPAREN();
    	EnterRule("RPAREN", 27);
    	TraceIn("RPAREN", 27);
    		try
    		{
    		int _type = RPAREN;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:148:9: ( ')' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:148:11: ')'
    		{
    		DebugLocation(148, 11);
    		Match(')'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("RPAREN", 27);
    		LeaveRule("RPAREN", 27);
    		LeaveRule_RPAREN();
        }
    }
    // $ANTLR end "RPAREN"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SLASH() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SLASH() {}

    // $ANTLR start "SLASH"
    [GrammarRule("SLASH")]
    private void mSLASH()
    {
    	EnterRule_SLASH();
    	EnterRule("SLASH", 28);
    	TraceIn("SLASH", 28);
    		try
    		{
    		int _type = SLASH;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:149:8: ( '/' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:149:10: '/'
    		{
    		DebugLocation(149, 10);
    		Match('/'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SLASH", 28);
    		LeaveRule("SLASH", 28);
    		LeaveRule_SLASH();
        }
    }
    // $ANTLR end "SLASH"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_STARSTAR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_STARSTAR() {}

    // $ANTLR start "STARSTAR"
    [GrammarRule("STARSTAR")]
    private void mSTARSTAR()
    {
    	EnterRule_STARSTAR();
    	EnterRule("STARSTAR", 29);
    	TraceIn("STARSTAR", 29);
    		try
    		{
    		int _type = STARSTAR;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:150:10: ( '*' '*' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:150:12: '*' '*'
    		{
    		DebugLocation(150, 12);
    		Match('*'); 
    		DebugLocation(150, 16);
    		Match('*'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("STARSTAR", 29);
    		LeaveRule("STARSTAR", 29);
    		LeaveRule_STARSTAR();
        }
    }
    // $ANTLR end "STARSTAR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_STAR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_STAR() {}

    // $ANTLR start "STAR"
    [GrammarRule("STAR")]
    private void mSTAR()
    {
    	EnterRule_STAR();
    	EnterRule("STAR", 30);
    	TraceIn("STAR", 30);
    		try
    		{
    		int _type = STAR;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:151:7: ( '*' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:151:9: '*'
    		{
    		DebugLocation(151, 9);
    		Match('*'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("STAR", 30);
    		LeaveRule("STAR", 30);
    		LeaveRule_STAR();
        }
    }
    // $ANTLR end "STAR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_A() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_A() {}

    // $ANTLR start "A"
    [GrammarRule("A")]
    private void mA()
    {
    	EnterRule_A();
    	EnterRule("A", 31);
    	TraceIn("A", 31);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:153:12: ( 'A' | 'a' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(153, 12);
    		if (input.LA(1)=='A'||input.LA(1)=='a')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("A", 31);
    		LeaveRule("A", 31);
    		LeaveRule_A();
        }
    }
    // $ANTLR end "A"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_B() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_B() {}

    // $ANTLR start "B"
    [GrammarRule("B")]
    private void mB()
    {
    	EnterRule_B();
    	EnterRule("B", 32);
    	TraceIn("B", 32);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:154:12: ( 'B' | 'b' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(154, 12);
    		if (input.LA(1)=='B'||input.LA(1)=='b')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("B", 32);
    		LeaveRule("B", 32);
    		LeaveRule_B();
        }
    }
    // $ANTLR end "B"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_C() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_C() {}

    // $ANTLR start "C"
    [GrammarRule("C")]
    private void mC()
    {
    	EnterRule_C();
    	EnterRule("C", 33);
    	TraceIn("C", 33);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:155:12: ( 'C' | 'c' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(155, 12);
    		if (input.LA(1)=='C'||input.LA(1)=='c')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("C", 33);
    		LeaveRule("C", 33);
    		LeaveRule_C();
        }
    }
    // $ANTLR end "C"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_D() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_D() {}

    // $ANTLR start "D"
    [GrammarRule("D")]
    private void mD()
    {
    	EnterRule_D();
    	EnterRule("D", 34);
    	TraceIn("D", 34);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:156:12: ( 'D' | 'd' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(156, 12);
    		if (input.LA(1)=='D'||input.LA(1)=='d')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("D", 34);
    		LeaveRule("D", 34);
    		LeaveRule_D();
        }
    }
    // $ANTLR end "D"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_E() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_E() {}

    // $ANTLR start "E"
    [GrammarRule("E")]
    private void mE()
    {
    	EnterRule_E();
    	EnterRule("E", 35);
    	TraceIn("E", 35);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:157:12: ( 'E' | 'e' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(157, 12);
    		if (input.LA(1)=='E'||input.LA(1)=='e')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("E", 35);
    		LeaveRule("E", 35);
    		LeaveRule_E();
        }
    }
    // $ANTLR end "E"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_F() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_F() {}

    // $ANTLR start "F"
    [GrammarRule("F")]
    private void mF()
    {
    	EnterRule_F();
    	EnterRule("F", 36);
    	TraceIn("F", 36);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:158:12: ( 'F' | 'f' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(158, 12);
    		if (input.LA(1)=='F'||input.LA(1)=='f')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("F", 36);
    		LeaveRule("F", 36);
    		LeaveRule_F();
        }
    }
    // $ANTLR end "F"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_G() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_G() {}

    // $ANTLR start "G"
    [GrammarRule("G")]
    private void mG()
    {
    	EnterRule_G();
    	EnterRule("G", 37);
    	TraceIn("G", 37);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:159:12: ( 'G' | 'g' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(159, 12);
    		if (input.LA(1)=='G'||input.LA(1)=='g')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("G", 37);
    		LeaveRule("G", 37);
    		LeaveRule_G();
        }
    }
    // $ANTLR end "G"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_H() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_H() {}

    // $ANTLR start "H"
    [GrammarRule("H")]
    private void mH()
    {
    	EnterRule_H();
    	EnterRule("H", 38);
    	TraceIn("H", 38);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:160:12: ( 'H' | 'h' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(160, 12);
    		if (input.LA(1)=='H'||input.LA(1)=='h')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("H", 38);
    		LeaveRule("H", 38);
    		LeaveRule_H();
        }
    }
    // $ANTLR end "H"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_I() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_I() {}

    // $ANTLR start "I"
    [GrammarRule("I")]
    private void mI()
    {
    	EnterRule_I();
    	EnterRule("I", 39);
    	TraceIn("I", 39);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:161:12: ( 'I' | 'i' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(161, 12);
    		if (input.LA(1)=='I'||input.LA(1)=='i')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("I", 39);
    		LeaveRule("I", 39);
    		LeaveRule_I();
        }
    }
    // $ANTLR end "I"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_J() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_J() {}

    // $ANTLR start "J"
    [GrammarRule("J")]
    private void mJ()
    {
    	EnterRule_J();
    	EnterRule("J", 40);
    	TraceIn("J", 40);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:162:12: ( 'J' | 'j' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(162, 12);
    		if (input.LA(1)=='J'||input.LA(1)=='j')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("J", 40);
    		LeaveRule("J", 40);
    		LeaveRule_J();
        }
    }
    // $ANTLR end "J"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_K() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_K() {}

    // $ANTLR start "K"
    [GrammarRule("K")]
    private void mK()
    {
    	EnterRule_K();
    	EnterRule("K", 41);
    	TraceIn("K", 41);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:163:12: ( 'K' | 'k' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(163, 12);
    		if (input.LA(1)=='K'||input.LA(1)=='k')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("K", 41);
    		LeaveRule("K", 41);
    		LeaveRule_K();
        }
    }
    // $ANTLR end "K"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_L() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_L() {}

    // $ANTLR start "L"
    [GrammarRule("L")]
    private void mL()
    {
    	EnterRule_L();
    	EnterRule("L", 42);
    	TraceIn("L", 42);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:164:12: ( 'L' | 'l' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(164, 12);
    		if (input.LA(1)=='L'||input.LA(1)=='l')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("L", 42);
    		LeaveRule("L", 42);
    		LeaveRule_L();
        }
    }
    // $ANTLR end "L"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_M() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_M() {}

    // $ANTLR start "M"
    [GrammarRule("M")]
    private void mM()
    {
    	EnterRule_M();
    	EnterRule("M", 43);
    	TraceIn("M", 43);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:165:12: ( 'M' | 'm' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(165, 12);
    		if (input.LA(1)=='M'||input.LA(1)=='m')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("M", 43);
    		LeaveRule("M", 43);
    		LeaveRule_M();
        }
    }
    // $ANTLR end "M"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_N() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_N() {}

    // $ANTLR start "N"
    [GrammarRule("N")]
    private void mN()
    {
    	EnterRule_N();
    	EnterRule("N", 44);
    	TraceIn("N", 44);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:166:12: ( 'N' | 'n' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(166, 12);
    		if (input.LA(1)=='N'||input.LA(1)=='n')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("N", 44);
    		LeaveRule("N", 44);
    		LeaveRule_N();
        }
    }
    // $ANTLR end "N"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_O() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_O() {}

    // $ANTLR start "O"
    [GrammarRule("O")]
    private void mO()
    {
    	EnterRule_O();
    	EnterRule("O", 45);
    	TraceIn("O", 45);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:167:12: ( 'O' | 'o' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(167, 12);
    		if (input.LA(1)=='O'||input.LA(1)=='o')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("O", 45);
    		LeaveRule("O", 45);
    		LeaveRule_O();
        }
    }
    // $ANTLR end "O"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_P() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_P() {}

    // $ANTLR start "P"
    [GrammarRule("P")]
    private void mP()
    {
    	EnterRule_P();
    	EnterRule("P", 46);
    	TraceIn("P", 46);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:168:12: ( 'P' | 'p' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(168, 12);
    		if (input.LA(1)=='P'||input.LA(1)=='p')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("P", 46);
    		LeaveRule("P", 46);
    		LeaveRule_P();
        }
    }
    // $ANTLR end "P"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_Q() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_Q() {}

    // $ANTLR start "Q"
    [GrammarRule("Q")]
    private void mQ()
    {
    	EnterRule_Q();
    	EnterRule("Q", 47);
    	TraceIn("Q", 47);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:169:12: ( 'Q' | 'q' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(169, 12);
    		if (input.LA(1)=='Q'||input.LA(1)=='q')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("Q", 47);
    		LeaveRule("Q", 47);
    		LeaveRule_Q();
        }
    }
    // $ANTLR end "Q"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_R() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_R() {}

    // $ANTLR start "R"
    [GrammarRule("R")]
    private void mR()
    {
    	EnterRule_R();
    	EnterRule("R", 48);
    	TraceIn("R", 48);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:170:12: ( 'R' | 'r' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(170, 12);
    		if (input.LA(1)=='R'||input.LA(1)=='r')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("R", 48);
    		LeaveRule("R", 48);
    		LeaveRule_R();
        }
    }
    // $ANTLR end "R"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_S() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_S() {}

    // $ANTLR start "S"
    [GrammarRule("S")]
    private void mS()
    {
    	EnterRule_S();
    	EnterRule("S", 49);
    	TraceIn("S", 49);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:171:12: ( 'S' | 's' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(171, 12);
    		if (input.LA(1)=='S'||input.LA(1)=='s')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("S", 49);
    		LeaveRule("S", 49);
    		LeaveRule_S();
        }
    }
    // $ANTLR end "S"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T() {}

    // $ANTLR start "T"
    [GrammarRule("T")]
    private void mT()
    {
    	EnterRule_T();
    	EnterRule("T", 50);
    	TraceIn("T", 50);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:172:12: ( 'T' | 't' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(172, 12);
    		if (input.LA(1)=='T'||input.LA(1)=='t')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("T", 50);
    		LeaveRule("T", 50);
    		LeaveRule_T();
        }
    }
    // $ANTLR end "T"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_U() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_U() {}

    // $ANTLR start "U"
    [GrammarRule("U")]
    private void mU()
    {
    	EnterRule_U();
    	EnterRule("U", 51);
    	TraceIn("U", 51);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:173:12: ( 'U' | 'u' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(173, 12);
    		if (input.LA(1)=='U'||input.LA(1)=='u')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("U", 51);
    		LeaveRule("U", 51);
    		LeaveRule_U();
        }
    }
    // $ANTLR end "U"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_V() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_V() {}

    // $ANTLR start "V"
    [GrammarRule("V")]
    private void mV()
    {
    	EnterRule_V();
    	EnterRule("V", 52);
    	TraceIn("V", 52);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:174:12: ( 'V' | 'v' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(174, 12);
    		if (input.LA(1)=='V'||input.LA(1)=='v')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("V", 52);
    		LeaveRule("V", 52);
    		LeaveRule_V();
        }
    }
    // $ANTLR end "V"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_W() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_W() {}

    // $ANTLR start "W"
    [GrammarRule("W")]
    private void mW()
    {
    	EnterRule_W();
    	EnterRule("W", 53);
    	TraceIn("W", 53);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:175:12: ( 'W' | 'w' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(175, 12);
    		if (input.LA(1)=='W'||input.LA(1)=='w')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("W", 53);
    		LeaveRule("W", 53);
    		LeaveRule_W();
        }
    }
    // $ANTLR end "W"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_X() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_X() {}

    // $ANTLR start "X"
    [GrammarRule("X")]
    private void mX()
    {
    	EnterRule_X();
    	EnterRule("X", 54);
    	TraceIn("X", 54);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:176:12: ( 'X' | 'x' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(176, 12);
    		if (input.LA(1)=='X'||input.LA(1)=='x')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("X", 54);
    		LeaveRule("X", 54);
    		LeaveRule_X();
        }
    }
    // $ANTLR end "X"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_Y() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_Y() {}

    // $ANTLR start "Y"
    [GrammarRule("Y")]
    private void mY()
    {
    	EnterRule_Y();
    	EnterRule("Y", 55);
    	TraceIn("Y", 55);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:177:12: ( 'Y' | 'y' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(177, 12);
    		if (input.LA(1)=='Y'||input.LA(1)=='y')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("Y", 55);
    		LeaveRule("Y", 55);
    		LeaveRule_Y();
        }
    }
    // $ANTLR end "Y"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_Z() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_Z() {}

    // $ANTLR start "Z"
    [GrammarRule("Z")]
    private void mZ()
    {
    	EnterRule_Z();
    	EnterRule("Z", 56);
    	TraceIn("Z", 56);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:178:12: ( 'Z' | 'z' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    		{
    		DebugLocation(178, 12);
    		if (input.LA(1)=='Z'||input.LA(1)=='z')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("Z", 56);
    		LeaveRule("Z", 56);
    		LeaveRule_Z();
        }
    }
    // $ANTLR end "Z"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_WS() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_WS() {}

    // $ANTLR start "WS"
    [GrammarRule("WS")]
    private void mWS()
    {
    	EnterRule_WS();
    	EnterRule("WS", 57);
    	TraceIn("WS", 57);
    		try
    		{
    		int _type = WS;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:181:3: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:181:9: ( ' ' | '\\t' | '\\r' | '\\n' )
    		{
    		DebugLocation(181, 9);
    		if ((input.LA(1)>='\t' && input.LA(1)<='\n')||input.LA(1)=='\r'||input.LA(1)==' ')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}

    		DebugLocation(185, 11);
    		_channel=Hidden;

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("WS", 57);
    		LeaveRule("WS", 57);
    		LeaveRule_WS();
        }
    }
    // $ANTLR end "WS"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_STRING() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_STRING() {}

    // $ANTLR start "STRING"
    [GrammarRule("STRING")]
    private void mSTRING()
    {
    	EnterRule_STRING();
    	EnterRule("STRING", 58);
    	TraceIn("STRING", 58);
    		try
    		{
    		int _type = STRING;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:189:5: ( '\"' (~ ( '\\\\' | '\"' ) )* '\"' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:189:8: '\"' (~ ( '\\\\' | '\"' ) )* '\"'
    		{
    		DebugLocation(189, 8);
    		Match('\"'); 
    		DebugLocation(189, 12);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:189:12: (~ ( '\\\\' | '\"' ) )*
    		try { DebugEnterSubRule(13);
    		while (true)
    		{
    			int alt13=2;
    			try { DebugEnterDecision(13, decisionCanBacktrack[13]);
    			int LA13_1 = input.LA(1);

    			if (((LA13_1>='\u0000' && LA13_1<='!')||(LA13_1>='#' && LA13_1<='[')||(LA13_1>=']' && LA13_1<='\uFFFF')))
    			{
    				alt13 = 1;
    			}


    			} finally { DebugExitDecision(13); }
    			switch ( alt13 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    				{
    				DebugLocation(189, 12);
    				input.Consume();


    				}
    				break;

    			default:
    				goto loop13;
    			}
    		}

    		loop13:
    			;

    		} finally { DebugExitSubRule(13); }

    		DebugLocation(189, 29);
    		Match('\"'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("STRING", 58);
    		LeaveRule("STRING", 58);
    		LeaveRule_STRING();
        }
    }
    // $ANTLR end "STRING"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_EXPONENT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_EXPONENT() {}

    // $ANTLR start "EXPONENT"
    [GrammarRule("EXPONENT")]
    private void mEXPONENT()
    {
    	EnterRule_EXPONENT();
    	EnterRule("EXPONENT", 59);
    	TraceIn("EXPONENT", 59);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:192:19: ( ( 'd' | 'D' | 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:192:21: ( 'd' | 'D' | 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
    		{
    		DebugLocation(192, 21);
    		if ((input.LA(1)>='D' && input.LA(1)<='E')||(input.LA(1)>='d' && input.LA(1)<='e'))
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}

    		DebugLocation(192, 39);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:192:39: ( '+' | '-' )?
    		int alt14=2;
    		try { DebugEnterSubRule(14);
    		try { DebugEnterDecision(14, decisionCanBacktrack[14]);
    		int LA14_1 = input.LA(1);

    		if ((LA14_1=='+'||LA14_1=='-'))
    		{
    			alt14 = 1;
    		}
    		} finally { DebugExitDecision(14); }
    		switch (alt14)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    			{
    			DebugLocation(192, 39);
    			input.Consume();


    			}
    			break;

    		}
    		} finally { DebugExitSubRule(14); }

    		DebugLocation(192, 50);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:192:50: ( '0' .. '9' )+
    		int cnt15=0;
    		try { DebugEnterSubRule(15);
    		while (true)
    		{
    			int alt15=2;
    			try { DebugEnterDecision(15, decisionCanBacktrack[15]);
    			int LA15_1 = input.LA(1);

    			if (((LA15_1>='0' && LA15_1<='9')))
    			{
    				alt15 = 1;
    			}


    			} finally { DebugExitDecision(15); }
    			switch (alt15)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:
    				{
    				DebugLocation(192, 50);
    				input.Consume();


    				}
    				break;

    			default:
    				if (cnt15 >= 1)
    					goto loop15;

    				EarlyExitException eee15 = new EarlyExitException( 15, input );
    				DebugRecognitionException(eee15);
    				throw eee15;
    			}
    			cnt15++;
    		}
    		loop15:
    			;

    		} finally { DebugExitSubRule(15); }


    		}

    	}
    	finally
    	{
    		TraceOut("EXPONENT", 59);
    		LeaveRule("EXPONENT", 59);
    		LeaveRule_EXPONENT();
        }
    }
    // $ANTLR end "EXPONENT"

    public override void mTokens()
    {
    	// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:8: ( INTEGER | FLOAT | AND | EE | EQ | FALSE | GE | GETS | GT | LE | LR | LT | MOD | NE | NOT | OR | PI | TRUE | IDENTIFIER | BACKSLASH | CARET | COMMA | EXCLAIM | LPAREN | MINUS | PLUS | RPAREN | SLASH | STARSTAR | STAR | WS | STRING )
    	int alt16=32;
    	try { DebugEnterDecision(16, decisionCanBacktrack[16]);
    	try
    	{
    		alt16 = dfa16.Predict(input);
    	}
    	catch (NoViableAltException nvae)
    	{
    		DebugRecognitionException(nvae);
    		throw;
    	}
    	} finally { DebugExitDecision(16); }
    	switch (alt16)
    	{
    	case 1:
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:10: INTEGER
    		{
    		DebugLocation(1, 10);
    		mINTEGER(); 

    		}
    		break;
    	case 2:
    		DebugEnterAlt(2);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:18: FLOAT
    		{
    		DebugLocation(1, 18);
    		mFLOAT(); 

    		}
    		break;
    	case 3:
    		DebugEnterAlt(3);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:24: AND
    		{
    		DebugLocation(1, 24);
    		mAND(); 

    		}
    		break;
    	case 4:
    		DebugEnterAlt(4);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:28: EE
    		{
    		DebugLocation(1, 28);
    		mEE(); 

    		}
    		break;
    	case 5:
    		DebugEnterAlt(5);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:31: EQ
    		{
    		DebugLocation(1, 31);
    		mEQ(); 

    		}
    		break;
    	case 6:
    		DebugEnterAlt(6);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:34: FALSE
    		{
    		DebugLocation(1, 34);
    		mFALSE(); 

    		}
    		break;
    	case 7:
    		DebugEnterAlt(7);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:40: GE
    		{
    		DebugLocation(1, 40);
    		mGE(); 

    		}
    		break;
    	case 8:
    		DebugEnterAlt(8);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:43: GETS
    		{
    		DebugLocation(1, 43);
    		mGETS(); 

    		}
    		break;
    	case 9:
    		DebugEnterAlt(9);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:48: GT
    		{
    		DebugLocation(1, 48);
    		mGT(); 

    		}
    		break;
    	case 10:
    		DebugEnterAlt(10);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:51: LE
    		{
    		DebugLocation(1, 51);
    		mLE(); 

    		}
    		break;
    	case 11:
    		DebugEnterAlt(11);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:54: LR
    		{
    		DebugLocation(1, 54);
    		mLR(); 

    		}
    		break;
    	case 12:
    		DebugEnterAlt(12);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:57: LT
    		{
    		DebugLocation(1, 57);
    		mLT(); 

    		}
    		break;
    	case 13:
    		DebugEnterAlt(13);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:60: MOD
    		{
    		DebugLocation(1, 60);
    		mMOD(); 

    		}
    		break;
    	case 14:
    		DebugEnterAlt(14);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:64: NE
    		{
    		DebugLocation(1, 64);
    		mNE(); 

    		}
    		break;
    	case 15:
    		DebugEnterAlt(15);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:67: NOT
    		{
    		DebugLocation(1, 67);
    		mNOT(); 

    		}
    		break;
    	case 16:
    		DebugEnterAlt(16);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:71: OR
    		{
    		DebugLocation(1, 71);
    		mOR(); 

    		}
    		break;
    	case 17:
    		DebugEnterAlt(17);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:74: PI
    		{
    		DebugLocation(1, 74);
    		mPI(); 

    		}
    		break;
    	case 18:
    		DebugEnterAlt(18);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:77: TRUE
    		{
    		DebugLocation(1, 77);
    		mTRUE(); 

    		}
    		break;
    	case 19:
    		DebugEnterAlt(19);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:82: IDENTIFIER
    		{
    		DebugLocation(1, 82);
    		mIDENTIFIER(); 

    		}
    		break;
    	case 20:
    		DebugEnterAlt(20);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:93: BACKSLASH
    		{
    		DebugLocation(1, 93);
    		mBACKSLASH(); 

    		}
    		break;
    	case 21:
    		DebugEnterAlt(21);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:103: CARET
    		{
    		DebugLocation(1, 103);
    		mCARET(); 

    		}
    		break;
    	case 22:
    		DebugEnterAlt(22);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:109: COMMA
    		{
    		DebugLocation(1, 109);
    		mCOMMA(); 

    		}
    		break;
    	case 23:
    		DebugEnterAlt(23);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:115: EXCLAIM
    		{
    		DebugLocation(1, 115);
    		mEXCLAIM(); 

    		}
    		break;
    	case 24:
    		DebugEnterAlt(24);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:123: LPAREN
    		{
    		DebugLocation(1, 123);
    		mLPAREN(); 

    		}
    		break;
    	case 25:
    		DebugEnterAlt(25);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:130: MINUS
    		{
    		DebugLocation(1, 130);
    		mMINUS(); 

    		}
    		break;
    	case 26:
    		DebugEnterAlt(26);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:136: PLUS
    		{
    		DebugLocation(1, 136);
    		mPLUS(); 

    		}
    		break;
    	case 27:
    		DebugEnterAlt(27);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:141: RPAREN
    		{
    		DebugLocation(1, 141);
    		mRPAREN(); 

    		}
    		break;
    	case 28:
    		DebugEnterAlt(28);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:148: SLASH
    		{
    		DebugLocation(1, 148);
    		mSLASH(); 

    		}
    		break;
    	case 29:
    		DebugEnterAlt(29);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:154: STARSTAR
    		{
    		DebugLocation(1, 154);
    		mSTARSTAR(); 

    		}
    		break;
    	case 30:
    		DebugEnterAlt(30);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:163: STAR
    		{
    		DebugLocation(1, 163);
    		mSTAR(); 

    		}
    		break;
    	case 31:
    		DebugEnterAlt(31);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:168: WS
    		{
    		DebugLocation(1, 168);
    		mWS(); 

    		}
    		break;
    	case 32:
    		DebugEnterAlt(32);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\Expressions\\StatsDirectExpression.g:1:171: STRING
    		{
    		DebugLocation(1, 171);
    		mSTRING(); 

    		}
    		break;

    	}

    }


	#region DFA
	DFA8 dfa8;
	DFA16 dfa16;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa8 = new DFA8(this);
		dfa16 = new DFA16(this);
	}

	private class DFA8 : DFA
	{
		private const string DFA8_eotS =
			"\x5\xFFFF";
		private const string DFA8_eofS =
			"\x5\xFFFF";
		private const string DFA8_minS =
			"\x2\x2E\x3\xFFFF";
		private const string DFA8_maxS =
			"\x1\x39\x1\x65\x3\xFFFF";
		private const string DFA8_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1\x1\x3";
		private const string DFA8_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA8_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x3\x1\xFFFF\xA\x1\xA\xFFFF\x2\x4\x1E\xFFFF\x2\x4",
				"",
				"",
				""
			};

		private static readonly short[] DFA8_eot = DFA.UnpackEncodedString(DFA8_eotS);
		private static readonly short[] DFA8_eof = DFA.UnpackEncodedString(DFA8_eofS);
		private static readonly char[] DFA8_min = DFA.UnpackEncodedStringToUnsignedChars(DFA8_minS);
		private static readonly char[] DFA8_max = DFA.UnpackEncodedStringToUnsignedChars(DFA8_maxS);
		private static readonly short[] DFA8_accept = DFA.UnpackEncodedString(DFA8_acceptS);
		private static readonly short[] DFA8_special = DFA.UnpackEncodedString(DFA8_specialS);
		private static readonly short[][] DFA8_transition;

		static DFA8()
		{
			int numStates = DFA8_transitionS.Length;
			DFA8_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA8_transition[i] = DFA.UnpackEncodedString(DFA8_transitionS[i]);
			}
		}

		public DFA8( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 8;
			this.eot = DFA8_eot;
			this.eof = DFA8_eof;
			this.min = DFA8_min;
			this.max = DFA8_max;
			this.accept = DFA8_accept;
			this.special = DFA8_special;
			this.transition = DFA8_transition;
		}

		public override string Description { get { return "114:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA16 : DFA
	{
		private const string DFA16_eotS =
			"\x1\xFFFF\x1\x1D\x1\xFFFF\x2\x10\x1\x22\x1\x10\x1\x25\x1\xFFFF\x1\x26"+
			"\x6\x10\xA\xFFFF\x1\x2E\x3\xFFFF\x1\x10\x1\x30\x3\xFFFF\x1\x10\x3\xFFFF"+
			"\x1\x32\x2\x10\x1\x35\x1\x36\x1\x10\x2\xFFFF\x1\x38\x1\xFFFF\x1\x10\x1"+
			"\xFFFF\x1\x3A\x1\x3B\x2\xFFFF\x1\x10\x1\xFFFF\x1\x10\x2\xFFFF\x1\x3E"+
			"\x1\x3F\x2\xFFFF";
		private const string DFA16_eofS =
			"\x40\xFFFF";
		private const string DFA16_minS =
			"\x1\x9\x1\x2E\x1\xFFFF\x1\x4E\x1\x45\x1\x3C\x1\x41\x1\x3C\x1\xFFFF\x1"+
			"\x3D\x1\x52\x2\x4F\x1\x52\x1\x49\x1\x52\xA\xFFFF\x1\x2A\x3\xFFFF\x1\x44"+
			"\x1\x21\x3\xFFFF\x1\x4C\x3\xFFFF\x1\x21\x1\x44\x1\x54\x2\x21\x1\x55\x2"+
			"\xFFFF\x1\x21\x1\xFFFF\x1\x53\x1\xFFFF\x2\x21\x2\xFFFF\x1\x45\x1\xFFFF"+
			"\x1\x45\x2\xFFFF\x2\x21\x2\xFFFF";
		private const string DFA16_maxS =
			"\x1\x7A\x1\x65\x1\xFFFF\x1\x6E\x1\x65\x1\x3E\x1\x61\x1\x3D\x1\xFFFF\x1"+
			"\x3E\x1\x72\x2\x6F\x1\x72\x1\x69\x1\x72\xA\xFFFF\x1\x2A\x3\xFFFF\x1\x64"+
			"\x1\x7A\x3\xFFFF\x1\x6C\x3\xFFFF\x1\x7A\x1\x64\x1\x74\x2\x7A\x1\x75\x2"+
			"\xFFFF\x1\x7A\x1\xFFFF\x1\x73\x1\xFFFF\x2\x7A\x2\xFFFF\x1\x65\x1\xFFFF"+
			"\x1\x65\x2\xFFFF\x2\x7A\x2\xFFFF";
		private const string DFA16_acceptS =
			"\x2\xFFFF\x1\x2\x5\xFFFF\x1\x8\x7\xFFFF\x1\x13\x1\x14\x1\x15\x1\x16\x1"+
			"\x17\x1\x18\x1\x19\x1\x1A\x1\x1B\x1\x1C\x1\xFFFF\x1\x1F\x1\x20\x1\x1"+
			"\x2\xFFFF\x1\x7\x1\xA\x1\x5\x1\xFFFF\x1\xE\x1\x9\x1\xC\x6\xFFFF\x1\x1D"+
			"\x1\x1E\x1\xFFFF\x1\x4\x1\xFFFF\x1\xB\x2\xFFFF\x1\x10\x1\x11\x1\xFFFF"+
			"\x1\x3\x1\xFFFF\x1\xD\x1\xF\x2\xFFFF\x1\x12\x1\x6";
		private const string DFA16_specialS =
			"\x40\xFFFF}>";
		private static readonly string[] DFA16_transitionS =
			{
				"\x2\x1B\x2\xFFFF\x1\x1B\x12\xFFFF\x1\x1B\x1\x14\x1\x1C\x5\xFFFF\x1\x15"+
				"\x1\x18\x1\x1A\x1\x17\x1\x13\x1\x16\x1\x2\x1\x19\xA\x1\x1\x8\x1\xFFFF"+
				"\x1\x9\x1\x5\x1\x7\x2\xFFFF\x1\x3\x3\x10\x1\x4\x1\x6\x5\x10\x1\xA\x1"+
				"\xB\x1\xC\x1\xD\x1\xE\x3\x10\x1\xF\x6\x10\x1\xFFFF\x1\x11\x1\xFFFF\x1"+
				"\x12\x2\xFFFF\x1\x3\x3\x10\x1\x4\x1\x6\x5\x10\x1\xA\x1\xB\x1\xC\x1\xD"+
				"\x1\xE\x3\x10\x1\xF\x6\x10",
				"\x1\x2\x1\xFFFF\xA\x1\xA\xFFFF\x2\x2\x1E\xFFFF\x2\x2",
				"",
				"\x1\x1E\x1F\xFFFF\x1\x1E",
				"\x1\x1F\x1F\xFFFF\x1\x1F",
				"\x1\x21\x1\xFFFF\x1\x20",
				"\x1\x23\x1F\xFFFF\x1\x23",
				"\x1\x24\x1\x20",
				"",
				"\x1\x21\x1\x24",
				"\x1\x27\x1F\xFFFF\x1\x27",
				"\x1\x28\x1F\xFFFF\x1\x28",
				"\x1\x29\x1F\xFFFF\x1\x29",
				"\x1\x2A\x1F\xFFFF\x1\x2A",
				"\x1\x2B\x1F\xFFFF\x1\x2B",
				"\x1\x2C\x1F\xFFFF\x1\x2C",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x2D",
				"",
				"",
				"",
				"\x1\x2F\x1F\xFFFF\x1\x2F",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"",
				"",
				"",
				"\x1\x31\x1F\xFFFF\x1\x31",
				"",
				"",
				"",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"\x1\x33\x1F\xFFFF\x1\x33",
				"\x1\x34\x1F\xFFFF\x1\x34",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"\x1\x37\x1F\xFFFF\x1\x37",
				"",
				"",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"",
				"\x1\x39\x1F\xFFFF\x1\x39",
				"",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"",
				"",
				"\x1\x3C\x1F\xFFFF\x1\x3C",
				"",
				"\x1\x3D\x1F\xFFFF\x1\x3D",
				"",
				"",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"\x1\x10\xC\xFFFF\x1\x10\x1\xFFFF\xA\x10\x7\xFFFF\x1A\x10\x6\xFFFF\x1A"+
				"\x10",
				"",
				""
			};

		private static readonly short[] DFA16_eot = DFA.UnpackEncodedString(DFA16_eotS);
		private static readonly short[] DFA16_eof = DFA.UnpackEncodedString(DFA16_eofS);
		private static readonly char[] DFA16_min = DFA.UnpackEncodedStringToUnsignedChars(DFA16_minS);
		private static readonly char[] DFA16_max = DFA.UnpackEncodedStringToUnsignedChars(DFA16_maxS);
		private static readonly short[] DFA16_accept = DFA.UnpackEncodedString(DFA16_acceptS);
		private static readonly short[] DFA16_special = DFA.UnpackEncodedString(DFA16_specialS);
		private static readonly short[][] DFA16_transition;

		static DFA16()
		{
			int numStates = DFA16_transitionS.Length;
			DFA16_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA16_transition[i] = DFA.UnpackEncodedString(DFA16_transitionS[i]);
			}
		}

		public DFA16( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 16;
			this.eot = DFA16_eot;
			this.eof = DFA16_eof;
			this.min = DFA16_min;
			this.max = DFA16_max;
			this.accept = DFA16_accept;
			this.special = DFA16_special;
			this.transition = DFA16_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( INTEGER | FLOAT | AND | EE | EQ | FALSE | GE | GETS | GT | LE | LR | LT | MOD | NE | NOT | OR | PI | TRUE | IDENTIFIER | BACKSLASH | CARET | COMMA | EXCLAIM | LPAREN | MINUS | PLUS | RPAREN | SLASH | STARSTAR | STAR | WS | STRING );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
