//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4.1.9004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4.1.9004 C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g 2012-04-05 16:09:07

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4.1.9004")]
[System.CLSCompliant(false)]
public partial class ActiveRtfLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int A=4;
	public const int B=5;
	public const int BUMF=6;
	public const int C=7;
	public const int COLON=8;
	public const int D=9;
	public const int E=10;
	public const int F=11;
	public const int G=12;
	public const int H=13;
	public const int I=14;
	public const int IDENTIFIER=15;
	public const int J=16;
	public const int K=17;
	public const int L=18;
	public const int M=19;
	public const int N=20;
	public const int O=21;
	public const int P=22;
	public const int Q=23;
	public const int R=24;
	public const int S=25;
	public const int SLASH=26;
	public const int SLASHBF=27;
	public const int SLASHBS=28;
	public const int SLASHSTAR=29;
	public const int T=30;
	public const int U=31;
	public const int V=32;
	public const int W=33;
	public const int WS=34;
	public const int X=35;
	public const int Y=36;
	public const int Z=37;

    // delegates
    // delegators

	public ActiveRtfLexer()
	{
		OnCreated();
	}

	public ActiveRtfLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public ActiveRtfLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g"; } }

	private static readonly bool[] decisionCanBacktrack = new bool[0];

	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SLASHBF() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SLASHBF() {}

    // $ANTLR start "SLASHBF"
    [GrammarRule("SLASHBF")]
    private void mSLASHBF()
    {
    	EnterRule_SLASHBF();
    	EnterRule("SLASHBF", 1);
    	TraceIn("SLASHBF", 1);
    		try
    		{
    		int _type = SLASHBF;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:59:9: ( '/' B F )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:59:11: '/' B F
    		{
    		DebugLocation(59, 11);
    		Match('/'); 
    		DebugLocation(59, 15);
    		mB(); 
    		DebugLocation(59, 17);
    		mF(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SLASHBF", 1);
    		LeaveRule("SLASHBF", 1);
    		LeaveRule_SLASHBF();
        }
    }
    // $ANTLR end "SLASHBF"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SLASHBS() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SLASHBS() {}

    // $ANTLR start "SLASHBS"
    [GrammarRule("SLASHBS")]
    private void mSLASHBS()
    {
    	EnterRule_SLASHBS();
    	EnterRule("SLASHBS", 2);
    	TraceIn("SLASHBS", 2);
    		try
    		{
    		int _type = SLASHBS;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:60:9: ( '/' B S )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:60:11: '/' B S
    		{
    		DebugLocation(60, 11);
    		Match('/'); 
    		DebugLocation(60, 15);
    		mB(); 
    		DebugLocation(60, 17);
    		mS(); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SLASHBS", 2);
    		LeaveRule("SLASHBS", 2);
    		LeaveRule_SLASHBS();
        }
    }
    // $ANTLR end "SLASHBS"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SLASHSTAR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SLASHSTAR() {}

    // $ANTLR start "SLASHSTAR"
    [GrammarRule("SLASHSTAR")]
    private void mSLASHSTAR()
    {
    	EnterRule_SLASHSTAR();
    	EnterRule("SLASHSTAR", 3);
    	TraceIn("SLASHSTAR", 3);
    		try
    		{
    		int _type = SLASHSTAR;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:61:11: ( '/' '*' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:61:13: '/' '*'
    		{
    		DebugLocation(61, 13);
    		Match('/'); 
    		DebugLocation(61, 17);
    		Match('*'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SLASHSTAR", 3);
    		LeaveRule("SLASHSTAR", 3);
    		LeaveRule_SLASHSTAR();
        }
    }
    // $ANTLR end "SLASHSTAR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_COLON() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_COLON() {}

    // $ANTLR start "COLON"
    [GrammarRule("COLON")]
    private void mCOLON()
    {
    	EnterRule_COLON();
    	EnterRule("COLON", 4);
    	TraceIn("COLON", 4);
    		try
    		{
    		int _type = COLON;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:64:8: ( ':' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:64:10: ':'
    		{
    		DebugLocation(64, 10);
    		Match(':'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("COLON", 4);
    		LeaveRule("COLON", 4);
    		LeaveRule_COLON();
        }
    }
    // $ANTLR end "COLON"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_IDENTIFIER() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_IDENTIFIER() {}

    // $ANTLR start "IDENTIFIER"
    [GrammarRule("IDENTIFIER")]
    private void mIDENTIFIER()
    {
    	EnterRule_IDENTIFIER();
    	EnterRule("IDENTIFIER", 5);
    	TraceIn("IDENTIFIER", 5);
    		try
    		{
    		int _type = IDENTIFIER;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:65:11: ( ( 'A' .. 'Z' | 'a' .. 'z' ) ( 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' )* )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:65:13: ( 'A' .. 'Z' | 'a' .. 'z' ) ( 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' )*
    		{
    		DebugLocation(65, 13);
    		if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z'))
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}

    		DebugLocation(65, 32);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:65:32: ( 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' )*
    		try { DebugEnterSubRule(1);
    		while (true)
    		{
    			int alt1=2;
    			try { DebugEnterDecision(1, decisionCanBacktrack[1]);
    			int LA1_1 = input.LA(1);

    			if (((LA1_1>='0' && LA1_1<='9')||(LA1_1>='A' && LA1_1<='Z')||(LA1_1>='a' && LA1_1<='z')))
    			{
    				alt1 = 1;
    			}


    			} finally { DebugExitDecision(1); }
    			switch ( alt1 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    				{
    				DebugLocation(65, 32);
    				input.Consume();


    				}
    				break;

    			default:
    				goto loop1;
    			}
    		}

    		loop1:
    			;

    		} finally { DebugExitSubRule(1); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("IDENTIFIER", 5);
    		LeaveRule("IDENTIFIER", 5);
    		LeaveRule_IDENTIFIER();
        }
    }
    // $ANTLR end "IDENTIFIER"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SLASH() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SLASH() {}

    // $ANTLR start "SLASH"
    [GrammarRule("SLASH")]
    private void mSLASH()
    {
    	EnterRule_SLASH();
    	EnterRule("SLASH", 6);
    	TraceIn("SLASH", 6);
    		try
    		{
    		int _type = SLASH;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:66:8: ( '/' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:66:10: '/'
    		{
    		DebugLocation(66, 10);
    		Match('/'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SLASH", 6);
    		LeaveRule("SLASH", 6);
    		LeaveRule_SLASH();
        }
    }
    // $ANTLR end "SLASH"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_WS() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_WS() {}

    // $ANTLR start "WS"
    [GrammarRule("WS")]
    private void mWS()
    {
    	EnterRule_WS();
    	EnterRule("WS", 7);
    	TraceIn("WS", 7);
    		try
    		{
    		int _type = WS;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:67:3: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(67, 3);
    		if ((input.LA(1)>='\t' && input.LA(1)<='\n')||input.LA(1)=='\r'||input.LA(1)==' ')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("WS", 7);
    		LeaveRule("WS", 7);
    		LeaveRule_WS();
        }
    }
    // $ANTLR end "WS"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_BUMF() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_BUMF() {}

    // $ANTLR start "BUMF"
    [GrammarRule("BUMF")]
    private void mBUMF()
    {
    	EnterRule_BUMF();
    	EnterRule("BUMF", 8);
    	TraceIn("BUMF", 8);
    		try
    		{
    		int _type = BUMF;
    		int _channel = DefaultTokenChannel;
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:70:6: ( (~ ( '/' | ':' | ' ' | '\\t' | '\\r' | '\\n' | 'A' .. 'Z' | 'a' .. 'z' ) )+ )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:70:8: (~ ( '/' | ':' | ' ' | '\\t' | '\\r' | '\\n' | 'A' .. 'Z' | 'a' .. 'z' ) )+
    		{
    		DebugLocation(70, 8);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:70:8: (~ ( '/' | ':' | ' ' | '\\t' | '\\r' | '\\n' | 'A' .. 'Z' | 'a' .. 'z' ) )+
    		int cnt2=0;
    		try { DebugEnterSubRule(2);
    		while (true)
    		{
    			int alt2=2;
    			try { DebugEnterDecision(2, decisionCanBacktrack[2]);
    			int LA2_1 = input.LA(1);

    			if (((LA2_1>='\u0000' && LA2_1<='\b')||(LA2_1>='\u000B' && LA2_1<='\f')||(LA2_1>='\u000E' && LA2_1<='\u001F')||(LA2_1>='!' && LA2_1<='.')||(LA2_1>='0' && LA2_1<='9')||(LA2_1>=';' && LA2_1<='@')||(LA2_1>='[' && LA2_1<='`')||(LA2_1>='{' && LA2_1<='\uFFFF')))
    			{
    				alt2 = 1;
    			}


    			} finally { DebugExitDecision(2); }
    			switch (alt2)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    				{
    				DebugLocation(70, 8);
    				input.Consume();


    				}
    				break;

    			default:
    				if (cnt2 >= 1)
    					goto loop2;

    				EarlyExitException eee2 = new EarlyExitException( 2, input );
    				DebugRecognitionException(eee2);
    				throw eee2;
    			}
    			cnt2++;
    		}
    		loop2:
    			;

    		} finally { DebugExitSubRule(2); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("BUMF", 8);
    		LeaveRule("BUMF", 8);
    		LeaveRule_BUMF();
        }
    }
    // $ANTLR end "BUMF"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_A() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_A() {}

    // $ANTLR start "A"
    [GrammarRule("A")]
    private void mA()
    {
    	EnterRule_A();
    	EnterRule("A", 9);
    	TraceIn("A", 9);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:72:12: ( 'A' | 'a' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(72, 12);
    		if (input.LA(1)=='A'||input.LA(1)=='a')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("A", 9);
    		LeaveRule("A", 9);
    		LeaveRule_A();
        }
    }
    // $ANTLR end "A"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_B() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_B() {}

    // $ANTLR start "B"
    [GrammarRule("B")]
    private void mB()
    {
    	EnterRule_B();
    	EnterRule("B", 10);
    	TraceIn("B", 10);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:73:12: ( 'B' | 'b' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(73, 12);
    		if (input.LA(1)=='B'||input.LA(1)=='b')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("B", 10);
    		LeaveRule("B", 10);
    		LeaveRule_B();
        }
    }
    // $ANTLR end "B"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_C() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_C() {}

    // $ANTLR start "C"
    [GrammarRule("C")]
    private void mC()
    {
    	EnterRule_C();
    	EnterRule("C", 11);
    	TraceIn("C", 11);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:74:12: ( 'C' | 'c' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(74, 12);
    		if (input.LA(1)=='C'||input.LA(1)=='c')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("C", 11);
    		LeaveRule("C", 11);
    		LeaveRule_C();
        }
    }
    // $ANTLR end "C"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_D() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_D() {}

    // $ANTLR start "D"
    [GrammarRule("D")]
    private void mD()
    {
    	EnterRule_D();
    	EnterRule("D", 12);
    	TraceIn("D", 12);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:75:12: ( 'D' | 'd' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(75, 12);
    		if (input.LA(1)=='D'||input.LA(1)=='d')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("D", 12);
    		LeaveRule("D", 12);
    		LeaveRule_D();
        }
    }
    // $ANTLR end "D"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_E() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_E() {}

    // $ANTLR start "E"
    [GrammarRule("E")]
    private void mE()
    {
    	EnterRule_E();
    	EnterRule("E", 13);
    	TraceIn("E", 13);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:76:12: ( 'E' | 'e' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(76, 12);
    		if (input.LA(1)=='E'||input.LA(1)=='e')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("E", 13);
    		LeaveRule("E", 13);
    		LeaveRule_E();
        }
    }
    // $ANTLR end "E"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_F() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_F() {}

    // $ANTLR start "F"
    [GrammarRule("F")]
    private void mF()
    {
    	EnterRule_F();
    	EnterRule("F", 14);
    	TraceIn("F", 14);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:77:12: ( 'F' | 'f' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(77, 12);
    		if (input.LA(1)=='F'||input.LA(1)=='f')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("F", 14);
    		LeaveRule("F", 14);
    		LeaveRule_F();
        }
    }
    // $ANTLR end "F"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_G() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_G() {}

    // $ANTLR start "G"
    [GrammarRule("G")]
    private void mG()
    {
    	EnterRule_G();
    	EnterRule("G", 15);
    	TraceIn("G", 15);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:78:12: ( 'G' | 'g' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(78, 12);
    		if (input.LA(1)=='G'||input.LA(1)=='g')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("G", 15);
    		LeaveRule("G", 15);
    		LeaveRule_G();
        }
    }
    // $ANTLR end "G"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_H() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_H() {}

    // $ANTLR start "H"
    [GrammarRule("H")]
    private void mH()
    {
    	EnterRule_H();
    	EnterRule("H", 16);
    	TraceIn("H", 16);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:79:12: ( 'H' | 'h' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(79, 12);
    		if (input.LA(1)=='H'||input.LA(1)=='h')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("H", 16);
    		LeaveRule("H", 16);
    		LeaveRule_H();
        }
    }
    // $ANTLR end "H"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_I() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_I() {}

    // $ANTLR start "I"
    [GrammarRule("I")]
    private void mI()
    {
    	EnterRule_I();
    	EnterRule("I", 17);
    	TraceIn("I", 17);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:80:12: ( 'I' | 'i' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(80, 12);
    		if (input.LA(1)=='I'||input.LA(1)=='i')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("I", 17);
    		LeaveRule("I", 17);
    		LeaveRule_I();
        }
    }
    // $ANTLR end "I"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_J() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_J() {}

    // $ANTLR start "J"
    [GrammarRule("J")]
    private void mJ()
    {
    	EnterRule_J();
    	EnterRule("J", 18);
    	TraceIn("J", 18);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:81:12: ( 'J' | 'j' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(81, 12);
    		if (input.LA(1)=='J'||input.LA(1)=='j')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("J", 18);
    		LeaveRule("J", 18);
    		LeaveRule_J();
        }
    }
    // $ANTLR end "J"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_K() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_K() {}

    // $ANTLR start "K"
    [GrammarRule("K")]
    private void mK()
    {
    	EnterRule_K();
    	EnterRule("K", 19);
    	TraceIn("K", 19);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:82:12: ( 'K' | 'k' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(82, 12);
    		if (input.LA(1)=='K'||input.LA(1)=='k')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("K", 19);
    		LeaveRule("K", 19);
    		LeaveRule_K();
        }
    }
    // $ANTLR end "K"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_L() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_L() {}

    // $ANTLR start "L"
    [GrammarRule("L")]
    private void mL()
    {
    	EnterRule_L();
    	EnterRule("L", 20);
    	TraceIn("L", 20);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:83:12: ( 'L' | 'l' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(83, 12);
    		if (input.LA(1)=='L'||input.LA(1)=='l')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("L", 20);
    		LeaveRule("L", 20);
    		LeaveRule_L();
        }
    }
    // $ANTLR end "L"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_M() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_M() {}

    // $ANTLR start "M"
    [GrammarRule("M")]
    private void mM()
    {
    	EnterRule_M();
    	EnterRule("M", 21);
    	TraceIn("M", 21);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:84:12: ( 'M' | 'm' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(84, 12);
    		if (input.LA(1)=='M'||input.LA(1)=='m')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("M", 21);
    		LeaveRule("M", 21);
    		LeaveRule_M();
        }
    }
    // $ANTLR end "M"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_N() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_N() {}

    // $ANTLR start "N"
    [GrammarRule("N")]
    private void mN()
    {
    	EnterRule_N();
    	EnterRule("N", 22);
    	TraceIn("N", 22);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:85:12: ( 'N' | 'n' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(85, 12);
    		if (input.LA(1)=='N'||input.LA(1)=='n')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("N", 22);
    		LeaveRule("N", 22);
    		LeaveRule_N();
        }
    }
    // $ANTLR end "N"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_O() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_O() {}

    // $ANTLR start "O"
    [GrammarRule("O")]
    private void mO()
    {
    	EnterRule_O();
    	EnterRule("O", 23);
    	TraceIn("O", 23);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:86:12: ( 'O' | 'o' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(86, 12);
    		if (input.LA(1)=='O'||input.LA(1)=='o')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("O", 23);
    		LeaveRule("O", 23);
    		LeaveRule_O();
        }
    }
    // $ANTLR end "O"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_P() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_P() {}

    // $ANTLR start "P"
    [GrammarRule("P")]
    private void mP()
    {
    	EnterRule_P();
    	EnterRule("P", 24);
    	TraceIn("P", 24);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:87:12: ( 'P' | 'p' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(87, 12);
    		if (input.LA(1)=='P'||input.LA(1)=='p')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("P", 24);
    		LeaveRule("P", 24);
    		LeaveRule_P();
        }
    }
    // $ANTLR end "P"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_Q() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_Q() {}

    // $ANTLR start "Q"
    [GrammarRule("Q")]
    private void mQ()
    {
    	EnterRule_Q();
    	EnterRule("Q", 25);
    	TraceIn("Q", 25);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:88:12: ( 'Q' | 'q' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(88, 12);
    		if (input.LA(1)=='Q'||input.LA(1)=='q')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("Q", 25);
    		LeaveRule("Q", 25);
    		LeaveRule_Q();
        }
    }
    // $ANTLR end "Q"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_R() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_R() {}

    // $ANTLR start "R"
    [GrammarRule("R")]
    private void mR()
    {
    	EnterRule_R();
    	EnterRule("R", 26);
    	TraceIn("R", 26);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:89:12: ( 'R' | 'r' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(89, 12);
    		if (input.LA(1)=='R'||input.LA(1)=='r')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("R", 26);
    		LeaveRule("R", 26);
    		LeaveRule_R();
        }
    }
    // $ANTLR end "R"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_S() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_S() {}

    // $ANTLR start "S"
    [GrammarRule("S")]
    private void mS()
    {
    	EnterRule_S();
    	EnterRule("S", 27);
    	TraceIn("S", 27);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:90:12: ( 'S' | 's' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(90, 12);
    		if (input.LA(1)=='S'||input.LA(1)=='s')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("S", 27);
    		LeaveRule("S", 27);
    		LeaveRule_S();
        }
    }
    // $ANTLR end "S"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T() {}

    // $ANTLR start "T"
    [GrammarRule("T")]
    private void mT()
    {
    	EnterRule_T();
    	EnterRule("T", 28);
    	TraceIn("T", 28);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:91:12: ( 'T' | 't' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(91, 12);
    		if (input.LA(1)=='T'||input.LA(1)=='t')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("T", 28);
    		LeaveRule("T", 28);
    		LeaveRule_T();
        }
    }
    // $ANTLR end "T"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_U() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_U() {}

    // $ANTLR start "U"
    [GrammarRule("U")]
    private void mU()
    {
    	EnterRule_U();
    	EnterRule("U", 29);
    	TraceIn("U", 29);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:92:12: ( 'U' | 'u' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(92, 12);
    		if (input.LA(1)=='U'||input.LA(1)=='u')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("U", 29);
    		LeaveRule("U", 29);
    		LeaveRule_U();
        }
    }
    // $ANTLR end "U"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_V() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_V() {}

    // $ANTLR start "V"
    [GrammarRule("V")]
    private void mV()
    {
    	EnterRule_V();
    	EnterRule("V", 30);
    	TraceIn("V", 30);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:93:12: ( 'V' | 'v' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(93, 12);
    		if (input.LA(1)=='V'||input.LA(1)=='v')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("V", 30);
    		LeaveRule("V", 30);
    		LeaveRule_V();
        }
    }
    // $ANTLR end "V"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_W() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_W() {}

    // $ANTLR start "W"
    [GrammarRule("W")]
    private void mW()
    {
    	EnterRule_W();
    	EnterRule("W", 31);
    	TraceIn("W", 31);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:94:12: ( 'W' | 'w' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(94, 12);
    		if (input.LA(1)=='W'||input.LA(1)=='w')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("W", 31);
    		LeaveRule("W", 31);
    		LeaveRule_W();
        }
    }
    // $ANTLR end "W"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_X() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_X() {}

    // $ANTLR start "X"
    [GrammarRule("X")]
    private void mX()
    {
    	EnterRule_X();
    	EnterRule("X", 32);
    	TraceIn("X", 32);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:95:12: ( 'X' | 'x' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(95, 12);
    		if (input.LA(1)=='X'||input.LA(1)=='x')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("X", 32);
    		LeaveRule("X", 32);
    		LeaveRule_X();
        }
    }
    // $ANTLR end "X"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_Y() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_Y() {}

    // $ANTLR start "Y"
    [GrammarRule("Y")]
    private void mY()
    {
    	EnterRule_Y();
    	EnterRule("Y", 33);
    	TraceIn("Y", 33);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:96:12: ( 'Y' | 'y' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(96, 12);
    		if (input.LA(1)=='Y'||input.LA(1)=='y')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("Y", 33);
    		LeaveRule("Y", 33);
    		LeaveRule_Y();
        }
    }
    // $ANTLR end "Y"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_Z() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_Z() {}

    // $ANTLR start "Z"
    [GrammarRule("Z")]
    private void mZ()
    {
    	EnterRule_Z();
    	EnterRule("Z", 34);
    	TraceIn("Z", 34);
    		try
    		{
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:97:12: ( 'Z' | 'z' )
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:
    		{
    		DebugLocation(97, 12);
    		if (input.LA(1)=='Z'||input.LA(1)=='z')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("Z", 34);
    		LeaveRule("Z", 34);
    		LeaveRule_Z();
        }
    }
    // $ANTLR end "Z"

    public override void mTokens()
    {
    	// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:8: ( SLASHBF | SLASHBS | SLASHSTAR | COLON | IDENTIFIER | SLASH | WS | BUMF )
    	int alt3=8;
    	try { DebugEnterDecision(3, decisionCanBacktrack[3]);
    	int LA3_1 = input.LA(1);

    	if ((LA3_1=='/'))
    	{
    		switch (input.LA(2))
    		{
    		case '*':
    			{
    			alt3 = 3;
    			}
    			break;
    		case 'B':
    		case 'b':
    			{
    			int LA3_3 = input.LA(3);

    			if ((LA3_3=='F'||LA3_3=='f'))
    			{
    				alt3 = 1;
    			}
    			else if ((LA3_3=='S'||LA3_3=='s'))
    			{
    				alt3 = 2;
    			}
    			else
    			{
    				NoViableAltException nvae = new NoViableAltException("", 3, 7, input, 3);
    				DebugRecognitionException(nvae);
    				throw nvae;
    			}
    			}
    			break;
    		default:
    			alt3=6;
    			break;

    		}

    	}
    	else if ((LA3_1==':'))
    	{
    		alt3 = 4;
    	}
    	else if (((LA3_1>='A' && LA3_1<='Z')||(LA3_1>='a' && LA3_1<='z')))
    	{
    		alt3 = 5;
    	}
    	else if (((LA3_1>='\t' && LA3_1<='\n')||LA3_1=='\r'||LA3_1==' '))
    	{
    		alt3 = 7;
    	}
    	else if (((LA3_1>='\u0000' && LA3_1<='\b')||(LA3_1>='\u000B' && LA3_1<='\f')||(LA3_1>='\u000E' && LA3_1<='\u001F')||(LA3_1>='!' && LA3_1<='.')||(LA3_1>='0' && LA3_1<='9')||(LA3_1>=';' && LA3_1<='@')||(LA3_1>='[' && LA3_1<='`')||(LA3_1>='{' && LA3_1<='\uFFFF')))
    	{
    		alt3 = 8;
    	}
    	else
    	{
    		NoViableAltException nvae = new NoViableAltException("", 3, 0, input, 1);
    		DebugRecognitionException(nvae);
    		throw nvae;
    	}
    	} finally { DebugExitDecision(3); }
    	switch (alt3)
    	{
    	case 1:
    		DebugEnterAlt(1);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:10: SLASHBF
    		{
    		DebugLocation(1, 10);
    		mSLASHBF(); 

    		}
    		break;
    	case 2:
    		DebugEnterAlt(2);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:18: SLASHBS
    		{
    		DebugLocation(1, 18);
    		mSLASHBS(); 

    		}
    		break;
    	case 3:
    		DebugEnterAlt(3);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:26: SLASHSTAR
    		{
    		DebugLocation(1, 26);
    		mSLASHSTAR(); 

    		}
    		break;
    	case 4:
    		DebugEnterAlt(4);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:36: COLON
    		{
    		DebugLocation(1, 36);
    		mCOLON(); 

    		}
    		break;
    	case 5:
    		DebugEnterAlt(5);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:42: IDENTIFIER
    		{
    		DebugLocation(1, 42);
    		mIDENTIFIER(); 

    		}
    		break;
    	case 6:
    		DebugEnterAlt(6);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:53: SLASH
    		{
    		DebugLocation(1, 53);
    		mSLASH(); 

    		}
    		break;
    	case 7:
    		DebugEnterAlt(7);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:59: WS
    		{
    		DebugLocation(1, 59);
    		mWS(); 

    		}
    		break;
    	case 8:
    		DebugEnterAlt(8);
    		// C:\\Sandbox\\StatsDirect\\StatsDirect3\\StatsDirectUI\\TextProcessing\\ActiveRtf.g:1:62: BUMF
    		{
    		DebugLocation(1, 62);
    		mBUMF(); 

    		}
    		break;

    	}

    }


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

 
	#endregion

}
