using System.Collections.Generic;
using StatsDirect.Templates;

namespace StatsDirect.Builtins
{
    public static class Registry
    {
        /// <summary>
        /// Returns a mapping of function names to their bodies.
        /// This is allowed to be slow as callers will cache it.
        /// </summary>
        public static ICollection<IBuiltin> GetFunctionRegistry()
        {
            List<IBuiltin> functionRegistry = new List<IBuiltin>
            {
                new Builtin("chartCompareSeveralContinuousVariables", ChartExplorer.CompareSeveralContinuousVariables, InputDuringStep.Always),
                new Builtin("chartExploreContinuousDistributions", ChartExplorer.ExploreContinuousDistributions, InputDuringStep.Always),
                new Builtin("calcSimpleLinearRegressionCI", Regress.CalcSimpleLinearRegressionCi),
                new Builtin("convertUnits", Sheet.ConvertUnits, InputDuringStep.Always),
                new Builtin("distBinomial", Distribution.DistBinomial, InputDuringStep.Always),
                new Builtin("distChiSquare", Distribution.DistChiSquare, InputDuringStep.Always),
                new Builtin("distF", Distribution.DistF, InputDuringStep.Always),
                new Builtin("distKendall", Distribution.DistKendall, InputDuringStep.Always),
                new Builtin("distNonCentralT", Distribution.DistNonCentralT, InputDuringStep.Always),
                new Builtin("distNormal", Distribution.DistNormal, InputDuringStep.Always),
                new Builtin("distPoisson", Distribution.DistPoisson, InputDuringStep.Always),
                new Builtin("distQ", Distribution.DistQ, InputDuringStep.Always),
                new Builtin("distSpearman", Distribution.DistSpearman, InputDuringStep.Always),
                new Builtin("distT", Distribution.DistT, InputDuringStep.Always),
                new Builtin("fileExportWorksheet", ImportExport.FileExportWorksheet),
                new Builtin("fileImportWorksheet", ImportExport.FileImportWorksheet),
                new Builtin("gridLogisticRegressionFit", Regress.GridLogisticRegressionFit),
                new Builtin("gridPoissonRegressionFit", Regress.GridPoissonRegressionFit),
                new Builtin("opPoissonRegressionIrrMakeDichotomousCovariates", Regress.OpPoissonRegressionIrrMakeDichotomousCovariates),
                new Builtin("plotLogisticRegressionDiagnostics", Regress.PlotLogisticRegressionDiagnostics),
                new Builtin("plotPredictionInterval", Regress.PlotPredictionInterval),
                new PureBuiltin("plotProbit", Regress.PlotProbit),
                new PureBuiltin("plotResidualsSimple", Regress.PlotResidualsSimple),
                new Builtin("plotSeCi", Regress.PlotSeCi),
                new Builtin("plotSimpleLinearRegression", Regress.PlotSimpleLinearRegression),
                new PureBuiltin("plotMultipleLinearRegressionResiduals", Regress.PlotMultipleLinearRegressionResiduals),
                new Builtin("ProbitOrLogitDataHasControls", Regress.ProbitOrLogitDataHasControls),
                new Builtin("quickSummary", Describe.QuickSummary),
                new Builtin("rptAbridgedLifetable", Survival.RptAbridgedLifetable),
                new Builtin("rptAgreement", Anova.RptAgreement),
                new Builtin("rptAreaUnderCurve", Regress.RptAreaUnderCurve),
                new PureBuiltin("rptBonferroni", Anova.RptBonferroni),
                new Builtin("rptChiGFSimulateExactP", Tables.RptChiGfSimulateExactP),
                new PureBuiltin("rptChiSquareGoodnessOfFit", Tables.RptChiSquareGoodnessOfFit),
                new Builtin("rptChi2by2", Chi.RptChi2By2, InputDuringStep.Sometimes),
                new PureBuiltin("rptChi2byNLinearTrend", Chi.RptChi2ByNLinearTrend),
                new PureBuiltin("rptChi2byNWithoutTrend", Chi.RptChi2ByNWithoutTrend),
                new PureBuiltin("rptChi2byNWithTrend", Chi.RptChi2ByNWithTrend),
                new Builtin("rptChi2byNWithTrendSimulateExactP", Chi.RptChi2ByNWithTrendSimulateExactP),
                new Builtin("rptChiMantel", Chi.RptChiMantel, InputDuringStep.Sometimes),
                new Builtin("rptChiRbyC", Chi.RptChiRbyC),
                new Builtin("rptChiWoolf", Chi.RptChiWoolf),
                new Builtin("rptChiWoolfWorksheet", Tables.RptChiWoolfWorksheet),
                new Builtin("rptCiMeanY", Regress.RptCiMeanY),
                new PureBuiltin("rptConditionalLogisticRegression", RegressRpt.RptConditionalLogisticRegression),
                new PureBuiltin("rptCoxBaselineToReport", Coxreg.RptCoxBaselineToReport),
                new PureBuiltin("rptCoxBaselineToWorksheet", Coxreg.RptCoxBaselineToWorksheet),
                new PureBuiltin("rptCoxHazardPlots", Coxreg.RptCoxHazardPlots),
                new Builtin("rptCoxHazardRatios", Coxreg.RptCoxHazardRatios),
                new Builtin("rptCoxModelAnalysis", Coxreg.RptCoxModelAnalysis),
                new Builtin("rptCoxRegression", Coxreg.RptCoxRegression),
                new PureBuiltin("rptCoxResiduals", Coxreg.RptCoxResiduals),
                new Builtin("rptCronbach", Regress.RptCronbach),
                new Builtin("rptCrossover", Anova.RptCrossover),
                new Builtin("rptCrosstabs", Tables.RptCrosstabs),
                new Builtin("rptCrosstabsPreprocess", Tables.RptCrosstabsPreprocess, InputDuringStep.Sometimes),
                new PureBuiltin("rptCuzick", Nonparametric.RptCuzick),
                new Builtin("rptDiversity", Nonparametric.RptDiversity),
                new PureBuiltin("rptDunnett", Anova.RptDunnett),
                new Builtin("rptEffect", Meta.RptEffect),
                new PureBuiltin("rptEqualityOfVariance", Anova.RptEqualityOfVariance),
                new PureBuiltin("rptExactFisher", Exact.RptExactFisher),
                new PureBuiltin("rptExactFisherX", Exact.RptExactFisherX),
                new Builtin("rptExactMcNamar", Exact.RptExactMcNamar),
                new Builtin("rptExactORCML", Exact.RptExactORCML),
                new PureBuiltin("rptExactSign", Exact.RptExactSign),
                new Builtin("rptFollowUpLifetable", Survival.RptFollowUpLifetable),
                new PureBuiltin("rptFollowUpLifetableCalculateNatst", Survival.RptFollowUpLifetableCalculateNatst),
                new Builtin("rptFrequency", Describe.RptFrequency),
                new PureBuiltin("rptFriedman", Nonparametric.RptFriedman),
                new Builtin("rptFriedmanSimulateExactP", Nonparametric.RptFriedmanSimulateExactP),
                new Builtin("rptFrMultiple", Nonparametric.RptFrMultiple),
                new Builtin("rptGini", Nonparametric.RptGini),
                new Builtin("rptGroupedCovariance", RegressRpt.RptGroupedCovariance, InputDuringStep.Always),
                new Builtin("rptGroupedLinearity", RegressRpt.RptGroupedLinearity),
                new PureBuiltin("rptGroupedOneWay", Anova.RptGroupedOneWay),
                new PureBuiltin("rptGroupedTwoWay", Anova.RptGroupedTwoWay),
                new Builtin("rptInterpolateXY", Regress.RptInterpolateXY),
                new Builtin("rptInterpolateYX", Regress.RptInterpolateYX),
                new Builtin("rptKaplanMeier", Survival.RptKaplan),
                new PureBuiltin("rptKaplanMeierPlots", Survival.RptKaplanMeierPlots),
                new Builtin("rptKappa", Tables.RptKappa),
                new Builtin("rptKappaScreen", Analysis.RptKappaScreen),
                new Builtin("rptKappaSimulateExactP", Tables.RptKappaSimulateExactP),
                new PureBuiltin("rptKappaSizeWeights", Tables.RptKappaSizeWeights),
                new Builtin("rptKendall", Nonparametric.RptKendall),
                new PureBuiltin("rptKruskal", Nonparametric.RptKruskal),
                new Builtin("rptKruskalSimulateExactP", Nonparametric.RptKruskalSimulateExactP),
                new Builtin("rptKwMultiple", Nonparametric.RptKwMultiple),
                new PureBuiltin("rptLatin", Anova.RptLatin),
                new Builtin("rptLinearizedEstimates", Regress.RptLinearizedEstimates),
                new Builtin("rptLinearizedEstimateInterpolation", Regress.RptLinearizedEstimateInterpolation),
                new PureBuiltin("rptLinearizedEstimatePlot", Regress.RptLinearizedEstimatePlot),
                new Builtin("rptLogisticRegression", Regress.RptLogisticRegression),
                new Builtin("rptLogisticRegressionBootstrap", Regress.RptLogisticRegressionBootstrap),
                new Builtin("rptLogisticRegressionClassification", Regress.RptLogisticRegressionClassification),
                new Builtin("rptLogisticRegressionFit", Regress.RptLogisticRegressionFit),
                new Builtin("rptLogisticRegressionModel", Regress.RptLogisticRegressionModel),
                new Builtin("rptLogisticRegressionModelSelection", Regress.RptLogisticRegressionModelSelection),
                new Builtin("rptLogisticRegressionPrediction", Regress.RptLogisticRegressionPrediction),
                new Builtin("rptLogit", Regress.RptLogit),
                new Builtin("rptLogRank", Survival.RptLogRank, InputDuringStep.Sometimes),
                new Builtin("rptMannWhitney", Nonparametric.RptMannWhitney),
                new Builtin("rptMantel", Meta.RptMantel),
                new Builtin("rptMetaCorrelation", Meta.RptMetaCorrelation),
                new Builtin("rptMetaIncidenceRateDifference", Meta.RptMetaIncidenceRateDifference),
                new Builtin("rptMetaIncidenceRateRatio", Meta.RptMetaIncidenceRateRatio),
                new Builtin("rptMetaSummary", Meta.RptMetaSummary),
                new Builtin("rptMiscDiagnostic", Analysis.RptMiscDiagnostic),
                new PureBuiltin("rptMiscFalseResult", Analysis.RptMiscFalseResult),
                new PureBuiltin("rptMiscLikely", Analysis.RptMiscLikely),
                new Builtin("rptMiscNumberNeededToTreat", Analysis.RptMiscNumberNeededToTreat),
                new PureBuiltin("rptMiscRelRisk", Analysis.RptMiscRelRisk),
                new Builtin("rptMiscRetroRisk", Analysis.RptMiscRetroRisk, InputDuringStep.Always),
                new Builtin("rptMultipleLinearRegression", Regress.RptMultipleLinearRegression),
                new Builtin("rptMultipleLinearRegressionAnova", Regress.RptMultipleLinearRegressionAnova),
                new Builtin("rptMultipleLinearRegressionBestSubset", Regress.RptMultipleLinearRegressionBestSubset, InputDuringStep.Always),
                new Builtin("rptMultipleLinearRegressionParameterDetail", Regress.RptMultipleLinearRegressionParameterDetail),
                new Builtin("rptMultipleLinearRegressionPrediction", Regress.RptMultipleLinearRegressionPrediction),
                new Builtin("rptMultipleLinearRegressionResiduals", Regress.RptMultipleLinearRegressionResiduals),
                new PureBuiltin("rptNestMeans", Anova.RptNestMeans),
                new Builtin("rptNewmanKeuls", Anova.RptNewmanKeuls),
                new Builtin("rptNpRegression", Nonparametric.RptNpRegression),
                new PureBuiltin("rptOneWay", Anova.RptOneWay),
                new Builtin("rptPetoMeta", Meta.RptPetoMeta),
                new Builtin("rptPoissonRegression", Regress.RptPoissonRegression),
                new PureBuiltin("rptPoissonConfidenceInterval", Parametric.RptPoissonConfidenceInterval),
                new Builtin("rptPoissonRegressionFit", Regress.RptPoissonRegressionFit),
                new Builtin("rptPoissonRegressionIrr", Regress.RptPoissonRegressionIrr),
                new Builtin("rptPoissonRegressionModel", Regress.RptPoissonRegressionModel),
                new PureBuiltin("rptPoissonRegressionResiduals", Regress.RptPoissonRegressionResiduals),
                new Builtin("rptPolynomialRegression", Regress.RptPolynomialRegression),
                new Builtin("rptPolynomialRegressionBackInterpolation", Regress.RptPolynomialRegressionBackInterpolation),
                new Builtin("rptPolynomialRegressionConfidence", Regress.RptPolynomialRegressionConfidence),
                new Builtin("rptPolynomialRegressionInterpolation", Regress.RptPolynomialRegressionInterpolation),
                new PureBuiltin("rptPolynomialRegressionPlot", Regress.RptPolynomialRegressionPlot),
                new Builtin("rptPreferences", Describe.RptPreferences),
                new Builtin("rptPrincipalComponentsRegressionCorrelation", Regress.RptPrincipalComponentsRegressionCorrelation, InputDuringStep.Sometimes),
                new Builtin("rptPrincipalComponentsRegressionCovariance", Regress.RptPrincipalComponentsRegressionCovariance, InputDuringStep.Sometimes),
                new Builtin("rptPrincipalComponentsRegressionCoefficients", Regress.RptPrincipalComponentsRegressionCoefficients),
                new Builtin("rptPrincipalComponentsRegressionMatrix", Regress.RptPrincipalComponentsRegressionMatrix),
                new Builtin("rptPrincipalComponentsRegressionScores", Regress.RptPrincipalComponentsRegressionScores),
                new Builtin("rptProbit", Regress.RptProbit),
                new Builtin("rptProbitInterpolateX", Regress.RptProbitInterpolateX),
                new Builtin("rptProbitInterpolateY", Regress.RptProbitInterpolateY),
                new Builtin("rptProbitMore", Regress.RptProbitMore),
                new Builtin("rptProportionMeta", Meta.RptProportionMeta),
                new PureBuiltin("rptPropPairs", Analysis.RptPropPairs),
                new PureBuiltin("rptPropSingle", Analysis.RptPropSingle),
                new Builtin("rptPropUnPaired", Analysis.RptPropUnPaired),
                new PureBuiltin("rptQuantile", Nonparametric.RptQuantile),
                new Builtin("rptRandomBlock", Formula.RptRandomBlock),
                new Builtin("rptRandomPairs", Formula.RptRandomPairs, InputDuringStep.Sometimes),
                new Builtin("rptRandomUnPaired", Formula.RptRandomUnPaired),
                new Builtin("rptRandomXY", Formula.RptRandomXY),
                new Builtin("rptRanv", Regress.RptRanv),
                new Builtin("rptRateCompareTwo", Analysis.RptRateCompareTwo),
                new Builtin("rptRateDirect", Rates.rptRateDirect),
                new PureBuiltin("rptRateDirectStd", Analysis.RptRateDirectStd),
                new PureBuiltin("rptRatePoissonCI", Exact.RptRatePoissonCI),
                new Builtin("rptRateSMR", Rates.RptRateSmr),
                new Builtin("rptReferenceRange", Parametric.RptReferenceRange),
                new Builtin("rptRelativeRiskMeta", Meta.RptRelativeRiskMeta),
                new Builtin("rptRiskDifferenceMeta", Meta.RptRiskDifferenceMeta),
                new Builtin("rptNormality", Parametric.RptNormality, InputDuringStep.Sometimes),
                new Builtin("rptSimpleLinearRegression", Regress.RptSimpleLinearRegression),
                new Builtin("rptSizeCorrelation", Formula.RptSizeCorrelation),
                new Builtin("rptSizeIndCase", Formula.RptSizeIndCase),
                new Builtin("rptSizeIndProp", Formula.RptSizeIndProp),
                new Builtin("rptSizeMatchCase", Formula.RptSizeMatchCase),
                new Builtin("rptSizeMatchProp", Formula.RptSizeMatchProp),
                new Builtin("rptSizePaired", Formula.RptSizePaired),
                new Builtin("rptSizePopSurvey", Formula.RptSizePopSurvey),
                new Builtin("rptSizeSurvival", Formula.RptSizeSurvival),
                new Builtin("rptSizeUnPaired", Formula.RptSizeUnPaired),
                new PureBuiltin("rptSpearman", Nonparametric.RptSpearman),
                new PureBuiltin("rptSmirnov", Nonparametric.RptSmirnov),
                new Builtin("rptScheffe", Anova.RptScheffe),
                new Builtin("rptSqRank", Nonparametric.RptSqRank),
                new Builtin("rptTimeSeriesSummary", Describe.RptTimeSeriesSummary),
                new Builtin("rptStdrr", Rates.RptStdrr),
                new PureBuiltin("rptTPaired", Parametric.RptTPaired),
                new PureBuiltin("rptTSingle", Parametric.RptTSingle),
                new PureBuiltin("rptTSingleSummary", Parametric.RptTSingleSummary),
                new PureBuiltin("rptTUnpaired", Parametric.RptTUnpaired),
                new PureBuiltin("rptTUnpairedSummary", Parametric.RptTUnpairedSummary),
                new Builtin("rptTukey", Anova.RptTukey),
                new PureBuiltin("rptTwoMulti", Anova.RptTwoMulti),
                new PureBuiltin("rptTwoNest", Anova.RptTwoNest),
                new PureBuiltin("rptTwoWay", Anova.RptTwoWay),
                new Builtin("rptUnivariateSummary", Describe.RptUnivariateSummary),
                new Builtin("rptUniversalAgreement", Agreement.RptUniversalAgreement),
                new Builtin("rptUniversalAgreementSimulateExactP", Agreement.RptUniversalAgreementSimulateExactP),
                new Builtin("rptUniversalRCompare", Agreement.RptUniversalRCompare),
                new Builtin("rptWeightedUnivariateSummary", Describe.RptWeightedUnivariateSummary),
                new Builtin("rptWeiLachin", Survival.RptWeiLachin),
                new Builtin("rptWilcoxon", Nonparametric.RptWilcoxon),
                new Builtin("rptXxi", Regress.RptXxi),
                new Builtin("rptChildGrowth", Sheet.RptChildGrowth),
                new Builtin("rptZSingle", Parametric.RptZSingle),
                new Builtin("rptZUnpaired", Parametric.RptZUnpaired),
                new Builtin("setAnalysisOptions", Options.SetAnalysisOptions, InputDuringStep.Always),
                new Builtin("showGraphicsOptions", Options.ShowGraphicsOptions, InputDuringStep.Always),
                new PureBuiltin("shtClearMissing", Sheet.ShtClearMissing),
                new PureBuiltin("shtCombine", Sheet.ShtCombine),
                new PureBuiltin("shtContract", Sheet.ShtContract),
                new PureBuiltin("shtConvertUnits", Sheet.ShtConvertUnits),
                new PureBuiltin("shtDates", Sheet.ShtDates),
                new PureBuiltin("shtDetabulate", Tables.ShtDetabulate),
                new Builtin("shtDummyVariables", Sheet.ShtDummyVariables),
                new Builtin("shtExpand", Sheet.ShtExpand),
                new PureBuiltin("shtFillSeries", Sheet.ShtFillSeries),
                new PureBuiltin("shtFindAndReplaceAdvanced", Sheet.ShtFindAndReplaceAdvanced),
                new Builtin("shtGroupCategorise", Sheet.ShtGroupCategorise),
                new Builtin("shtGroupExtract", Sheet.ShtGroupExtract),
                new PureBuiltin("shtGroupSplit", Sheet.ShtGroupSplit),
                new PureBuiltin("shtLadderPowers", Sheet.ShtLadderPowers),
                new PureBuiltin("shtNormal", Sheet.ShtNormal),
                new Builtin("shtPairDifferences", Sheet.ShtPairDifferences),
                new Builtin("shtPairMeans", Sheet.ShtPairMeans),
                new Builtin("shtPairSlopes", Sheet.ShtPairSlopes),
                new PureBuiltin("shtRank", Sheet.ShtRank),
                new PureBuiltin("shtRotate", Sheet.ShtRotate),
                new Builtin("shtRndBeta", Sheet.ShtRndBeta),
                new PureBuiltin("shtRndBinomial", Sheet.ShtRndBinomial),
                new Builtin("shtRndCauchy", Sheet.ShtRndCauchy),
                new Builtin("shtRndChiSquare", Sheet.ShtRndChiSquare),
                new Builtin("shtRndExponential", Sheet.ShtRndExponential),
                new Builtin("shtRndF", Sheet.ShtRndF),
                new Builtin("shtRndGamma", Sheet.ShtRndGamma),
                new Builtin("shtRndGeometric", Sheet.ShtRndGeometric),
                new Builtin("shtRndLogit", Sheet.ShtRndLogit),
                new Builtin("shtRndLogNormal", Sheet.ShtRndLogNormal),
                new Builtin("shtRndNegativeBinomial", Sheet.ShtRndNegativeBinomial),
                new PureBuiltin("shtRndNormal", Sheet.ShtRndNormal),
                new PureBuiltin("shtRndPoisson", Sheet.ShtRndPoisson),
                new Builtin("shtRndT", Sheet.ShtRndT),
                new PureBuiltin("shtRndUniform01", Sheet.ShtRndUniform01),
                new PureBuiltin("shtRndUniformAB", Sheet.ShtRndUniformAB),
                new Builtin("shtRndWeibull", Sheet.ShtRndWeibull),
                new PureBuiltin("shtSort", Sheet.ShtSort),
                new PureBuiltin("shtSortByExpression", Sheet.ShtSortByExpression),
                new Builtin("shtSortInPlace", Sheet.ShtSortInPlace, InputDuringStep.Always),
                new PureBuiltin("shtStandardize", Sheet.ShtStandardize),
                new PureBuiltin("shtTabulate", Tables.ShtTabulate),
                new Builtin("shtToggleFilters", Sheet.ShtToggleFilters),
                new PureBuiltin("shtTransformAngular", Sheet.ShtTransformAngular),
                new PureBuiltin("shtTransformCumulate", Sheet.ShtTransformCumulate),
                new PureBuiltin("shtTransformECDF", Sheet.ShtTransformECDF),
                new PureBuiltin("shtTransformLog", Sheet.ShtTransformLog),
                new PureBuiltin("shtTransformLog10", Sheet.ShtTransformLog10),
                new PureBuiltin("shtTransformLogit", Sheet.ShtTransformLogit),
                new PureBuiltin("shtTransformProbit", Sheet.ShtTransformProbit),
                new PureBuiltin("shtTransformZECDF", Sheet.ShtTransformZecdf),
                new PureBuiltin("shtTransformZSD", Sheet.ShtTransformZsd),
                new PureBuiltin("valuesToFrequencies", Sheet.ValuesToFrequencies)
            };
            return functionRegistry;
        }
    }
}
