using System.Collections.Generic;
using StatsDirect.Templates;

namespace StatsDirect.Builtins
{
    public class Registry
    {
        /// <summary>
        /// Returns a mapping of function names to their bodies.
        /// This is allowed to be slow as callers will cache it.
        /// </summary>
        public static ICollection<Builtin> GetFunctionRegistry()
        {
            List<Builtin> functionRegistry = new List<Builtin>
                                                 {
                                                     new Builtin("chartCompareSeveralContinuousVariables",
                                                                 ChartExplorer.CompareSeveralContinuousVariables,
                                                                 InputDuringStep.Always),
                                                     new Builtin("chartExploreContinuousDistributions",
                                                                 ChartExplorer.ExploreContinuousDistributions,
                                                                 InputDuringStep.Always),
                                                     new Builtin("calcSimpleLinearRegressionCI",
                                                                 Regress.CalcSimpleLinearRegressionCi,
                                                                 InputDuringStep.Never),
                                                     new Builtin("distBinomial", Distribution.DistBinomial,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distChiSquare", Distribution.DistChiSquare,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distF", Distribution.DistF, InputDuringStep.Always),
                                                     new Builtin("distKendall", Distribution.DistKendall,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distNonCentralT", Distribution.DistNonCentralT,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distNormal", Distribution.DistNormal,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distPoisson", Distribution.DistPoisson,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distQ", Distribution.DistQ, InputDuringStep.Always),
                                                     new Builtin("distSpearman", Distribution.DistSpearman,
                                                                 InputDuringStep.Always),
                                                     new Builtin("distT", Distribution.DistT, InputDuringStep.Always),
                                                     new Builtin("fileExportWorksheet", ImportExport.FileExportWorksheet,
                                                                 InputDuringStep.Never),
                                                     new Builtin("fileImportWorksheet", ImportExport.FileImportWorksheet,
                                                                 InputDuringStep.Never),
                                                     new Builtin("gridLogisticRegressionFit",
                                                                 Regress.GridLogisticRegressionFit, InputDuringStep.Never),
                                                     new Builtin("gridPoissonRegressionFit",
                                                                 Regress.GridPoissonRegressionFit, InputDuringStep.Never),
                                                     new Builtin("plotLogisticRegressionDiagnostics",
                                                                 Regress.PlotLogisticRegressionDiagnostics,
                                                                 InputDuringStep.Never),
                                                     new Builtin("plotPredictionInterval", Regress.PlotPredictionInterval,
                                                                 InputDuringStep.Never),
                                                     new Builtin("plotProbit", Regress.PlotProbit, InputDuringStep.Never),
                                                     new Builtin("plotResidualsSimple", Regress.PlotResidualsSimple,
                                                                 InputDuringStep.Never),
                                                     new Builtin("plotSeCi", Regress.PlotSeCi, InputDuringStep.Never),
                                                     new Builtin("plotSimpleLinearRegression",
                                                                 Regress.PlotSimpleLinearRegression, InputDuringStep.Never),
                                                     new Builtin("plotMultipleLinearRegressionResiduals",
                                                                 Regress.PlotMultipleLinearRegressionResiduals,
                                                                 InputDuringStep.Never),
                                                     new Builtin("ProbitOrLogitDataHasControls", Regress.ProbitOrLogitDataHasControls, InputDuringStep.Never),
                                                     new Builtin("quickSummary", Describe.QuickSummary,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptAbridgedLifetable", Survival.RptAbridgedLifetable,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptAgreement", Anova.RptAgreement, InputDuringStep.Never),
                                                     new Builtin("rptAreaUnderCurve", Regress.RptAreaUnderCurve,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptBonferroni", Anova.RptBonferroni,
                                                                 InputDuringStep.Always),
                                                     new Builtin("rptChiGFSimulateExactP", Tables.RptChiGfSimulateExactP,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptChiSquareGoodnessOfFit",
                                                                 Tables.RptChiSquareGoodnessOfFit, InputDuringStep.Never),
                                                     new Builtin("rptChi2by2", Chi.RptChi2By2, InputDuringStep.Sometimes),
                                                     new Builtin("rptChi2byNLinearTrend", Chi.RptChi2ByNLinearTrend,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptChi2byNWithoutTrend", Chi.RptChi2ByNWithoutTrend,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptChi2byNWithTrend", Chi.RptChi2ByNWithTrend,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptChi2byNWithTrendSimulateExactP",
                                                                 Chi.RptChi2ByNWithTrendSimulateExactP,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptChiMantel", Chi.RptChiMantel,
                                                                 InputDuringStep.Sometimes),
                                                     new Builtin("rptChiRbyC", Chi.RptChiRbyC, InputDuringStep.Never),
                                                     new Builtin("rptChiWoolf", Chi.RptChiWoolf, InputDuringStep.Never),
                                                     new Builtin("rptChiWoolfWorksheet", Tables.RptChiWoolfWorksheet,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCiMeanY", Regress.RptCiMeanY, InputDuringStep.Never),
                                                     new Builtin("rptConditionalLogisticRegression",
                                                                 RegressRpt.RptConditionalLogisticRegression,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCoxBaselineToReport", Coxreg.RptCoxBaselineToReport,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCoxBaselineToWorksheet",
                                                                 Coxreg.RptCoxBaselineToWorksheet, InputDuringStep.Never),
                                                     new Builtin("rptCoxHazardPlots", Coxreg.RptCoxHazardPlots,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCoxHazardRatios", Coxreg.RptCoxHazardRatios,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCoxModelAnalysis", Coxreg.RptCoxModelAnalysis,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCoxRegression", Coxreg.RptCoxRegression,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCoxResiduals", Coxreg.RptCoxResiduals,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptCronbach", Regress.RptCronbach, InputDuringStep.Never),
                                                     new Builtin("rptCrossover", Anova.RptCrossover, InputDuringStep.Never),
                                                     new Builtin("rptCrosstabs", Tables.RptCrosstabs, InputDuringStep.Never),
                                                     new Builtin("rptCrosstabsPreprocess", Tables.RptCrosstabsPreprocess, InputDuringStep.Sometimes),
                                                     new Builtin("rptCuzick", Nonparametric.RptCuzick, InputDuringStep.Sometimes),
                                                     new Builtin("rptDiversity", Nonparametric.RptDiversity, InputDuringStep.Never),
                                                     new Builtin("rptDunnett", Anova.RptDunnett, InputDuringStep.Never),
                                                     new Builtin("rptEffect", Meta.RptEffect, InputDuringStep.Never),
                                                     new Builtin("rptEqualityOfVariance", Anova.RptEqualityOfVariance, InputDuringStep.Never),
                                                     new Builtin("rptExactFisher", Exact.RptExactFisher, InputDuringStep.Never),
                                                     new Builtin("rptExactFisherX", Exact.RptExactFisherX,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptExactMcNamar", Exact.RptExactMcNamar,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptExactORCML", Exact.RptExactORCML,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptExactSign", Exact.RptExactSign, InputDuringStep.Never),
                                                     new Builtin("rptFollowUpLifetable", Survival.RptFollowUpLifetable,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptFollowUpLifetableCalculateNatst", Survival.RptFollowUpLifetableCalculateNatst,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptFrequency", Describe.RptFrequency,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptFriedman", Nonparametric.RptFriedman,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptFriedmanSimulateExactP",
                                                                 Nonparametric.RptFriedmanSimulateExactP,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptFrMultiple", Nonparametric.RptFrMultiple,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptGini", Nonparametric.RptGini, InputDuringStep.Never),
                                                     new Builtin("rptGroupedCovariance", RegressRpt.rptGroupedCovariance,
                                                                 InputDuringStep.Always),
                                                     new Builtin("rptGroupedLinearity", RegressRpt.rptGroupedLinearity,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptGroupedOneWay", Anova.RptGroupedOneWay,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptGroupedTwoWay", Anova.RptGroupedTwoWay,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptInterpolateXY", Regress.RptInterpolateXY,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptInterpolateYX", Regress.RptInterpolateYX,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKaplanMeier", Survival.RptKaplan,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKaplanMeierPlots", Survival.RptKaplanMeierPlots,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKappa", Tables.RptKappa, InputDuringStep.Never),
                                                     new Builtin("rptKappaScreen", Analysis.RptKappaScreen,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKappaSimulateExactP", Tables.RptKappaSimulateExactP,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKappaSizeWeights", Tables.RptKappaSizeWeights,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKendall", Nonparametric.RptKendall,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKruskal", Nonparametric.RptKruskal,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKruskalSimulateExactP",
                                                                 Nonparametric.RptKruskalSimulateExactP,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptKwMultiple", Nonparametric.RptKwMultiple,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLatin", Anova.RptLatin, InputDuringStep.Never),
                                                     new Builtin("rptLinearizedEstimates", Regress.RptLinearizedEstimates,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLinearizedEstimateInterpolation",
                                                                 Regress.RptLinearizedEstimateInterpolation,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLinearizedEstimatePlot",
                                                                 Regress.RptLinearizedEstimatePlot, InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegression", Regress.RptLogisticRegression,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegressionBootstrap",
                                                                 Regress.RptLogisticRegressionBootstrap,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegressionClassification",
                                                                 Regress.RptLogisticRegressionClassification,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegressionFit",
                                                                 Regress.RptLogisticRegressionFit, InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegressionModel",
                                                                 Regress.RptLogisticRegressionModel, InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegressionOdds",
                                                                 Regress.RptLogisticRegressionOdds, InputDuringStep.Never),
                                                     new Builtin("rptLogisticRegressionPrediction",
                                                                 Regress.RptLogisticRegressionPrediction,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptLogit", Regress.RptLogit, InputDuringStep.Never),
                                                     new Builtin("rptLogRank", Survival.RptLogRank,
                                                                 InputDuringStep.Sometimes),
                                                     new Builtin("rptMannWhitney", Nonparametric.RptMannWhitney,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMantel", Meta.RptMantel, InputDuringStep.Never),
                                                     new Builtin("rptMetaCorrelation", Meta.RptMetaCorrelation,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMetaIncidenceRateDifference",
                                                                 Meta.RptMetaIncidenceRateDifference, InputDuringStep.Never),
                                                     new Builtin("rptMetaIncidenceRateRatio",
                                                                 Meta.RptMetaIncidenceRateRatio, InputDuringStep.Never),
                                                     new Builtin("rptMetaSummary", Meta.RptMetaSummary,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMiscDiagnostic", Analysis.RptMiscDiagnostic,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMiscFalseResult", Analysis.RptMiscFalseResult,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMiscLikely", Analysis.RptMiscLikely,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMiscNumberNeededToTreat",
                                                                 Analysis.RptMiscNumberNeededToTreat, InputDuringStep.Never),
                                                     new Builtin("rptMiscRelRisk", Analysis.RptMiscRelRisk,
                                                                 InputDuringStep.Always),
                                                     new Builtin("rptMiscRetroRisk", Analysis.RptMiscRetroRisk,
                                                                 InputDuringStep.Always),
                                                     new Builtin("rptMultipleLinearRegression",
                                                                 Regress.RptMultipleLinearRegression, InputDuringStep.Never),
                                                     new Builtin("rptMultipleLinearRegressionAnova",
                                                                 Regress.RptMultipleLinearRegressionAnova,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMultipleLinearRegressionBestSubset",
                                                                 Regress.RptMultipleLinearRegressionBestSubset,
                                                                 InputDuringStep.Always),
                                                     new Builtin("rptMultipleLinearRegressionParameterDetail",
                                                                 Regress.RptMultipleLinearRegressionParameterDetail,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMultipleLinearRegressionPrediction",
                                                                 Regress.RptMultipleLinearRegressionPrediction,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptMultipleLinearRegressionResiduals",
                                                                 Regress.RptMultipleLinearRegressionResiduals,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptNestMeans", Anova.RptNestMeans, InputDuringStep.Never),
                                                     new Builtin("rptNewmanKeuls", Anova.RptNewmanKeuls,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptNpRegression", Nonparametric.RptNpRegression,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptOneWay", Anova.RptOneWay, InputDuringStep.Never),
                                                     new Builtin("rptPetoMeta", Meta.RptPetoMeta, InputDuringStep.Never),
                                                     new Builtin("rptPoissonRegression", Regress.RptPoissonRegression,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPoissonConfidenceInterval",
                                                                 Parametric.rptPoissonConfidenceInterval,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPoissonRegressionFit", Regress.RptPoissonRegressionFit,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPoissonRegressionIRR", Regress.RptPoissonRegressionIrr,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPoissonRegressionModel",
                                                                 Regress.RptPoissonRegressionModel, InputDuringStep.Never),
                                                     new Builtin("rptPoissonRegressionResiduals",
                                                                 Regress.RptPoissonRegressionResiduals,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPolynomialRegression", Regress.RptPolynomialRegression,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPolynomialRegressionBackInterpolation",
                                                                 Regress.RptPolynomialRegressionBackInterpolation,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPolynomialRegressionConfidence",
                                                                 Regress.RptPolynomialRegressionConfidence,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPolynomialRegressionInterpolation",
                                                                 Regress.RptPolynomialRegressionInterpolation,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPolynomialRegressionPlot",
                                                                 Regress.RptPolynomialRegressionPlot, InputDuringStep.Never),
                                                     new Builtin("rptPreferences", Describe.RptPreferences,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPrincipalComponentsRegressionCorrelation",
                                                                 Regress.RptPrincipalComponentsRegressionCorrelation,
                                                                 InputDuringStep.Sometimes),
                                                     new Builtin("rptPrincipalComponentsRegressionCovariance",
                                                                 Regress.RptPrincipalComponentsRegressionCovariance,
                                                                 InputDuringStep.Sometimes),
                                                     new Builtin("rptPrincipalComponentsRegressionCoefficients",
                                                                 Regress.RptPrincipalComponentsRegressionCoefficients,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPrincipalComponentsRegressionMatrix",
                                                                 Regress.RptPrincipalComponentsRegressionMatrix,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPrincipalComponentsRegressionScores",
                                                                 Regress.RptPrincipalComponentsRegressionScores,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptProbit", Regress.RptProbit, InputDuringStep.Never),
                                                     new Builtin("rptProbitInterpolateX", Regress.RptProbitInterpolateX,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptProbitInterpolateY", Regress.RptProbitInterpolateY,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptProbitMore", Regress.RptProbitMore,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptProportionMeta", Meta.RptProportionMeta,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPropPairs", Analysis.RptPropPairs,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPropSingle", Analysis.RptPropSingle,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptPropUnPaired", Analysis.RptPropUnPaired,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptQuantile", Nonparametric.RptQuantile,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRandomBlock", Formula.RptRandomBlock,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRandomPairs", Formula.RptRandomPairs,
                                                                 InputDuringStep.Sometimes),
                                                     new Builtin("rptRandomUnPaired", Formula.RptRandomUnPaired,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRandomXY", Formula.RptRandomXY, InputDuringStep.Never),
                                                     new Builtin("rptRanv", Regress.RptRanv, InputDuringStep.Never),
                                                     new Builtin("rptRateCompareTwo", Analysis.RptRateCompareTwo,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRateDirect", Rates.rptRateDirect,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRateDirectStd", Analysis.RptRateDirectStd,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRatePoissonCI", Exact.RptRatePoissonCI,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRateSMR", Rates.RptRateSmr, InputDuringStep.Never),
                                                     new Builtin("rptReferenceRange", Parametric.RptReferenceRange,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRelativeRiskMeta", Meta.RptRelativeRiskMeta,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptRiskDifferenceMeta", Meta.RptRiskDifferenceMeta,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptNormality", Parametric.RptNormality,
                                                                 InputDuringStep.Sometimes),
                                                     new Builtin("rptSimpleLinearRegression",
                                                                 Regress.RptSimpleLinearRegression, InputDuringStep.Never),
                                                     new Builtin("rptSizeCorrelation", Formula.RptSizeCorrelation,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizeIndCase", Formula.RptSizeIndCase,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizeIndProp", Formula.RptSizeIndProp,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizeMatchCase", Formula.RptSizeMatchCase,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizeMatchProp", Formula.RptSizeMatchProp,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizePaired", Formula.RptSizePaired,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizePopSurvey", Formula.RptSizePopSurvey,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizeSurvival", Formula.RptSizeSurvival,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSizeUnPaired", Formula.RptSizeUnPaired,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSpearman", Nonparametric.RptSpearman,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptSmirnov", Nonparametric.RptSmirnov,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptScheffe", Anova.RptScheffe, InputDuringStep.Never),
                                                     new Builtin("rptSqRank", Nonparametric.RptSqRank,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptStdrr", Rates.RptStdrr, InputDuringStep.Never),
                                                     new Builtin("rptTPaired", Parametric.RptTPaired, InputDuringStep.Never),
                                                     new Builtin("rptTSingle", Parametric.RptTSingle, InputDuringStep.Never),
                                                     new Builtin("rptTSingleSummary", Parametric.RptTSingleSummary,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptTUnpaired", Parametric.RptTUnpaired,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptTUnpairedSummary", Parametric.rptTUnpairedSummary,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptTukey", Anova.RptTukey, InputDuringStep.Never),
                                                     new Builtin("rptTwoMulti", Anova.RptTwoMulti, InputDuringStep.Never),
                                                     new Builtin("rptTwoNest", Anova.RptTwoNest, InputDuringStep.Never),
                                                     new Builtin("rptTwoWay", Anova.RptTwoWay, InputDuringStep.Never),
                                                     new Builtin("rptUnivariateSummary", Describe.RptUnivariateSummary,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptUniversalAgreement", Agreement.RptUniversalAgreement,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptUniversalAgreementSimulateExactP",
                                                                 Agreement.RptUniversalAgreementSimulateExactP,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptUniversalRCompare", Agreement.RptUniversalRCompare,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptWeightedUnivariateSummary",
                                                                 Describe.RptWeightedUnivariateSummary,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptWeiLachin", Survival.RptWeiLachin,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptWilcoxon", Nonparametric.RptWilcoxon,
                                                                 InputDuringStep.Never),
                                                     new Builtin("rptXxi", Regress.RptXxi, InputDuringStep.Never),
                                                     new Builtin("rptZSingle", Parametric.RptZSingle, InputDuringStep.Never),
                                                     new Builtin("rptZUnpaired", Parametric.RptZUnpaired,
                                                                 InputDuringStep.Never),
                                                     new Builtin("setAnalysisOptions", Options.SetAnalysisOptions,
                                                                 InputDuringStep.Always),
                                                     new Builtin("showGraphicsOptions", Options.ShowGraphicsOptions,
                                                                 InputDuringStep.Always),
                                                     new Builtin("shtClearMissing", Sheet.ShtClearMissing,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtCombine", Sheet.ShtCombine, InputDuringStep.Never),
                                                     new Builtin("shtConvertUnits", Sheet.ShtConvertUnits, InputDuringStep.Never),
                                                     new Builtin("shtDates", Sheet.ShtDates, InputDuringStep.Never),
                                                     new Builtin("shtDetabulate", Tables.ShtDetabulate,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtDummyVariables", Sheet.ShtDummyVariables,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtFillSeries", Sheet.ShtFillSeries,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtGroupCategorise", Sheet.shtGroupCategorise, InputDuringStep.Never),
                                                     new Builtin("shtGroupExtract", Sheet.shtGroupExtract, InputDuringStep.Never),
                                                     new Builtin("shtGroupSplit", Sheet.shtGroupSplit,
                                                                 InputDuringStep.Always),
                                                     new Builtin("shtLadderPowers", Sheet.ShtLadderPowers,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtNormal", Sheet.ShtNormal, InputDuringStep.Never),
                                                     new Builtin("shtPairDifferences", Sheet.ShtPairDifferences,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtPairMeans", Sheet.ShtPairMeans, InputDuringStep.Never),
                                                     new Builtin("shtPairSlopes", Sheet.ShtPairSlopes,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRank", Sheet.ShtRank, InputDuringStep.Never),
                                                     new Builtin("shtRotate", Sheet.shtRotate, InputDuringStep.Never),
                                                     new Builtin("shtRndBeta", Sheet.shtRndBeta, InputDuringStep.Never),
                                                     new Builtin("shtRndBinomial", Sheet.shtRndBinomial,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndCauchy", Sheet.shtRndCauchy, InputDuringStep.Never),
                                                     new Builtin("shtRndChiSquare", Sheet.shtRndChiSquare,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndExponential", Sheet.shtRndExponential,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndF", Sheet.shtRndF, InputDuringStep.Never),
                                                     new Builtin("shtRndGamma", Sheet.shtRndGamma, InputDuringStep.Never),
                                                     new Builtin("shtRndGeometric", Sheet.shtRndGeometric,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndLogit", Sheet.shtRndLogit, InputDuringStep.Never),
                                                     new Builtin("shtRndLogNormal", Sheet.shtRndLogNormal,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndNegativeBinomial", Sheet.shtRndNegativeBinomial,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndNormal", Sheet.shtRndNormal, InputDuringStep.Never),
                                                     new Builtin("shtRndPoisson", Sheet.shtRndPoisson,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndT", Sheet.shtRndT, InputDuringStep.Never),
                                                     new Builtin("shtRndUniform01", Sheet.shtRndUniform01,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndUniformAB", Sheet.shtRndUniformAB,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtRndWeibull", Sheet.shtRndWeibull,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtSort", Sheet.ShtSort, InputDuringStep.Never),
                                                     new Builtin("shtSortByExpression", Sheet.ShtSortByExpression, InputDuringStep.Never),
                                                     new Builtin("shtSortInPlace", Sheet.ShtSortInPlace,
                                                                 InputDuringStep.Always),
                                                     new Builtin("shtStandardize", Sheet.ShtStandardize,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTabulate", Tables.ShtTabulate, InputDuringStep.Never),
                                                     new Builtin("shtTransformAngular", Sheet.ShtTransformAngular,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformCumulate", Sheet.ShtTransformCumulate,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformECDF", Sheet.ShtTransformECDF,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformLog", Sheet.ShtTransformLog,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformLog10", Sheet.ShtTransformLog10,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformLogit", Sheet.ShtTransformLogit,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformProbit", Sheet.ShtTransformProbit,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformZECDF", Sheet.ShtTransformZecdf,
                                                                 InputDuringStep.Never),
                                                     new Builtin("shtTransformZSD", Sheet.ShtTransformZsd,
                                                                 InputDuringStep.Never)
                                                 };
            return functionRegistry;
        }
    }
}
