using System.Collections.Generic;
using StatsDirect.Charting;
using StatsDirect.Templates;

namespace StatsDirect.Builtins
{
    public class Registry
    {
        private Agreement Agreement { get; }
        private Analysis Analysis { get; }
        private Anova Anova { get; }
        private ChartExplorer ChartExplorer { get; }
        private Chi Chi { get; }
        private Describe Describe { get; }
        private Distribution Distribution { get; }
        private Exact Exact { get; }
        private ImportExport ImportExport { get; }
        private Meta Meta { get; }
        private Nonparametric Nonparametric { get; }
        private Options Options { get; }
        private Parametric Parametric { get; }
        private Regress Regress { get; }
        private Sheet Sheet { get; }
        private Survival Survival { get; }
        private Tables Tables { get; }

        public Registry(IChartPreferences chartPreferences, IChartRendererFactory chartRendererFactory, IProgressBarHost progressBarHost, ISdPreferences sdPreferences, IUserInterface userInterface)
        {
            Agreement = new(progressBarHost);
            Analysis = new(progressBarHost, sdPreferences, userInterface);
            Anova = new(progressBarHost);
            ChartExplorer = new(userInterface);
            Describe = new(chartPreferences, progressBarHost, sdPreferences, userInterface);
            Distribution = new(userInterface);
            Exact = new(progressBarHost);
            ImportExport = new(progressBarHost, sdApplication);
            Nonparametric = new(progressBarHost, sdPreferences, userInterface);
            Options = new(sdPreferences, uiPreferences, userInterface);
            Parametric = new(sdPreferences);
            Regress = new(progressBarHost, sdPreferences);
            Sheet = new(sdPreferences, userInterface);
            Survival = new(progressBarHost, sdPreferences);

            Meta = new(Anova, chartPreferences, chartRendererFactory, progressBarHost, sdPreferences);
            Chi = new(chartRendererFactory, progressBarHost, sdPreferences, Meta);
            Tables = new(Chi, chartRendererFactory, progressBarHost, sdPreferences, userInterface, Meta);
        }

        /// <summary>
        /// Returns a mapping of function names to their bodies.
        /// This is allowed to be slow as callers will cache it.
        /// </summary>
        public ICollection<IBuiltin> GetFunctionRegistry()
        {
            List<IBuiltin> functionRegistry = new()
            {
                new Builtin("chartCompareSeveralContinuousVariables", (parameters) => ChartExplorer.CompareSeveralContinuousVariables(parameters)),
                new Builtin("chartExploreContinuousDistributions", (parameters) => ChartExplorer.ExploreContinuousDistributions(parameters)),
                new Builtin("calcSimpleLinearRegressionCI", Regress.CalcSimpleLinearRegressionCi),
                new Builtin("convertUnits", (parameters) => Sheet.ConvertUnits(parameters)),
                new Builtin("distBinomial", (parameters) => Distribution.DistBinomial(parameters)),
                new Builtin("distChiSquare", (parameters) => Distribution.DistChiSquare(parameters)),
                new Builtin("distF", (parameters) => Distribution.DistF(parameters)),
                new Builtin("distKendall", (parameters) => Distribution.DistKendall(parameters)),
                new Builtin("distNonCentralT", (parameters) => Distribution.DistNonCentralT(parameters)),
                new Builtin("distNormal", (parameters) => Distribution.DistNormal(parameters)),
                new Builtin("distPoisson", (parameters) => Distribution.DistPoisson(parameters)),
                new Builtin("distQ", (parameters) => Distribution.DistQ(parameters)),
                new Builtin("distSpearman", (parameters) => Distribution.DistSpearman(parameters)),
                new Builtin("distT", (parameters) => Distribution.DistT(parameters)),
                new Builtin("fileExportWorksheet", (parameters) => ImportExport.FileExportWorksheet(parameters)),
                new Builtin("fileImportWorksheet", (parameters) => ImportExport.FileImportWorksheet(parameters)),
                new Builtin("gridLogisticRegressionFit", Regress.GridLogisticRegressionFit),
                new Builtin("gridPoissonRegressionFit", Regress.GridPoissonRegressionFit),
                new Builtin("opPoissonRegressionIrrMakeDichotomousCovariates", Regress.OpPoissonRegressionIrrMakeDichotomousCovariates),
                new Builtin("plotLogisticRegressionDiagnostics", Regress.PlotLogisticRegressionDiagnostics),
                new Builtin("plotPredictionInterval", Regress.PlotPredictionInterval),
                new Builtin("plotProbit", Regress.PlotProbit),
                new Builtin("plotResidualsSimple", Regress.PlotResidualsSimple),
                new Builtin("plotSeCi", Regress.PlotSeCi),
                new Builtin("plotSimpleLinearRegression", Regress.PlotSimpleLinearRegression),
                new Builtin("plotMultipleLinearRegressionResiduals", Regress.PlotMultipleLinearRegressionResiduals),
                new Builtin("ProbitOrLogitDataHasControls", Regress.ProbitOrLogitDataHasControls),
                new Builtin("quickSummary", (parameters) => Describe.QuickSummary(parameters)),
                new Builtin("rptAbridgedLifetable", (parameters) => Survival.RptAbridgedLifetable(parameters)),
                new Builtin("rptAgreement", (parameters) => Anova.RptAgreement(parameters)),
                new Builtin("rptAreaUnderCurve", (parameters) => Regress.RptAreaUnderCurve(parameters)),
                new Builtin("rptBonferroni", Anova.RptBonferroni),
                new Builtin("rptChiGFSimulateExactP", Tables.RptChiGfSimulateExactP),
                new Builtin("rptChiSquareGoodnessOfFit", Tables.RptChiSquareGoodnessOfFit),
                new Builtin("rptChi2by2", (parameters) => Chi.RptChi2By2(parameters)),
                new Builtin("rptChi2byNLinearTrend", Chi.RptChi2ByNLinearTrend),
                new Builtin("rptChi2byNWithoutTrend", Chi.RptChi2ByNWithoutTrend),
                new Builtin("rptChi2byNWithTrend", Chi.RptChi2ByNWithTrend),
                new Builtin("rptChi2byNWithTrendSimulateExactP", (parameters) => Chi.RptChi2ByNWithTrendSimulateExactP(parameters)),
                new Builtin("rptChiMantel", (parameters) => Chi.RptChiMantel(parameters)),
                new Builtin("rptChiRbyC", (parameters) => Chi.RptChiRbyC(parameters)),
                new Builtin("rptChiWoolf", Chi.RptChiWoolf),
                new Builtin("rptChiWoolfWorksheet", Tables.RptChiWoolfWorksheet),
                new Builtin("rptCiMeanY", Regress.RptCiMeanY),
                new Builtin("rptConditionalLogisticRegression", RegressRpt.RptConditionalLogisticRegression),
                new Builtin("rptCoxBaselineToReport", CoxRegression.RptCoxBaselineToReport),
                new Builtin("rptCoxBaselineToWorksheet", CoxRegression.RptCoxBaselineToWorksheet),
                new Builtin("rptCoxHazardPlots", CoxRegression.RptCoxHazardPlots),
                new Builtin("rptCoxHazardRatios", CoxRegression.RptCoxHazardRatios),
                new Builtin("rptCoxModelAnalysis", CoxRegression.RptCoxModelAnalysis),
                new Builtin("rptCoxRegression", CoxRegression.RptCoxRegression),
                new Builtin("rptCoxRegressionPreprocess", CoxRegression.RptCoxRegressionPreprocess),
                new Builtin("rptCoxResiduals", CoxRegression.RptCoxResiduals),
                new Builtin("rptCronbach", Regress.RptCronbach),
                new Builtin("rptCrossover", Anova.RptCrossover),
                new Builtin("rptCrosstabs", Tables.RptCrosstabs),
                new Builtin("rptCrosstabsPreprocess", (parameters) => Tables.RptCrosstabsPreprocess(parameters)),
                new Builtin("rptCuzick", Nonparametric.RptCuzick),
                new Builtin("rptDiversity", (parameters) => Nonparametric.RptDiversity(parameters)),
                new Builtin("rptDunnett", Anova.RptDunnett),
                new Builtin("rptEffect", (parameters) => Meta.RptEffect(parameters)),
                new Builtin("rptEqualityOfVariance", Anova.RptEqualityOfVariance),
                new Builtin("rptExactFisher", Exact.RptExactFisher),
                new Builtin("rptExactFisherX", Exact.RptExactFisherX),
                new Builtin("rptExactMcNamar", Exact.RptExactMcNamar),
                new Builtin("rptExactORCML", (parameters) => Exact.RptExactORCML(parameters)),
                new Builtin("rptExactSign", Exact.RptExactSign),
                new Builtin("rptFollowUpLifetable", Survival.RptFollowUpLifetable),
                new Builtin("rptFollowUpLifetableCalculateNatst", Survival.RptFollowUpLifetableCalculateNatst),
                new Builtin("rptFrequency", Describe.RptFrequency),
                new Builtin("rptFriedman", Nonparametric.RptFriedman),
                new Builtin("rptFriedmanSimulateExactP", (parameters) => Nonparametric.RptFriedmanSimulateExactP(parameters)),
                new Builtin("rptFrMultiple", Nonparametric.RptFrMultiple),
                new Builtin("rptGini", (parameters) => Nonparametric.RptGini(parameters)),
                new Builtin("rptGroupedCovariance", RegressRpt.RptGroupedCovariance),
                new Builtin("rptGroupedCovariancePreprocess", RegressRpt.RptGroupedCovariancePreprocess),
                new Builtin("rptGroupedLinearity", RegressRpt.RptGroupedLinearity),
                new Builtin("rptGroupedOneWay", Anova.RptGroupedOneWay),
                new Builtin("rptGroupedTwoWay", Anova.RptGroupedTwoWay),
                new Builtin("rptInterpolateXY", Regress.RptInterpolateXY),
                new Builtin("rptInterpolateYX", Regress.RptInterpolateYX),
                new Builtin("rptKaplanMeier", (parameters) => Survival.RptKaplan(parameters)),
                new Builtin("rptKaplanMeierPlots", Survival.RptKaplanMeierPlots),
                new Builtin("rptKappa", (parameters) => Tables.RptKappa(parameters)),
                new Builtin("rptKappaScreen", (parameters) => Analysis.RptKappaScreen(parameters)),
                new Builtin("rptKappaSimulateExactP", (parameters) => Tables.RptKappaSimulateExactP(parameters)),
                new Builtin("rptKappaSizeWeights", Tables.RptKappaSizeWeights),
                new Builtin("rptKendall", (parameters) => Nonparametric.RptKendall(parameters)),
                new Builtin("rptKruskal", Nonparametric.RptKruskal),
                new Builtin("rptKruskalSimulateExactP", (parameters) => Nonparametric.RptKruskalSimulateExactP(parameters)),
                new Builtin("rptKwMultiple", Nonparametric.RptKwMultiple),
                new Builtin("rptLatin", Anova.RptLatin),
                new Builtin("rptLinearizedEstimates", Regress.RptLinearizedEstimates),
                new Builtin("rptLinearizedEstimateInterpolation", Regress.RptLinearizedEstimateInterpolation),
                new Builtin("rptLinearizedEstimatePlot", Regress.RptLinearizedEstimatePlot),
                new Builtin("rptLogisticRegression", (parameters) => Regress.RptLogisticRegression(parameters)),
                new Builtin("rptLogisticRegressionBootstrap", (parameters) => Regress.RptLogisticRegressionBootstrap(parameters)),
                new Builtin("rptLogisticRegressionClassification", Regress.RptLogisticRegressionClassification),
                new Builtin("rptLogisticRegressionFit", Regress.RptLogisticRegressionFit),
                new Builtin("rptLogisticRegressionModel", Regress.RptLogisticRegressionModel),
                new Builtin("rptLogisticRegressionModelSelection", Regress.RptLogisticRegressionModelSelection),
                new Builtin("rptLogisticRegressionPrediction", Regress.RptLogisticRegressionPrediction),
                new Builtin("rptLogit", Regress.RptLogit),
                new Builtin("rptLogRank", (parameters) => Survival.RptLogRank(parameters)),
                new Builtin("rptLogRankPreprocess", Survival.RptLogRankPreprocess),
                new Builtin("rptMannWhitney", (parameters) => Nonparametric.RptMannWhitney(parameters)),
                new Builtin("rptMantel", Meta.RptMantel),
                new Builtin("rptMetaCorrelation", (parameters) => Meta.RptMetaCorrelation(parameters)),
                new Builtin("rptMetaIncidenceRateDifference", (parameters) => Meta.RptMetaIncidenceRateDifference(parameters)),
                new Builtin("rptMetaIncidenceRateRatio", (parameters) => Meta.RptMetaIncidenceRateRatio(parameters)),
                new Builtin("rptMetaSummary", (parameters) => Meta.RptMetaSummary(parameters)),
                new Builtin("rptMiscDiagnostic", (parameters) => Analysis.RptMiscDiagnostic(parameters)),
                new Builtin("rptMiscFalseResult", Analysis.RptMiscFalseResult),
                new Builtin("rptMiscLikely", Analysis.RptMiscLikely),
                new Builtin("rptMiscNumberNeededToTreat", Analysis.RptMiscNumberNeededToTreat),
                new Builtin("rptMiscRelRisk", Analysis.RptMiscRelRisk),
                new Builtin("rptMiscRetroRisk", (parameters) => Analysis.RptMiscRetroRisk(parameters)),
                new Builtin("rptMultipleLinearRegression", Regress.RptMultipleLinearRegression),
                new Builtin("rptMultipleLinearRegressionAnova", (parameters) => Regress.RptMultipleLinearRegressionAnova(parameters)),
                new Builtin("rptMultipleLinearRegressionBestSubset", Regress.RptMultipleLinearRegressionBestSubset),
                new Builtin("rptMultipleLinearRegressionParameterDetail", Regress.RptMultipleLinearRegressionParameterDetail),
                new Builtin("rptMultipleLinearRegressionPrediction", Regress.RptMultipleLinearRegressionPrediction),
                new Builtin("rptMultipleLinearRegressionResiduals", Regress.RptMultipleLinearRegressionResiduals),
                new Builtin("rptNestMeans", Anova.RptNestMeans),
                new Builtin("rptNewmanKeuls", Anova.RptNewmanKeuls),
                new Builtin("rptNpRegression", (parameters) => Nonparametric.RptNpRegression(parameters)),
                new Builtin("rptOneWay", Anova.RptOneWay),
                new Builtin("rptPetoMeta", Meta.RptPetoMeta),
                new Builtin("rptPoissonRegression", (parameters) => Regress.RptPoissonRegression(parameters)),
                new Builtin("rptPoissonConfidenceInterval", Parametric.RptPoissonConfidenceInterval),
                new Builtin("rptPoissonRegressionFit", Regress.RptPoissonRegressionFit),
                new Builtin("rptPoissonRegressionIrr", Regress.RptPoissonRegressionIrr),
                new Builtin("rptPoissonRegressionModel", Regress.RptPoissonRegressionModel),
                new Builtin("rptPoissonRegressionResiduals", Regress.RptPoissonRegressionResiduals),
                new Builtin("rptPolynomialRegression", Regress.RptPolynomialRegression),
                new Builtin("rptPolynomialRegressionBackInterpolation", (parameters) => Regress.RptPolynomialRegressionBackInterpolation(parameters)),
                new Builtin("rptPolynomialRegressionConfidence", Regress.RptPolynomialRegressionConfidence),
                new Builtin("rptPolynomialRegressionInterpolation", Regress.RptPolynomialRegressionInterpolation),
                new Builtin("rptPolynomialRegressionPlot", Regress.RptPolynomialRegressionPlot),
                new Builtin("rptPreferences", Describe.RptPreferences),
                new Builtin("rptPrincipalComponentsRegressionCorrelation", Regress.RptPrincipalComponentsRegressionCorrelation),
                new Builtin("rptPrincipalComponentsRegressionCovariance", Regress.RptPrincipalComponentsRegressionCovariance),
                new Builtin("rptPrincipalComponentsRegressionCoefficients", Regress.RptPrincipalComponentsRegressionCoefficients),
                new Builtin("rptPrincipalComponentsRegressionMatrix", Regress.RptPrincipalComponentsRegressionMatrix),
                new Builtin("rptPrincipalComponentsRegressionScores", Regress.RptPrincipalComponentsRegressionScores),
                new Builtin("rptProbit", Regress.RptProbit),
                new Builtin("rptProbitInterpolateX", Regress.RptProbitInterpolateX),
                new Builtin("rptProbitInterpolateY", Regress.RptProbitInterpolateY),
                new Builtin("rptProbitMore", Regress.RptProbitMore),
                new Builtin("rptProportionMeta", (parameters) => Meta.RptProportionMeta(parameters)),
                new Builtin("rptPropPairs", Analysis.RptPropPairs),
                new Builtin("rptPropSingle", Analysis.RptPropSingle),
                new Builtin("rptPropUnPaired", Analysis.RptPropUnPaired),
                new Builtin("rptQuantile", Nonparametric.RptQuantile),
                new Builtin("rptRandomBlock", Formula.RptRandomBlock),
                new Builtin("rptRandomPairs", Formula.RptRandomPairs),
                new Builtin("rptRandomUnPaired", Formula.RptRandomUnPaired),
                new Builtin("rptRandomXY", Formula.RptRandomXY),
                new Builtin("rptRanv", Regress.RptRanv),
                new Builtin("rptRateCompareTwo", (parameters) => Analysis.RptRateCompareTwo(parameters)),
                new Builtin("rptRateDirect", Rates.RptRateDirect),
                new Builtin("rptRateDirectStd", Analysis.RptRateDirectStd),
                new Builtin("rptRatePoissonCI", Exact.RptRatePoissonCI),
                new Builtin("rptRateSMR", Rates.RptRateSmr),
                new Builtin("rptReferenceRange", Parametric.RptReferenceRange),
                new Builtin("rptRelativeRiskMeta", (parameters) => Meta.RptRelativeRiskMeta(parameters)),
                new Builtin("rptRiskDifferenceMeta", (parameters) => Meta.RptRiskDifferenceMeta(parameters)),
                new Builtin("rptNormality", (parameters) => Parametric.RptNormality(parameters)),
                new Builtin("rptSimpleLinearRegression", Regress.RptSimpleLinearRegression),
                new Builtin("rptSizeCorrelation", Formula.RptSizeCorrelation),
                new Builtin("rptSizeIndCase", Formula.RptSizeIndCase),
                new Builtin("rptSizeIndProp", Formula.RptSizeIndProp),
                new Builtin("rptSizeMatchCase", Formula.RptSizeMatchCase),
                new Builtin("rptSizeMatchProp", Formula.RptSizeMatchProp),
                new Builtin("rptSizePaired", Formula.RptSizePaired),
                new Builtin("rptSizePopSurvey", Formula.RptSizePopSurvey),
                new Builtin("rptSizeSurvival", Formula.RptSizeSurvival),
                new Builtin("rptSizeUnPaired", Formula.RptSizeUnPaired),
                new Builtin("rptSpearman", Nonparametric.RptSpearman),
                new Builtin("rptSmirnov", Nonparametric.RptSmirnov),
                new Builtin("rptScheffe", Anova.RptScheffe),
                new Builtin("rptSqRank", Nonparametric.RptSqRank),
                new Builtin("rptTimeSeriesSummary", (parameters) => Describe.RptTimeSeriesSummary(parameters)),
                new Builtin("rptStdrr", Rates.RptStdrr),
                new Builtin("rptTPaired", Parametric.RptTPaired),
                new Builtin("rptTSingle", Parametric.RptTSingle),
                new Builtin("rptTSingleSummary", Parametric.RptTSingleSummary),
                new Builtin("rptTUnpaired", Parametric.RptTUnpaired),
                new Builtin("rptTUnpairedSummary", Parametric.RptTUnpairedSummary),
                new Builtin("rptTukey", Anova.RptTukey),
                new Builtin("rptTwoMulti", Anova.RptTwoMulti),
                new Builtin("rptTwoNest", Anova.RptTwoNest),
                new Builtin("rptTwoWay", Anova.RptTwoWay),
                new Builtin("rptUnivariateSummary", Describe.RptUnivariateSummary),
                new Builtin("rptUniversalAgreement", Agreement.RptUniversalAgreement),
                new Builtin("rptUniversalAgreementSimulateExactP", (parameters) => Agreement.RptUniversalAgreementSimulateExactP(parameters)),
                new Builtin("rptUniversalRCompare", Agreement.RptUniversalRCompare),
                new Builtin("rptWeightedUnivariateSummary", Describe.RptWeightedUnivariateSummary),
                new Builtin("rptWeiLachin", Survival.RptWeiLachin),
                new Builtin("rptWilcoxon", (parameters) => Nonparametric.RptWilcoxon(parameters)),
                new Builtin("rptXxi", Regress.RptXxi),
                new Builtin("rptChildGrowth", Sheet.RptChildGrowth),
                new Builtin("rptZSingle", Parametric.RptZSingle),
                new Builtin("rptZUnpaired", Parametric.RptZUnpaired),
                new Builtin("setAnalysisOptions", (parameters) => Options.SetAnalysisOptions(parameters)),
                new Builtin("showGraphicsOptions", (parameters) => Options.ShowGraphicsOptions(parameters)),
                new Builtin("shtClearMissing", Sheet.ShtClearMissing),
                new Builtin("shtCombine", Sheet.ShtCombine),
                new Builtin("shtContract", Sheet.ShtContract),
                new Builtin("shtConvertUnits", Sheet.ShtConvertUnits),
                new Builtin("shtDates", Sheet.ShtDates),
                new Builtin("shtDetabulate", Tables.ShtDetabulate),
                new Builtin("shtDummyVariables", Sheet.ShtDummyVariables),
                new Builtin("shtExpand", Sheet.ShtExpand),
                new Builtin("shtFillSeries", Sheet.ShtFillSeries),
                new Builtin("shtFindAndReplaceAdvanced", Sheet.ShtFindAndReplaceAdvanced),
                new Builtin("shtGroupCategorise", (parameters) => Sheet.ShtGroupCategorise(parameters)),
                new Builtin("shtGroupExtract", (parameters) => Sheet.ShtGroupExtract(parameters)),
                new Builtin("shtGroupSplit", Sheet.ShtGroupSplit),
                new Builtin("shtLadderPowers", Sheet.ShtLadderPowers),
                new Builtin("shtNormal", Sheet.ShtNormal),
                new Builtin("shtPairDifferences", (parameters) => Sheet.ShtPairDifferences(parameters)),
                new Builtin("shtPairMeans", (parameters) => Sheet.ShtPairMeans(parameters)),
                new Builtin("shtPairSlopes", (parameters) => Sheet.ShtPairSlopes(parameters)),
                new Builtin("shtRank", Sheet.ShtRank),
                new Builtin("shtRotate", Sheet.ShtRotate),
                new Builtin("shtRndBeta", Sheet.ShtRndBeta),
                new Builtin("shtRndBinomial", Sheet.ShtRndBinomial),
                new Builtin("shtRndCauchy", Sheet.ShtRndCauchy),
                new Builtin("shtRndChiSquare", Sheet.ShtRndChiSquare),
                new Builtin("shtRndExponential", Sheet.ShtRndExponential),
                new Builtin("shtRndF", Sheet.ShtRndF),
                new Builtin("shtRndGamma", Sheet.ShtRndGamma),
                new Builtin("shtRndGeometric", Sheet.ShtRndGeometric),
                new Builtin("shtRndLogit", Sheet.ShtRndLogit),
                new Builtin("shtRndLogNormal", Sheet.ShtRndLogNormal),
                new Builtin("shtRndNegativeBinomial", Sheet.ShtRndNegativeBinomial),
                new Builtin("shtRndNormal", Sheet.ShtRndNormal),
                new Builtin("shtRndPoisson", Sheet.ShtRndPoisson),
                new Builtin("shtRndT", Sheet.ShtRndT),
                new Builtin("shtRndUniform01", Sheet.ShtRndUniform01),
                new Builtin("shtRndUniformAB", Sheet.ShtRndUniformAB),
                new Builtin("shtRndWeibull", Sheet.ShtRndWeibull),
                new Builtin("shtSort", Sheet.ShtSort),
                new Builtin("shtSortByExpression", Sheet.ShtSortByExpression),
                new Builtin("shtSortInPlace", (parameters) => Sheet.ShtSortInPlace(parameters)),
                new Builtin("shtStandardize", Sheet.ShtStandardize),
                new Builtin("shtTabulate", Tables.ShtTabulate),
                new Builtin("shtToggleFilters", (parameters) => Sheet.ShtToggleFilters(parameters)),
                new Builtin("shtTransformAngular", Sheet.ShtTransformAngular),
                new Builtin("shtTransformCumulate", Sheet.ShtTransformCumulate),
                new Builtin("shtTransformECDF", Sheet.ShtTransformECDF),
                new Builtin("shtTransformLog", Sheet.ShtTransformLog),
                new Builtin("shtTransformLog10", Sheet.ShtTransformLog10),
                new Builtin("shtTransformLogit", Sheet.ShtTransformLogit),
                new Builtin("shtTransformProbit", Sheet.ShtTransformProbit),
                new Builtin("shtTransformZECDF", Sheet.ShtTransformZecdf),
                new Builtin("shtTransformZSD", Sheet.ShtTransformZsd),
                new Builtin("valuesToFrequencies", Sheet.ValuesToFrequencies)
            };
            return functionRegistry;
        }
    }
}
