<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>StatsDirect</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>StatsDirect</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <NoWarn>CA1416</NoWarn>
    <ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt</ApplicationDefaultFont>
    <UseWPF>False</UseWPF>
    <StartupObject>StatsDirect.UI.Program</StartupObject>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <Version>4.0.5</Version>
    <AssemblyTitle>StatsDirect</AssemblyTitle>
    <AssemblyDescription>StatsDirect statistical analysis workbench</AssemblyDescription>
    <Company>StatsDirect Limited</Company>
    <Product>StatsDirect</Product>
    <Copyright>Copyright ©1997-2025 StatsDirect Limited</Copyright>
  </PropertyGroup>
  <PropertyGroup>
	<!-- Pull the SSG license string from the environment - make sure you set this in your environment variables on your build machine! -->
    <SpreadsheetGearLicenseString>$(SPREADSHEETGEAR_LICENSE_STRING)</SpreadsheetGearLicenseString>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="StatsDirect.UI.SpreadsheetGearLicenseAttribute">
      <_Parameter1>$(SpreadsheetGearLicenseString)</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.CLSCompliantAttribute">
      <_Parameter1>false</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UI\frmReportDNBTest.cs" />
    <Compile Remove="UI\frmReportDNBTest.Designer.cs" />
    <Compile Remove="UI\frmReportDotNetBrowser.cs" />
    <Compile Remove="UI\frmReportDotNetBrowser.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="UI\frmReportDNBTest.resx" />
    <EmbeddedResource Remove="UI\frmReportDotNetBrowser.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Antlr4.Runtime" Version="4.6.6" />
    <PackageReference Include="DevExpress.Win.RichEdit" Version="25.1.7" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="5.0.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="OpenMcdf" Version="3.1.0" />
    <PackageReference Include="PresentationFramework" Version="4.6.0" />
    <PackageReference Include="SpreadsheetGear.Windows" Version="9.3.56" />
  </ItemGroup>
  <ItemGroup>
    <ContentWithTargetPath Include="Assets/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StatsDirectEngine\StatsDirectEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationFramework">
      <HintPath>..\..\..\..\..\Windows Kits\10\Windows Performance Toolkit\PresentationFramework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ReleaseWithSigning|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugWatchExceptions|AnyCPU'">
    <DefineConstants>$(DefineConstants);WATCH_EXCEPTIONS</DefineConstants>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  </Target>
</Project>
