<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows10.0.17763.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>StatsDirect</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>StatsDirect</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>CA1416</NoWarn>
    <ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt</ApplicationDefaultFont>
    <UseWPF>False</UseWPF>
    <StartupObject>StatsDirect.UI.Program</StartupObject>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>true</TieredCompilation>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="UI\frmReportDNBTest.cs" />
    <Compile Remove="UI\frmReportDNBTest.Designer.cs" />
    <Compile Remove="UI\frmReportDotNetBrowser.cs" />
    <Compile Remove="UI\frmReportDotNetBrowser.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="UI\frmReportDNBTest.resx" />
    <EmbeddedResource Remove="UI\frmReportDotNetBrowser.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Antlr4.Runtime" Version="4.6.6" />
    <PackageReference Include="DevExpress.Win.RichEdit" Version="23.2.5" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.8.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="OpenMcdf" Version="2.3.0" />
    <PackageReference Include="PresentationFramework" Version="4.6.0" />
    <PackageReference Include="SpreadsheetGear.Windows" Version="9.2.26" />
  </ItemGroup>
  <ItemGroup>
    <ContentWithTargetPath Include="Assets/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\WebHelp\agreement\agreement_analyses.htm" />
    <Content Include="Assets\WebHelp\agreement\intraclass.htm" />
    <Content Include="Assets\WebHelp\agreement\kappa.htm" />
    <Content Include="Assets\WebHelp\agreement\mcr.htm" />
    <Content Include="Assets\WebHelp\agreement\universal_agreement.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\anova.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\crossover.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\homogeneity_of_variance.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\latin_square.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\multiple_comparisons.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\nested.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\one_way.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\randomized_blocks.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\treatments_and_blocks.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\two_way.htm" />
    <Content Include="Assets\WebHelp\analysis_of_variance\two_way_replicate.htm" />
    <Content Include="Assets\WebHelp\basics\analysis.htm" />
    <Content Include="Assets\WebHelp\basics\attributable_risk.htm" />
    <Content Include="Assets\WebHelp\basics\basics.htm" />
    <Content Include="Assets\WebHelp\basics\bias.htm" />
    <Content Include="Assets\WebHelp\basics\calculator.htm" />
    <Content Include="Assets\WebHelp\basics\causality.htm" />
    <Content Include="Assets\WebHelp\basics\confidence_interval.htm" />
    <Content Include="Assets\WebHelp\basics\confounding.htm" />
    <Content Include="Assets\WebHelp\basics\degrees_freedom.htm" />
    <Content Include="Assets\WebHelp\basics\epidemiology.htm" />
    <Content Include="Assets\WebHelp\basics\example.htm" />
    <Content Include="Assets\WebHelp\basics\excel.htm" />
    <Content Include="Assets\WebHelp\basics\intention_to_treat.htm" />
    <Content Include="Assets\WebHelp\basics\licence.htm" />
    <Content Include="Assets\WebHelp\basics\measurement_scales.htm" />
    <Content Include="Assets\WebHelp\basics\missing_data.htm" />
    <Content Include="Assets\WebHelp\basics\precision.htm" />
    <Content Include="Assets\WebHelp\basics\prospective.htm" />
    <Content Include="Assets\WebHelp\basics\p_values.htm" />
    <Content Include="Assets\WebHelp\basics\reliability.htm" />
    <Content Include="Assets\WebHelp\basics\statistics.htm" />
    <Content Include="Assets\WebHelp\basics\validity.htm" />
    <Content Include="Assets\WebHelp\basics\variables.htm" />
    <Content Include="Assets\WebHelp\basics\worksheet.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\central_tendency.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\crosstabs.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\descriptive_statistics.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\frequencies.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\quick_summary.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\skewness.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\standard_deviation.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\time_series.htm" />
    <Content Include="Assets\WebHelp\basic_descriptive_statistics\univariate_summary.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\22.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\2k.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\chisq_tests.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\generalized_cochran_mantel_haenszel.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\haldane_correction.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\mcnemar.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\rc.htm" />
    <Content Include="Assets\WebHelp\chi_square_tests\woolf.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\clinical_epidemiology.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\diagnostic.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\likelihood_ratios.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\nnt.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\risk_prospective.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\risk_retrospective.htm" />
    <Content Include="Assets\WebHelp\clinical_epidemiology\screening_test.htm" />
    <Content Include="Assets\WebHelp\contents.htm" />
    <Content Include="Assets\WebHelp\Data\Alias.xml" />
    <Content Include="Assets\WebHelp\Data\HelpSystem.xml" />
    <Content Include="Assets\WebHelp\Data\Synonyms.xml" />
    <Content Include="Assets\WebHelp\data_preparation\apply_function.htm" />
    <Content Include="Assets\WebHelp\data_preparation\categorise.htm" />
    <Content Include="Assets\WebHelp\data_preparation\cleaning.htm" />
    <Content Include="Assets\WebHelp\data_preparation\clear_missing_data.htm" />
    <Content Include="Assets\WebHelp\data_preparation\combine_groups.htm" />
    <Content Include="Assets\WebHelp\data_preparation\contract.htm" />
    <Content Include="Assets\WebHelp\data_preparation\conversion_factors.htm" />
    <Content Include="Assets\WebHelp\data_preparation\data_preparation.htm" />
    <Content Include="Assets\WebHelp\data_preparation\dates_and_times.htm" />
    <Content Include="Assets\WebHelp\data_preparation\date_time_intervals.htm" />
    <Content Include="Assets\WebHelp\data_preparation\detabulate.htm" />
    <Content Include="Assets\WebHelp\data_preparation\dummy_variables.htm" />
    <Content Include="Assets\WebHelp\data_preparation\expand.htm" />
    <Content Include="Assets\WebHelp\data_preparation\extract_variables.htm" />
    <Content Include="Assets\WebHelp\data_preparation\fill_series.htm" />
    <Content Include="Assets\WebHelp\data_preparation\filter_worksheet.htm" />
    <Content Include="Assets\WebHelp\data_preparation\generating.htm" />
    <Content Include="Assets\WebHelp\data_preparation\group_split.htm" />
    <Content Include="Assets\WebHelp\data_preparation\growth_charts.htm" />
    <Content Include="Assets\WebHelp\data_preparation\organizing.htm" />
    <Content Include="Assets\WebHelp\data_preparation\pairwise.htm" />
    <Content Include="Assets\WebHelp\data_preparation\pairwise_differences.htm" />
    <Content Include="Assets\WebHelp\data_preparation\pairwise_means.htm" />
    <Content Include="Assets\WebHelp\data_preparation\pairwise_slopes.htm" />
    <Content Include="Assets\WebHelp\data_preparation\ranking.htm" />
    <Content Include="Assets\WebHelp\data_preparation\rotate_block.htm" />
    <Content Include="Assets\WebHelp\data_preparation\search_replace.htm" />
    <Content Include="Assets\WebHelp\data_preparation\sorting.htm" />
    <Content Include="Assets\WebHelp\data_preparation\sorting_create.htm" />
    <Content Include="Assets\WebHelp\data_preparation\sorting_worksheet.htm" />
    <Content Include="Assets\WebHelp\data_preparation\standardization.htm" />
    <Content Include="Assets\WebHelp\data_preparation\tabulate.htm" />
    <Content Include="Assets\WebHelp\data_preparation\text_to_numbers.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transformations.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transforming_and_deriving.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transforming_data.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_angle.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_cumulative.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_empirical_cdf.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_ladder_powers.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_log.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_logit.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_normal_scores.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_probit.htm" />
    <Content Include="Assets\WebHelp\data_preparation\transform_z_scores.htm" />
    <Content Include="Assets\WebHelp\Default.htm" />
    <Content Include="Assets\WebHelp\Default_CSH.htm" />
    <Content Include="Assets\WebHelp\distributions\binomial.htm" />
    <Content Include="Assets\WebHelp\distributions\chisq.htm" />
    <Content Include="Assets\WebHelp\distributions\distributions.htm" />
    <Content Include="Assets\WebHelp\distributions\f.htm" />
    <Content Include="Assets\WebHelp\distributions\gamma.htm" />
    <Content Include="Assets\WebHelp\distributions\non_central_t.htm" />
    <Content Include="Assets\WebHelp\distributions\normal.htm" />
    <Content Include="Assets\WebHelp\distributions\poisson.htm" />
    <Content Include="Assets\WebHelp\distributions\rho.htm" />
    <Content Include="Assets\WebHelp\distributions\studentized_range.htm" />
    <Content Include="Assets\WebHelp\distributions\t.htm" />
    <Content Include="Assets\WebHelp\distributions\tau.htm" />
    <Content Include="Assets\WebHelp\exact_tests_on_counts\exact_tests.htm" />
    <Content Include="Assets\WebHelp\exact_tests_on_counts\fisher_exact.htm" />
    <Content Include="Assets\WebHelp\exact_tests_on_counts\fisher_exact_extended.htm" />
    <Content Include="Assets\WebHelp\exact_tests_on_counts\odds_ratio_ci.htm" />
    <Content Include="Assets\WebHelp\exact_tests_on_counts\sign.htm" />
    <Content Include="Assets\WebHelp\graphics\bar.htm" />
    <Content Include="Assets\WebHelp\graphics\box_whisker.htm" />
    <Content Include="Assets\WebHelp\graphics\box_whisker_text.htm" />
    <Content Include="Assets\WebHelp\graphics\check_scale.htm" />
    <Content Include="Assets\WebHelp\graphics\control.htm" />
    <Content Include="Assets\WebHelp\graphics\defaults.htm" />
    <Content Include="Assets\WebHelp\graphics\default_label_font.htm" />
    <Content Include="Assets\WebHelp\graphics\default_title_font.htm" />
    <Content Include="Assets\WebHelp\graphics\error_bar.htm" />
    <Content Include="Assets\WebHelp\graphics\export_graphic.htm" />
    <Content Include="Assets\WebHelp\graphics\forest.htm" />
    <Content Include="Assets\WebHelp\graphics\graphics.htm" />
    <Content Include="Assets\WebHelp\graphics\histogram.htm" />
    <Content Include="Assets\WebHelp\graphics\histogram_text.htm" />
    <Content Include="Assets\WebHelp\graphics\ladder.htm" />
    <Content Include="Assets\WebHelp\graphics\markers.htm" />
    <Content Include="Assets\WebHelp\graphics\normal.htm" />
    <Content Include="Assets\WebHelp\graphics\population_pyramid.htm" />
    <Content Include="Assets\WebHelp\graphics\scatter.htm" />
    <Content Include="Assets\WebHelp\graphics\scatter_text.htm" />
    <Content Include="Assets\WebHelp\graphics\spread.htm" />
    <Content Include="Assets\WebHelp\graphics\survival.htm" />
    <Content Include="Assets\WebHelp\graphics\text_vector.htm" />
    <Content Include="Assets\WebHelp\menus\about.htm" />
    <Content Include="Assets\WebHelp\menus\analysis_options.htm" />
    <Content Include="Assets\WebHelp\menus\arrange_icons.htm" />
    <Content Include="Assets\WebHelp\menus\batch_mode.htm" />
    <Content Include="Assets\WebHelp\menus\cascade_windows.htm" />
    <Content Include="Assets\WebHelp\menus\close.htm" />
    <Content Include="Assets\WebHelp\menus\copy.htm" />
    <Content Include="Assets\WebHelp\menus\current_report_or_workbook.htm" />
    <Content Include="Assets\WebHelp\menus\edit.htm" />
    <Content Include="Assets\WebHelp\menus\edit_options.htm" />
    <Content Include="Assets\WebHelp\menus\exit.htm" />
    <Content Include="Assets\WebHelp\menus\file.htm" />
    <Content Include="Assets\WebHelp\menus\format.htm" />
    <Content Include="Assets\WebHelp\menus\help.htm" />
    <Content Include="Assets\WebHelp\menus\insert.htm" />
    <Content Include="Assets\WebHelp\menus\international_issues.htm" />
    <Content Include="Assets\WebHelp\menus\maximize.htm" />
    <Content Include="Assets\WebHelp\menus\open_file.htm" />
    <Content Include="Assets\WebHelp\menus\page_setup.htm" />
    <Content Include="Assets\WebHelp\menus\paste.htm" />
    <Content Include="Assets\WebHelp\menus\previously_opened_files.htm" />
    <Content Include="Assets\WebHelp\menus\print.htm" />
    <Content Include="Assets\WebHelp\menus\printer_setup.htm" />
    <Content Include="Assets\WebHelp\menus\print_preview.htm" />
    <Content Include="Assets\WebHelp\menus\rename_as.htm" />
    <Content Include="Assets\WebHelp\menus\save.htm" />
    <Content Include="Assets\WebHelp\menus\save_as.htm" />
    <Content Include="Assets\WebHelp\menus\setup_tools.htm" />
    <Content Include="Assets\WebHelp\menus\tile_windows_horizontally.htm" />
    <Content Include="Assets\WebHelp\menus\tile_windows_vertically.htm" />
    <Content Include="Assets\WebHelp\menus\tools.htm" />
    <Content Include="Assets\WebHelp\menus\window.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\bias_detection.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\correlation.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\effect_size.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\further.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\heterogeneity.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\incidence_rate.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\labbe.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\meta_analyses.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\mh.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\options.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\peto.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\proportion.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\relative_risk.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\risk_difference.htm" />
    <Content Include="Assets\WebHelp\meta_analysis\summary.htm" />
    <Content Include="Assets\WebHelp\methods\comparison_of_two_independent_groups.htm" />
    <Content Include="Assets\WebHelp\methods\comparison_response_different_conditions.htm" />
    <Content Include="Assets\WebHelp\methods\interval_measured_independent_groups.htm" />
    <Content Include="Assets\WebHelp\methods\methods_dichotomous_vs_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_non_normal_vs_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_non_normal_vs_interval_non_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_non_normal_vs_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_non_normal_vs_nominal_ordered.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_non_normal_vs_ordinal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_normal_vs_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_normal_vs_interval_non_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_normal_vs_interval_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_normal_vs_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_normal_vs_nominal_ordered.htm" />
    <Content Include="Assets\WebHelp\methods\methods_interval_normal_vs_ordinal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_nominal_ordered_vs_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_nominal_ordered_vs_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_nominal_ordered_vs_nominal_ordered.htm" />
    <Content Include="Assets\WebHelp\methods\methods_nominal_vs_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_nominal_vs_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_ordinal_vs_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_ordinal_vs_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_ordinal_vs_nominal_ordered.htm" />
    <Content Include="Assets\WebHelp\methods\methods_ordinal_vs_ordinal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_paired_dichotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_paired_interval_small_medium_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_paired_interval_small_to_medium_non_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_paired_interval__large_sample.htm" />
    <Content Include="Assets\WebHelp\methods\methods_paired_nominal_without_order.htm" />
    <Content Include="Assets\WebHelp\methods\methods_paired_ordinal_or_ordered_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_dicotomous.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_interval_large_sample.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_interval_small_medium_non_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_interval_small_medium_normal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_nominal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_nominal_ordered.htm" />
    <Content Include="Assets\WebHelp\methods\methods_unpaired_ordinal.htm" />
    <Content Include="Assets\WebHelp\methods\methods_warning.htm" />
    <Content Include="Assets\WebHelp\methods\method_selection.htm" />
    <Content Include="Assets\WebHelp\methods\paired_interval_measurements.htm" />
    <Content Include="Assets\WebHelp\methods\relationship_two_variables_measured_on_same_group.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\chisq_goodness_fit.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\cuzick.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\diversity.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\friedman.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\gini.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\kendall_correlation.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\kruskal_wallis.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\loess.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\mann_whitney.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\nonmarametric_methods.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\nonparametric_regression.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\quantiles.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\quantile_ci.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\roc.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\smirnov.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\spearman.htm" />
    <Content Include="Assets\WebHelp\nonparametric_methods\wilcoxon_signed_ranks.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\f_variance_ratio.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\normality.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\paired_t.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\parametric_methods.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\poisson_ci.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\reference_range.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\single_sample_t.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\summary_t.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\unpaired_t.htm" />
    <Content Include="Assets\WebHelp\parametric_methods\z_normal.htm" />
    <Content Include="Assets\WebHelp\proportions\binomial_proportions.htm" />
    <Content Include="Assets\WebHelp\proportions\mid_p.htm" />
    <Content Include="Assets\WebHelp\proportions\paired.htm" />
    <Content Include="Assets\WebHelp\proportions\proportions.htm" />
    <Content Include="Assets\WebHelp\proportions\single.htm" />
    <Content Include="Assets\WebHelp\proportions\unpaired.htm" />
    <Content Include="Assets\WebHelp\randomization\block.htm" />
    <Content Include="Assets\WebHelp\randomization\generate_random_numbers.htm" />
    <Content Include="Assets\WebHelp\randomization\intervention_control_pairs.htm" />
    <Content Include="Assets\WebHelp\randomization\preference_group.htm" />
    <Content Include="Assets\WebHelp\randomization\randomization.htm" />
    <Content Include="Assets\WebHelp\randomization\random_number_generator.htm" />
    <Content Include="Assets\WebHelp\randomization\two_independent_groups.htm" />
    <Content Include="Assets\WebHelp\randomization\x_y_series.htm" />
    <Content Include="Assets\WebHelp\rates\compare_crude_incidence_rates.htm" />
    <Content Include="Assets\WebHelp\rates\direct_standardization.htm" />
    <Content Include="Assets\WebHelp\rates\incidence_and_prevalence.htm" />
    <Content Include="Assets\WebHelp\rates\poisson_rate_ci.htm" />
    <Content Include="Assets\WebHelp\rates\rates.htm" />
    <Content Include="Assets\WebHelp\rates\smr.htm" />
    <Content Include="Assets\WebHelp\rates\standardize_compare_two_rates.htm" />
    <Content Include="Assets\WebHelp\references\glossary.htm" />
    <Content Include="Assets\WebHelp\references\reference_list.htm" />
    <Content Include="Assets\WebHelp\references\reference_sources.htm" />
    <Content Include="Assets\WebHelp\references\support.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\conditional_logistic.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\correlation_all_pairs.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\grouped.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\grouped_covariance.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\grouped_linearity_replicates.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\linear_estimates.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\logistic.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\multiple_linear.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\nonlinear.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\partial_correlation.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\pca.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\poisson.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\polynomial.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\probit_analysis.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\questionnaire_design.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\regression_and_correlation.htm" />
    <Content Include="Assets\WebHelp\regression_and_correlation\simple_linear.htm" />
    <Content Include="Assets\WebHelp\report\cut.htm" />
    <Content Include="Assets\WebHelp\report\default_page_settings.htm" />
    <Content Include="Assets\WebHelp\report\delete.htm" />
    <Content Include="Assets\WebHelp\report\export_text.htm" />
    <Content Include="Assets\WebHelp\report\find.htm" />
    <Content Include="Assets\WebHelp\report\find_replace.htm" />
    <Content Include="Assets\WebHelp\report\format_bullets.htm" />
    <Content Include="Assets\WebHelp\report\format_font.htm" />
    <Content Include="Assets\WebHelp\report\format_paragraph.htm" />
    <Content Include="Assets\WebHelp\report\import_text.htm" />
    <Content Include="Assets\WebHelp\report\insert_date_and_time.htm" />
    <Content Include="Assets\WebHelp\report\insert_picture.htm" />
    <Content Include="Assets\WebHelp\report\new_report.htm" />
    <Content Include="Assets\WebHelp\report\replace.htm" />
    <Content Include="Assets\WebHelp\report\selecting_text.htm" />
    <Content Include="Assets\WebHelp\report\select_all.htm" />
    <Content Include="Assets\WebHelp\report\undo.htm" />
    <Content Include="Assets\WebHelp\resources\images\about.png" />
    <Content Include="Assets\WebHelp\resources\images\bar_chart.png" />
    <Content Include="Assets\WebHelp\resources\images\bias1_wmf.gif" />
    <Content Include="Assets\WebHelp\resources\images\bias2_wmf.gif" />
    <Content Include="Assets\WebHelp\resources\images\binomialchart.gif" />
    <Content Include="Assets\WebHelp\resources\images\binomialchart2.gif" />
    <Content Include="Assets\WebHelp\resources\images\boxwhisker.gif" />
    <Content Include="Assets\WebHelp\resources\images\controlchart.gif" />
    <Content Include="Assets\WebHelp\resources\images\deming_regression.png" />
    <Content Include="Assets\WebHelp\resources\images\ebx_1266835018.gif" />
    <Content Include="Assets\WebHelp\resources\images\ebx_545344684.gif" />
    <Content Include="Assets\WebHelp\resources\images\errorbar.gif" />
    <Content Include="Assets\WebHelp\resources\images\fcurves.gif" />
    <Content Include="Assets\WebHelp\resources\images\forest.gif" />
    <Content Include="Assets\WebHelp\resources\images\forest2.gif" />
    <Content Include="Assets\WebHelp\resources\images\hazardplot.gif" />
    <Content Include="Assets\WebHelp\resources\images\hazardrate.gif" />
    <Content Include="Assets\WebHelp\resources\images\hbegfr.png" />
    <Content Include="Assets\WebHelp\resources\images\histogram.gif" />
    <Content Include="Assets\WebHelp\resources\images\histogram2.gif" />
    <Content Include="Assets\WebHelp\resources\images\kaplanplot.gif" />
    <Content Include="Assets\WebHelp\resources\images\labbe.gif" />
    <Content Include="Assets\WebHelp\resources\images\ladder.gif" />
    <Content Include="Assets\WebHelp\resources\images\linechart.gif" />
    <Content Include="Assets\WebHelp\resources\images\loess.png" />
    <Content Include="Assets\WebHelp\resources\images\loghazardplot.gif" />
    <Content Include="Assets\WebHelp\resources\images\lognormalsurvival.gif" />
    <Content Include="Assets\WebHelp\resources\images\lorenz.gif" />
    <Content Include="Assets\WebHelp\resources\images\normalcurves.gif" />
    <Content Include="Assets\WebHelp\resources\images\normalhistogram.gif" />
    <Content Include="Assets\WebHelp\resources\images\normal_plot.png" />
    <Content Include="Assets\WebHelp\resources\images\polynolialci.gif" />
    <Content Include="Assets\WebHelp\resources\images\polynomialcurve.gif" />
    <Content Include="Assets\WebHelp\resources\images\polynomialpi.gif" />
    <Content Include="Assets\WebHelp\resources\images\polynomialregression.gif" />
    <Content Include="Assets\WebHelp\resources\images\probitplot.gif" />
    <Content Include="Assets\WebHelp\resources\images\pyramid.gif" />
    <Content Include="Assets\WebHelp\resources\images\qq.gif" />
    <Content Include="Assets\WebHelp\resources\images\rateratioplot.gif" />
    <Content Include="Assets\WebHelp\resources\images\repeatability.gif" />
    <Content Include="Assets\WebHelp\resources\images\scatter.gif" />
    <Content Include="Assets\WebHelp\resources\images\sd3.ico" />
    <Content Include="Assets\WebHelp\resources\images\sd3helplogo.png" />
    <Content Include="Assets\WebHelp\resources\images\sdbutton.png" />
    <Content Include="Assets\WebHelp\resources\images\sigma.gif" />
    <Content Include="Assets\WebHelp\resources\images\spreadplot.gif" />
    <Content Include="Assets\WebHelp\resources\images\stat0001.gif" />
    <Content Include="Assets\WebHelp\resources\images\statsdirect_logo.jpg" />
    <Content Include="Assets\WebHelp\resources\images\survivalchart.gif" />
    <Content Include="Assets\WebHelp\resources\images\tcurves.gif" />
    <Content Include="Assets\WebHelp\resources\images\time_series_summary_compare.png" />
    <Content Include="Assets\WebHelp\resources\images\time_series_summary_malabsorbtion.png" />
    <Content Include="Assets\WebHelp\resources\images\time_series_summary_normal.png" />
    <Content Include="Assets\WebHelp\resources\images\time_series_summary_normal_plot.png" />
    <Content Include="Assets\WebHelp\resources\images\time_series_summary_normal_plot_log.png" />
    <Content Include="Assets\WebHelp\resources\stylesheets\statsdirect.css" />
    <Content Include="Assets\WebHelp\resources\stylesheets\statsdirect2.css" />
    <Content Include="Assets\WebHelp\sample_size\correlation.htm" />
    <Content Include="Assets\WebHelp\sample_size\independent_case_control.htm" />
    <Content Include="Assets\WebHelp\sample_size\independent_cohort.htm" />
    <Content Include="Assets\WebHelp\sample_size\matched_case_control.htm" />
    <Content Include="Assets\WebHelp\sample_size\paired_cohort.htm" />
    <Content Include="Assets\WebHelp\sample_size\paired_t_test.htm" />
    <Content Include="Assets\WebHelp\sample_size\population_survey.htm" />
    <Content Include="Assets\WebHelp\sample_size\sample_size.htm" />
    <Content Include="Assets\WebHelp\sample_size\survival.htm" />
    <Content Include="Assets\WebHelp\sample_size\unpaired_t_test.htm" />
    <Content Include="Assets\WebHelp\Sitemap.xml" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Components\Mobile.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Components\Print.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Components\Styles.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Components\Tablet.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\foundation_custom.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\arrow-down.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\arrow-up.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\book-open.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\book.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\browseActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\browseInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\close.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\collapse.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\communityActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\communityInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\diagonal_lines.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\edit-profile.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\expand.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\Filter.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\FilterOutline.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\glossaryActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\glossaryInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\help-control.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\highlight.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\icon-user-gray.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\icon-user-light-gray.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\index-collapsed.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\index-expanded.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\index.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\indexActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\indexInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\loading-32px.gif" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\loading.gif" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\login-dialog-icon.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\login.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\logo.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\magnifying_glass.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\MCSlider_controls.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\MCSlider_loader.gif" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\navigate-next.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\navigate-previous.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\new-indicator.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\printer.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\RatingStars.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveBook.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveBrowseSequenceActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveBrowseSequenceInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveCollapseAllButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveExpandAllButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveGlossaryActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveGlossaryInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveHome.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveIndexActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveIndexInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveLogInButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveMadCapLogo.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveMenuButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveNextTopicButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveOpenBook.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsivePreviousTopicButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsivePrintButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveRatingStarEmpty.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveRatingStarFilled.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveRemoveHighlightsButton.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveSearch.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveSearchFilterActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveSearchFilterInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveTOCActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveTOCInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\ResponsiveTopic.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\sd3helplogo.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\SearchIcon.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\select-language.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\select-skin.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\star-empty.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\star-full.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\tocActive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\tocInactive.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\topic.png" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Images\transparent.gif" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Mobile.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\normalize.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\offcanvas.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Print.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Slideshow.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Styles.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Tablet.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\TextEffects.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\TextEffects.micro-content.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Topic.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Topic.micro-content.css" />
    <Content Include="Assets\WebHelp\Skins\Default\Stylesheets\Web.css" />
    <Content Include="Assets\WebHelp\Skins\Fluid\Stylesheets\Images\arrow-down.png" />
    <Content Include="Assets\WebHelp\Skins\Fluid\Stylesheets\Images\arrow-up.png" />
    <Content Include="Assets\WebHelp\survival_analysis\abridged_life_table.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\censorship.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\cox_regression.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\follow_up_life_table.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\kaplan_meier.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\logrank.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\survival.htm" />
    <Content Include="Assets\WebHelp\survival_analysis\wei_lachin.htm" />
    <Content Include="Assets\WebHelp\workbook\auto_fit_column_width.htm" />
    <Content Include="Assets\WebHelp\workbook\clear_from_selected_cells.htm" />
    <Content Include="Assets\WebHelp\workbook\colour_palette.htm" />
    <Content Include="Assets\WebHelp\workbook\column_titles.htm" />
    <Content Include="Assets\WebHelp\workbook\column_width.htm" />
    <Content Include="Assets\WebHelp\workbook\cut_selected_cells.htm" />
    <Content Include="Assets\WebHelp\workbook\default_font_for_workbook.htm" />
    <Content Include="Assets\WebHelp\workbook\default_height_for_rows.htm" />
    <Content Include="Assets\WebHelp\workbook\default_width_for_columns.htm" />
    <Content Include="Assets\WebHelp\workbook\delete_column.htm" />
    <Content Include="Assets\WebHelp\workbook\delete_row.htm" />
    <Content Include="Assets\WebHelp\workbook\delete_special.htm" />
    <Content Include="Assets\WebHelp\workbook\delete_worksheet.htm" />
    <Content Include="Assets\WebHelp\workbook\exporting_data.htm" />
    <Content Include="Assets\WebHelp\workbook\fill_down.htm" />
    <Content Include="Assets\WebHelp\workbook\fill_right.htm" />
    <Content Include="Assets\WebHelp\workbook\find_replace.htm" />
    <Content Include="Assets\WebHelp\workbook\formatting_worksheets.htm" />
    <Content Include="Assets\WebHelp\workbook\format_cells.htm" />
    <Content Include="Assets\WebHelp\workbook\format_column.htm" />
    <Content Include="Assets\WebHelp\workbook\format_row.htm" />
    <Content Include="Assets\WebHelp\workbook\freeze_panes.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_ac.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_arithmetic.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_date_time.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_dh.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_financial.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_in.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_logical.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_os.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_search.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_string.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_trigonometry.htm" />
    <Content Include="Assets\WebHelp\workbook\functions_ty.htm" />
    <Content Include="Assets\WebHelp\workbook\goto_cell.htm" />
    <Content Include="Assets\WebHelp\workbook\hide_column.htm" />
    <Content Include="Assets\WebHelp\workbook\hide_row.htm" />
    <Content Include="Assets\WebHelp\workbook\importing_data.htm" />
    <Content Include="Assets\WebHelp\workbook\insert_cells.htm" />
    <Content Include="Assets\WebHelp\workbook\insert_column.htm" />
    <Content Include="Assets\WebHelp\workbook\insert_row.htm" />
    <Content Include="Assets\WebHelp\workbook\insert_sheet.htm" />
    <Content Include="Assets\WebHelp\workbook\lock_worksheet.htm" />
    <Content Include="Assets\WebHelp\workbook\new_workbook.htm" />
    <Content Include="Assets\WebHelp\workbook\page_setup.htm" />
    <Content Include="Assets\WebHelp\workbook\paste_special.htm" />
    <Content Include="Assets\WebHelp\workbook\replace.htm" />
    <Content Include="Assets\WebHelp\workbook\row_height.htm" />
    <Content Include="Assets\WebHelp\workbook\selecting_cells.htm" />
    <Content Include="Assets\WebHelp\workbook\selecting_data.htm" />
    <Content Include="Assets\WebHelp\workbook\set_area_to_print.htm" />
    <Content Include="Assets\WebHelp\workbook\sheet_settings.htm" />
    <Content Include="Assets\WebHelp\workbook\undo.htm" />
    <Content Include="Assets\WebHelp\workbook\unhide_column.htm" />
    <Content Include="Assets\WebHelp\workbook\unhide_row.htm" />
    <Content Include="Assets\WebHelp\workbook\workbook_basics.htm" />
    <Content Include="Assets\WebHelp\workbook\workbook_options.htm" />
    <Content Include="Assets\WebHelp\workbook\working_with_data_in_worksheets.htm" />
    <Content Include="Assets\WebHelp\workbook\worksheet_functions.htm" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationFramework">
      <HintPath>..\..\..\..\..\Windows Kits\10\Windows Performance Toolkit\PresentationFramework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ReleaseWithSigning|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugWatchExceptions|AnyCPU'">
    <DefineConstants>$(DefineConstants);WATCH_EXCEPTIONS</DefineConstants>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  </Target>
</Project>
