<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../StatsDirectUI/Builtins/Regress1.cs" Link="Production/Regress1.cs" />
  </ItemGroup>
</Project>
