//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsDirect.Calculator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Calculator : global::System.Configuration.ApplicationSettingsBase {
        
        private static Calculator defaultInstance = ((Calculator)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Calculator())));
        
        public static Calculator Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CalculatorTop {
            get {
                return ((int)(this["CalculatorTop"]));
            }
            set {
                this["CalculatorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CalculatorLeft {
            get {
                return ((int)(this["CalculatorLeft"]));
            }
            set {
                this["CalculatorLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CalculatorWidth {
            get {
                return ((int)(this["CalculatorWidth"]));
            }
            set {
                this["CalculatorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CalculatorHeight {
            get {
                return ((int)(this["CalculatorHeight"]));
            }
            set {
                this["CalculatorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CalculatorMaximized {
            get {
                return ((bool)(this["CalculatorMaximized"]));
            }
            set {
                this["CalculatorMaximized"] = value;
            }
        }
    }
}
