"""Generates GammaCoefficients.cs: the Taylor coefficients of log Gamma(1 + z) about 0, (-1)^n zeta(n) / n for n = 2 to 64
(DLMF 5.7.3), with zeta(n) from its Euler-Maclaurin sum in 90-digit arithmetic."""
from decimal import Decimal as D, getcontext
from fractions import Fraction as F
from math import comb, factorial
from pathlib import Path
getcontext().prec = 90
B = [F(1)]
for n in range(1, 41):
    B.append(-sum(F(comb(n + 1, k)) * B[k] for k in range(n)) / F(n + 1))
def dec(f):
    return D(f.numerator) / D(f.denominator)
def zeta(s):
    n = D(96)
    value = sum(D(k) ** (-s) for k in range(1, 96)) + n ** (1 - s) / D(s - 1) + n ** (-s) / 2
    for k in range(1, 21):
        rising = 1
        for j in range(2 * k - 1):
            rising *= s + j
        value += dec(B[2 * k]) * D(rising) / D(factorial(2 * k)) * n ** (-s - 2 * k + 1)
    return value
values = [float(((-1) ** n) * zeta(n) / D(n)) for n in range(2, 65)]
p = Path(__file__).parent / 'GammaCoefficients.cs'
p.write_text('// Generated by generate_constants.py: the Taylor coefficients of log Gamma(1 + z) about 0, (-1)^n zeta(n) / n for n = 2 to 64\n'
             'using System;\nnamespace StatsDirect.Numerics.SpecialFunctions;\n\ninternal static class GammaCoefficients\n{\n'
             '    internal static readonly double[] Values = [\n' + ''.join('        ' + repr(v) + ',\n' for v in values) + '    ];\n}\n',
             newline='\r\n')
print('Generated', len(values), 'log-gamma coefficients')
